WE Core: DSPUnitProcessingTests.cpp File Reference
DSPUnitProcessingTests.cpp File Reference
#include "catch.hpp"
#include "CarveDSP/CarveDSPUnit.h"
#include "CarveDSP/Tests/TestData.h"
Functions
SCENARIO ("CarveDSPUnit: Silence in = silence out")
SCENARIO ("CarveDSPUnit: Sine Default")
SCENARIO ("CarveDSPUnit: Parabolic Soft Default")
SCENARIO ("CarveDSPUnit: Parabolic Hard Default")
SCENARIO ("CarveDSPUnit: Asymetric Sine Default")
SCENARIO ("CarveDSPUnit: Exponent Default")
SCENARIO ("CarveDSPUnit: Clipper Default")
Function Documentation
SCENARIO ()
Definition at line 28 of file DSPUnitProcessingTests.cpp.
References WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Sine Default")
Definition at line 54 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Parabolic Soft Default")
Definition at line 90 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Parabolic Hard Default")
Definition at line 126 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Asymetric Sine Default")
Definition at line 162 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Exponent Default")
Definition at line 198 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO ("CarveDSPUnit: Clipper Default")
Definition at line 234 of file DSPUnitProcessingTests.cpp.
References TestData::Carve::Data, CoreMath::LONG_TAU, WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().