WE Core: DSPUnitParameterTests.cpp File Reference
DSPUnitParameterTests.cpp File Reference
#include "catch.hpp"
#include "CarveDSP/CarveDSPUnit.h"
Functions
SCENARIO ("CarveDSPUnit: Parameters can be set and retrieved correctly")
SCENARIO ("CarveDSPUnit: Parameters enforce their bounds correctly")
SCENARIO ("CarveDSPUnit: Parameter combinations that should result in silence output for any input")
Function Documentation
SCENARIO() [1/3]
SCENARIO ("CarveDSPUnit: Parameter combinations that should result in silence output for any input")
Definition at line 88 of file DSPUnitParameterTests.cpp.
References WECore::Carve::CarveDSPUnit< T >::process(), WECore::Carve::CarveDSPUnit< T >::setMode(), WECore::Carve::CarveDSPUnit< T >::setPostGain(), and WECore::Carve::CarveDSPUnit< T >::setPreGain().
SCENARIO() [2/3]
SCENARIO ("CarveDSPUnit: Parameters can be set and retrieved correctly")
Definition at line 25 of file DSPUnitParameterTests.cpp.
References WECore::Carve::CarveDSPUnit< T >::getMode(), WECore::Carve::CarveDSPUnit< T >::getPostGain(), WECore::Carve::CarveDSPUnit< T >::getPreGain(), WECore::Carve::CarveDSPUnit< T >::getTweak(), WECore::Carve::CarveDSPUnit< T >::setMode(), WECore::Carve::CarveDSPUnit< T >::setPostGain(), WECore::Carve::CarveDSPUnit< T >::setPreGain(), and WECore::Carve::CarveDSPUnit< T >::setTweak().
SCENARIO() [3/3]
SCENARIO ("CarveDSPUnit: Parameters enforce their bounds correctly")
Definition at line 54 of file DSPUnitParameterTests.cpp.
References WECore::Carve::CarveDSPUnit< T >::getMode(), WECore::Carve::CarveDSPUnit< T >::getPostGain(), WECore::Carve::CarveDSPUnit< T >::getPreGain(), WECore::Carve::CarveDSPUnit< T >::getTweak(), WECore::Carve::CarveDSPUnit< T >::setMode(), WECore::Carve::CarveDSPUnit< T >::setPostGain(), WECore::Carve::CarveDSPUnit< T >::setPreGain(), and WECore::Carve::CarveDSPUnit< T >::setTweak().