WE Core: MONSTRCrossoverTests.cpp File Reference
MONSTRCrossoverTests.cpp File Reference
#include <memory>
#include "catch.hpp"
#include "TestData.h"
#include "General/CoreMath.h"
#include "MONSTRFilters/MONSTRCrossover.h"
#include "WEFilters/Tests/TestUtils.h"
#include "WEFilters/StereoWidthProcessor.h"
Functions
SCENARIO ("MONSTRCrossover: Parameters can be set and retrieved correctly")
SCENARIO ("MONSTRCrossover: Parameters enforce their bounds correctly")
SCENARIO ("MONSTRCrossover: Silence in = silence out")
SCENARIO ("MONSTRCrossover: Small buffer")
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover frequency below maximum")
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover at maximum")
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover at maximum and only 2 bands")
SCENARIO ("MONSTRCrossover: Adding a band - at maximum number of bands")
SCENARIO ("MONSTRCrossover: Removing bands")
SCENARIO ("MONSTRCrossover: Added band has clean configuration")
SCENARIO ("MONSTRCrossover: All bands muted")
SCENARIO ("MONSTRCrossover: A band is soloed and muted")
SCENARIO ("MONSTRCrossover: All bands are soloed")
SCENARIO ("MONSTRCrossover: EffectsProcessors are not called for muted bands")
SCENARIO ("MONSTRCrossover: EffectsProcessors are not called for bands that aren't soloed")
Function Documentation
SCENARIO() [1/15]
SCENARIO ("MONSTRCrossover: A band is soloed and muted")
Definition at line 417 of file MONSTRCrossoverTests.cpp.
References WECore::TestUtils::generateSine(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsSoloed().
SCENARIO() [2/15]
SCENARIO ("MONSTRCrossover: Added band has clean configuration")
Definition at line 332 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::getIsActive(), WECore::MONSTR::MONSTRCrossover< SampleType >::getIsMuted(), WECore::MONSTR::MONSTRCrossover< SampleType >::removeBand(), WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor(), WECore::MONSTR::MONSTRCrossover< SampleType >::setIsActive(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted().
SCENARIO() [3/15]
SCENARIO ("MONSTRCrossover: Adding a band - at maximum number of bands")
Definition at line 288 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), and WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands().
SCENARIO() [4/15]
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover at maximum and only 2 bands")
Definition at line 268 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands(), WECore::MONSTR::MONSTRCrossover< SampleType >::removeBand(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency().
SCENARIO() [5/15]
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover at maximum")
Definition at line 248 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY(), WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency().
SCENARIO() [6/15]
SCENARIO ("MONSTRCrossover: Adding a band - existing crossover frequency below maximum")
Definition at line 229 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), and WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands().
SCENARIO() [7/15]
SCENARIO ("MONSTRCrossover: All bands are soloed")
Definition at line 445 of file MONSTRCrossoverTests.cpp.
References TestData::MONSTR::Data, WECore::TestUtils::generateSine(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsSoloed().
SCENARIO() [8/15]
SCENARIO ("MONSTRCrossover: All bands muted")
Definition at line 363 of file MONSTRCrossoverTests.cpp.
References WECore::TestUtils::generateSine(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted().
SCENARIO() [9/15]
SCENARIO ("MONSTRCrossover: EffectsProcessors are not called for bands that aren't soloed")
Definition at line 509 of file MONSTRCrossoverTests.cpp.
References WECore::TestUtils::generateSine(), WECore::EffectsProcessor2in2out< SampleType >::process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsSoloed().
SCENARIO() [10/15]
SCENARIO ("MONSTRCrossover: EffectsProcessors are not called for muted bands")
Definition at line 476 of file MONSTRCrossoverTests.cpp.
References WECore::TestUtils::generateSine(), WECore::EffectsProcessor2in2out< SampleType >::process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted().
SCENARIO() [11/15]
SCENARIO ("MONSTRCrossover: Parameters can be set and retrieved correctly")
Definition at line 31 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::getIsActive(), WECore::MONSTR::MONSTRCrossover< SampleType >::getIsMuted(), WECore::MONSTR::MONSTRCrossover< SampleType >::getIsSoloed(), WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency(), WECore::MONSTR::MONSTRCrossover< SampleType >::setIsActive(), WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setIsSoloed().
SCENARIO() [12/15]
SCENARIO ("MONSTRCrossover: Parameters enforce their bounds correctly")
Definition at line 74 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency().
SCENARIO() [13/15]
SCENARIO ("MONSTRCrossover: Removing bands")
Definition at line 307 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands(), and WECore::MONSTR::MONSTRCrossover< SampleType >::removeBand().
SCENARIO() [14/15]
SCENARIO ()
Definition at line 120 of file MONSTRCrossoverTests.cpp.
References WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor().
SCENARIO() [15/15]
SCENARIO ("MONSTRCrossover: Small buffer")
Definition at line 198 of file MONSTRCrossoverTests.cpp.
References TestData::MONSTR::Data, WECore::TestUtils::generateSine(), WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor().