WE Core: PerformanceTests.cpp File Reference
PerformanceTests.cpp File Reference
#include "catch.hpp"
#include <ctime>
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <chrono>
#include "CarveDSP/CarveDSPUnit.h"
#include "MONSTRFilters/MONSTRCrossover.h"
#include "SongbirdFilters/SongbirdFilterModule.h"
Functions
SCENARIO ("Performance: CarveDSPUnit, 100 buffers of 1024 samples each")
SCENARIO ("Performance: SongbirdFilterModule (blend mode), 100 buffers of 1024 samples each")
SCENARIO ("Performance: SongbirdFilterModule (freq mode), 100 buffers of 1024 samples each")
Function Documentation
SCENARIO() [1/3]
SCENARIO ("Performance: CarveDSPUnit, 100 buffers of 1024 samples each")
Definition at line 110 of file PerformanceTests.cpp.
References WECore::Carve::CarveDSPUnit< T >::process(), and WECore::Carve::CarveDSPUnit< T >::setMode().
SCENARIO() [2/3]
SCENARIO ("Performance: SongbirdFilterModule blend mode, 100 buffers of 1024 samples each")
Definition at line 210 of file PerformanceTests.cpp.
References WECore::Songbird::SongbirdFilterModule< T >::Process2in2out(), and WECore::Songbird::SongbirdFilterModule< T >::setModMode().
SCENARIO() [3/3]
SCENARIO ("Performance: SongbirdFilterModule freq mode, 100 buffers of 1024 samples each")
Definition at line 259 of file PerformanceTests.cpp.
References WECore::Songbird::SongbirdFilterModule< T >::Process2in2out(), and WECore::Songbird::SongbirdFilterModule< T >::setModMode().