WE Core: RichterLFOPairTests.cpp File Reference
RichterLFOPairTests.cpp File Reference
#include "catch.hpp"
#include "RichterLFO/RichterLFOPair.h"
Functions
SCENARIO ("RichterLFOPair: Parameters can be set and retrieved correctly")
SCENARIO ("RichterLFOPair: Parameters enforce their bounds correctly")
Function Documentation
SCENARIO() [1/2]
SCENARIO ("RichterLFOPair: Parameters can be set and retrieved correctly")
Definition at line 25 of file RichterLFOPairTests.cpp.
References WECore::Richter::RichterLFO::getBypassSwitch(), WECore::Richter::RichterLFO::getDepth(), WECore::Richter::RichterLFO::getDepthMod(), WECore::Richter::RichterLFO::getFreq(), WECore::Richter::RichterLFO::getFreqMod(), WECore::Richter::RichterLFO::getInvertSwitch(), WECore::Richter::RichterLFO::getManualPhase(), WECore::Richter::RichterLFO::getPhaseSyncSwitch(), WECore::Richter::RichterLFO::getTempoDenom(), WECore::Richter::RichterLFO::getTempoNumer(), WECore::Richter::RichterLFO::getTempoSyncSwitch(), WECore::Richter::RichterLFO::getWave(), WECore::Richter::RichterLFOPair::LFO, WECore::Richter::RichterLFOPair::MOD, WECore::Richter::RichterLFO::setBypassSwitch(), WECore::Richter::RichterLFO::setDepth(), WECore::Richter::RichterLFO::setDepthMod(), WECore::Richter::RichterLFO::setFreq(), WECore::Richter::RichterLFO::setFreqMod(), WECore::Richter::RichterLFO::setInvertSwitch(), WECore::Richter::RichterLFO::setManualPhase(), WECore::Richter::RichterLFO::setPhaseSyncSwitch(), WECore::Richter::RichterLFO::setTempoDenom(), WECore::Richter::RichterLFO::setTempoNumer(), WECore::Richter::RichterLFO::setTempoSyncSwitch(), and WECore::Richter::RichterLFO::setWave().
SCENARIO() [2/2]
SCENARIO ("RichterLFOPair: Parameters enforce their bounds correctly")
Definition at line 111 of file RichterLFOPairTests.cpp.
References WECore::Richter::RichterLFO::getDepth(), WECore::Richter::RichterLFO::getDepthMod(), WECore::Richter::RichterLFO::getFreq(), WECore::Richter::RichterLFO::getFreqMod(), WECore::Richter::RichterLFO::getManualPhase(), WECore::Richter::RichterLFO::getTempoDenom(), WECore::Richter::RichterLFO::getTempoNumer(), WECore::Richter::RichterLFO::getWave(), WECore::Richter::RichterLFOPair::LFO, WECore::Richter::RichterLFOPair::MOD, WECore::Richter::RichterLFO::setDepth(), WECore::Richter::RichterLFO::setDepthMod(), WECore::Richter::RichterLFO::setFreq(), WECore::Richter::RichterLFO::setFreqMod(), WECore::Richter::RichterLFO::setManualPhase(), WECore::Richter::RichterLFO::setTempoDenom(), WECore::Richter::RichterLFO::setTempoNumer(), and WECore::Richter::RichterLFO::setWave().