WE Core: SimpleCompressorTests.cpp File Reference
SimpleCompressorTests.cpp File Reference
#include "catch.hpp"
#include "WEFilters/SimpleCompressor.h"
Functions
SCENARIO ("SimpleCompressor: Parameters can be set and retrieved correctly")
SCENARIO ("SimpleCompressor: Parameters enforce their bounds correctly")
SCENARIO ("SimpleCompressor: Silence in = silence out")
Function Documentation
SCENARIO() [1/3]
SCENARIO ("SimpleCompressor: Parameters can be set and retrieved correctly")
Definition at line 29 of file SimpleCompressorTests.cpp.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::getAttack(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getDirection(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getKneeWidth(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRatio(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRelease(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getThreshold(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setAttack(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setDirection(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setKneeWidth(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRatio(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRelease(), and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setThreshold().
SCENARIO() [2/3]
SCENARIO ("SimpleCompressor: Parameters enforce their bounds correctly")
Definition at line 65 of file SimpleCompressorTests.cpp.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::getAttack(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getKneeWidth(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRatio(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRelease(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::getThreshold(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setAttack(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setKneeWidth(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRatio(), WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRelease(), and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setThreshold().
SCENARIO() [3/3]
SCENARIO ()
Definition at line 104 of file SimpleCompressorTests.cpp.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::process1in1out().