WE Core: SongbirdFilterModuleTests.cpp File Reference
SongbirdFilterModuleTests.cpp File Reference
#include "catch.hpp"
#include "SongbirdFilters/SongbirdFilterModule.h"
#include "SongbirdFilters/Tests/TestData.h"
#include <algorithm>
Functions
SCENARIO ("SongbirdFilterModule: Parameters can be set and retrieved correctly")
SCENARIO ("SongbirdFilterModule: Parameters enforce their bounds correctly")
SCENARIO ("SongbirdFilterModule: Silence in = silence out")
SCENARIO ("SongbirdFilterModule: Freq mode")
SCENARIO ("SongbirdFilterModule: Blend mode")
Function Documentation
SCENARIO() [1/5]
SCENARIO ("SongbirdFilterModule: Blend mode")
Definition at line 168 of file SongbirdFilterModuleTests.cpp.
References TestData::Songbird::Data, WECore::Songbird::SongbirdFilterModule< T >::Process2in2out(), WECore::Songbird::SongbirdFilterModule< T >::setAirGain(), WECore::Songbird::SongbirdFilterModule< T >::setModMode(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().
SCENARIO() [2/5]
SCENARIO ("SongbirdFilterModule: Freq mode")
Definition at line 126 of file SongbirdFilterModuleTests.cpp.
References TestData::Songbird::Data, WECore::Songbird::SongbirdFilterModule< T >::Process2in2out(), WECore::Songbird::SongbirdFilterModule< T >::setAirGain(), WECore::Songbird::SongbirdFilterModule< T >::setModMode(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().
SCENARIO() [3/5]
SCENARIO ("SongbirdFilterModule: Parameters can be set and retrieved correctly")
Definition at line 28 of file SongbirdFilterModuleTests.cpp.
References WECore::Songbird::SongbirdFilterModule< T >::getAirGain(), WECore::Songbird::SongbirdFilterModule< T >::getFilterPosition(), WECore::Songbird::SongbirdFilterModule< T >::getMix(), WECore::Songbird::SongbirdFilterModule< T >::getModMode(), WECore::Songbird::SongbirdFilterModule< T >::getVowel1(), WECore::Songbird::SongbirdFilterModule< T >::getVowel2(), WECore::Songbird::SongbirdFilterModule< T >::setAirGain(), WECore::Songbird::SongbirdFilterModule< T >::setFilterPosition(), WECore::Songbird::SongbirdFilterModule< T >::setMix(), WECore::Songbird::SongbirdFilterModule< T >::setModMode(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().
SCENARIO() [4/5]
SCENARIO ("SongbirdFilterModule: Parameters enforce their bounds correctly")
Definition at line 63 of file SongbirdFilterModuleTests.cpp.
References WECore::Songbird::SongbirdFilterModule< T >::getAirGain(), WECore::Songbird::SongbirdFilterModule< T >::getFilterPosition(), WECore::Songbird::SongbirdFilterModule< T >::getMix(), WECore::Songbird::SongbirdFilterModule< T >::getVowel1(), WECore::Songbird::SongbirdFilterModule< T >::getVowel2(), WECore::Songbird::SongbirdFilterModule< T >::setAirGain(), WECore::Songbird::SongbirdFilterModule< T >::setFilterPosition(), WECore::Songbird::SongbirdFilterModule< T >::setMix(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().
SCENARIO() [5/5]
SCENARIO ()
Definition at line 101 of file SongbirdFilterModuleTests.cpp.
References WECore::Songbird::SongbirdFilterModule< T >::Process2in2out().