WE Core: StereoWidthProcessorTests.cpp File Reference
StereoWidthProcessorTests.cpp File Reference
#include "catch.hpp"
#include "General/CoreMath.h"
#include "TestUtils.h"
#include "WEFilters/StereoWidthProcessor.h"
Functions
SCENARIO ("StereoWidthProcessor: Parameters can be set and retrieved correctly")
SCENARIO ("StereoWidthProcessor: Parameters enforce their bounds correctly")
SCENARIO ("StereoWidthProcessor: Silence in = silence out")
SCENARIO ("StereoWidthProcessor: Neutral width position")
SCENARIO ("StereoWidthProcessor: Stereo to full mono")
Function Documentation
SCENARIO() [1/5]
SCENARIO ("StereoWidthProcessor: Neutral width position")
Definition at line 99 of file StereoWidthProcessorTests.cpp.
References WECore::TestUtils::generateSine(), and WECore::StereoWidth::StereoWidthProcessor< SampleType >::process2in2out().
SCENARIO() [2/5]
SCENARIO ("StereoWidthProcessor: Parameters can be set and retrieved correctly")
Definition at line 27 of file StereoWidthProcessorTests.cpp.
References WECore::StereoWidth::StereoWidthProcessor< SampleType >::getWidth(), and WECore::StereoWidth::StereoWidthProcessor< SampleType >::setWidth().
SCENARIO() [3/5]
SCENARIO ("StereoWidthProcessor: Parameters enforce their bounds correctly")
Definition at line 48 of file StereoWidthProcessorTests.cpp.
References WECore::StereoWidth::StereoWidthProcessor< SampleType >::getWidth(), and WECore::StereoWidth::StereoWidthProcessor< SampleType >::setWidth().
SCENARIO() [4/5]
SCENARIO ()
Definition at line 73 of file StereoWidthProcessorTests.cpp.
References WECore::StereoWidth::StereoWidthProcessor< SampleType >::process2in2out().
SCENARIO() [5/5]
SCENARIO ("StereoWidthProcessor: Stereo to full mono")
Definition at line 128 of file StereoWidthProcessorTests.cpp.
References WECore::TestUtils::generateSine(), WECore::StereoWidth::StereoWidthProcessor< SampleType >::process2in2out(), and WECore::StereoWidth::StereoWidthProcessor< SampleType >::setWidth().