WE Core: TPTSVFilterTests.cpp File Reference
TPTSVFilterTests.cpp File Reference
#include "catch.hpp"
#include "WEFilters/TPTSVFilter.h"
Functions
SCENARIO ("TPTSVFilter: Parameters can be set and retrieved correctly")
SCENARIO ("TPTSVFilter: Parameters enforce their bounds correctly")
SCENARIO ("TPTSVFilter: Silence in = silence out")
SCENARIO ("TPTSVFilter: Clone works correctly")
Function Documentation
SCENARIO() [1/4]
SCENARIO ("TPTSVFilter: Clone works correctly")
Definition at line 109 of file TPTSVFilterTests.cpp.
References WECore::TPTSVF::TPTSVFilter< T >::clone(), WECore::TPTSVF::Parameters::FILTER_MODE, WECore::TPTSVF::TPTSVFilter< T >::getCutoff(), WECore::TPTSVF::TPTSVFilter< T >::getGain(), WECore::TPTSVF::TPTSVFilter< T >::getMode(), WECore::TPTSVF::TPTSVFilter< T >::getQ(), WECore::TPTSVF::TPTSVFilter< T >::processBlock(), WECore::TPTSVF::TPTSVFilter< T >::setCutoff(), WECore::TPTSVF::TPTSVFilter< T >::setGain(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), WECore::TPTSVF::TPTSVFilter< T >::setQ(), and WECore::TPTSVF::TPTSVFilter< T >::setSampleRate().
SCENARIO() [2/4]
SCENARIO ("TPTSVFilter: Parameters can be set and retrieved correctly")
Definition at line 25 of file TPTSVFilterTests.cpp.
References WECore::TPTSVF::TPTSVFilter< T >::getCutoff(), WECore::TPTSVF::TPTSVFilter< T >::getGain(), WECore::TPTSVF::TPTSVFilter< T >::getMode(), WECore::TPTSVF::TPTSVFilter< T >::getQ(), WECore::TPTSVF::TPTSVFilter< T >::setCutoff(), WECore::TPTSVF::TPTSVFilter< T >::setGain(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), and WECore::TPTSVF::TPTSVFilter< T >::setQ().
SCENARIO() [3/4]
SCENARIO ("TPTSVFilter: Parameters enforce their bounds correctly")
Definition at line 54 of file TPTSVFilterTests.cpp.
References WECore::TPTSVF::TPTSVFilter< T >::getCutoff(), WECore::TPTSVF::TPTSVFilter< T >::getGain(), WECore::TPTSVF::TPTSVFilter< T >::getMode(), WECore::TPTSVF::TPTSVFilter< T >::getQ(), WECore::TPTSVF::TPTSVFilter< T >::setCutoff(), WECore::TPTSVF::TPTSVFilter< T >::setGain(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), and WECore::TPTSVF::TPTSVFilter< T >::setQ().
SCENARIO() [4/4]
SCENARIO ()
Definition at line 88 of file TPTSVFilterTests.cpp.
References WECore::TPTSVF::TPTSVFilter< T >::processBlock().