WE Core: WECore::AREnv::AREnvelopeFollower Class Reference
WECore::AREnv::AREnvelopeFollower Class Reference
#include <AREnvelopeFollower.h>
Public Member Functions
AREnvelopeFollower ()
void reset ()
double clockUpdateEnvelope (double inSample)
Setter Methods
void setSampleRate (double sampleRate)
void setAttackTimeMs (double time)
void setReleaseTimeMs (double time)
Getter Methods
double getAttackTimeMs () const
double getReleaseTimeMs () const
double getEnvelope ()
Private Member Functions
double _calcCoef (double timeMs)
Private Attributes
double _envVal
double _attackTimeMs
double _releaseTimeMs
double _attackCoef
double _releaseCoef
double _sampleRate
Detailed Description
A basic envelope follower with controls for attack and release times.
Definition at line 33 of file AREnvelopeFollower.h.
Constructor & Destructor Documentation
AREnvelopeFollower()
WECore::AREnv::AREnvelopeFollower::AREnvelopeFollower () inline
Definition at line 35 of file AREnvelopeFollower.h.
References reset(), and setSampleRate().
Member Function Documentation
_calcCoef()
double WECore::AREnv::AREnvelopeFollower::_calcCoef (double timeMs) inline private
Definition at line 120 of file AREnvelopeFollower.h.
References _sampleRate.
Referenced by setAttackTimeMs(), setReleaseTimeMs(), and setSampleRate().
clockUpdateEnvelope()
double WECore::AREnv::AREnvelopeFollower::clockUpdateEnvelope (double inSample) inline
Updates the envelope with the current sample and returns the updated envelope value. Must be called for every sample.
Parameters
[in] inSample Sample used to update the envelope state
Returns
The updated envelope value
Definition at line 141 of file AREnvelopeFollower.h.
References _attackCoef, _envVal, and _releaseCoef.
getAttackTimeMs()
double WECore::AREnv::AREnvelopeFollower::getAttackTimeMs () const inline
See also
setAttackTimeMs
Definition at line 80 of file AREnvelopeFollower.h.
References _attackTimeMs.
Referenced by SCENARIO().
getEnvelope()
double WECore::AREnv::AREnvelopeFollower::getEnvelope () inline
Returns the latest envelope value without modifying it.
Definition at line 90 of file AREnvelopeFollower.h.
References _envVal.
getReleaseTimeMs()
double WECore::AREnv::AREnvelopeFollower::getReleaseTimeMs () const inline
See also
setReleaseTimeMs
Definition at line 85 of file AREnvelopeFollower.h.
References _releaseTimeMs.
Referenced by SCENARIO().
reset()
void WECore::AREnv::AREnvelopeFollower::reset () inline
Resets the envelope state.
Definition at line 97 of file AREnvelopeFollower.h.
References _envVal.
Referenced by AREnvelopeFollower().
setAttackTimeMs()
void WECore::AREnv::AREnvelopeFollower::setAttackTimeMs (double time) inline
Sets the attack time of the envelope.
See also
ATTACK_MS for valid values
Parameters
[in] time Attack time in milliseconds
Definition at line 131 of file AREnvelopeFollower.h.
References _attackCoef, _attackTimeMs, _calcCoef(), and WECore::AREnv::Parameters::ATTACK_MS().
Referenced by SCENARIO().
setReleaseTimeMs()
void WECore::AREnv::AREnvelopeFollower::setReleaseTimeMs (double time) inline
Sets the release time of the envelope.
See also
RELEASE_MS for valid values
Parameters
[in] time Release time in milliseconds
Definition at line 136 of file AREnvelopeFollower.h.
References _calcCoef(), _releaseCoef, _releaseTimeMs, and WECore::AREnv::Parameters::RELEASE_MS().
Referenced by SCENARIO().
setSampleRate()
void WECore::AREnv::AREnvelopeFollower::setSampleRate (double sampleRate) inline
Sets the sample rate the envelope will operate at. It is recommended that you call this at some point before calling clockUpdateEnvelope.
Parameters
[in] sampleRate The sample rate in Hz
Definition at line 125 of file AREnvelopeFollower.h.
References _attackCoef, _attackTimeMs, _calcCoef(), _releaseCoef, _releaseTimeMs, and _sampleRate.
Referenced by AREnvelopeFollower().
Member Data Documentation
_attackCoef
double WECore::AREnv::AREnvelopeFollower::_attackCoef private
Definition at line 115 of file AREnvelopeFollower.h.
Referenced by clockUpdateEnvelope(), setAttackTimeMs(), and setSampleRate().
_attackTimeMs
double WECore::AREnv::AREnvelopeFollower::_attackTimeMs private
Definition at line 112 of file AREnvelopeFollower.h.
Referenced by getAttackTimeMs(), setAttackTimeMs(), and setSampleRate().
_envVal
double WECore::AREnv::AREnvelopeFollower::_envVal private
Definition at line 110 of file AREnvelopeFollower.h.
Referenced by clockUpdateEnvelope(), getEnvelope(), and reset().
_releaseCoef
double WECore::AREnv::AREnvelopeFollower::_releaseCoef private
Definition at line 116 of file AREnvelopeFollower.h.
Referenced by clockUpdateEnvelope(), setReleaseTimeMs(), and setSampleRate().
_releaseTimeMs
double WECore::AREnv::AREnvelopeFollower::_releaseTimeMs private
Definition at line 113 of file AREnvelopeFollower.h.
Referenced by getReleaseTimeMs(), setReleaseTimeMs(), and setSampleRate().
_sampleRate
double WECore::AREnv::AREnvelopeFollower::_sampleRate private
Definition at line 118 of file AREnvelopeFollower.h.
Referenced by _calcCoef(), and setSampleRate().
The documentation for this class was generated from the following file:
AREnvelopeFollower.h