WE Core: WECore::StereoWidth::StereoWidthProcessor< SampleType > Class Template Reference
WECore::StereoWidth::StereoWidthProcessor< SampleType > Class Template Reference
#include <StereoWidthProcessor.h>
Public Member Functions
StereoWidthProcessor ()
virtual ~StereoWidthProcessor () override=default
void setWidth (double val)
double getWidth () const
virtual void process2in2out (SampleType *inSamplesLeft, SampleType *inSamplesRight, size_t numSamples) override
Public Member Functions inherited from WECore::EffectsProcessor< SampleType >
EffectsProcessor ()=default
virtual ~EffectsProcessor ()=default
virtual void process1in1out (SampleType *, size_t)
virtual void process1in2out (SampleType *, SampleType *, size_t)
virtual void reset ()
Private Attributes
double _width
Detailed Description
template<typename SampleType>
class WECore::StereoWidth::StereoWidthProcessor< SampleType >
Processor which can apply stereo widening or narrowing.
Definition at line 37 of file StereoWidthProcessor.h.
Constructor & Destructor Documentation
StereoWidthProcessor()
template<typename SampleType > WECore::StereoWidth::StereoWidthProcessor< SampleType >::StereoWidthProcessor () inline
Definition at line 39 of file StereoWidthProcessor.h.
~StereoWidthProcessor()
template<typename SampleType > virtual WECore::StereoWidth::StereoWidthProcessor< SampleType >::~StereoWidthProcessor () override virtual default
Member Function Documentation
getWidth()
template<typename SampleType > double WECore::StereoWidth::StereoWidthProcessor< SampleType >::getWidth () const inline
See also
setWidth
Definition at line 57 of file StereoWidthProcessor.h.
References WECore::StereoWidth::StereoWidthProcessor< SampleType >::_width.
Referenced by SCENARIO().
process2in2out()
template<typename SampleType > void WECore::StereoWidth::StereoWidthProcessor< SampleType >::process2in2out (SampleType * inSamplesLeft, SampleType * inSamplesRight, size_t numSamples) inline override virtual
Reimplemented from WECore::EffectsProcessor< SampleType >.
Definition at line 69 of file StereoWidthProcessor.h.
Referenced by SCENARIO().
setWidth()
template<typename SampleType > void WECore::StereoWidth::StereoWidthProcessor< SampleType >::setWidth (double val) inline
Sets the stereo width. 0 = mono 1 = neutral, no processing 2 = highest width
Parameters
val The width to be applied.
See also
WIDTH for valid values
Definition at line 52 of file StereoWidthProcessor.h.
References WECore::StereoWidth::StereoWidthProcessor< SampleType >::_width, and WECore::StereoWidth::Parameters::WIDTH().
Referenced by SCENARIO().
Member Data Documentation
_width
template<typename SampleType > double WECore::StereoWidth::StereoWidthProcessor< SampleType >::_width private
Definition at line 65 of file StereoWidthProcessor.h.
Referenced by WECore::StereoWidth::StereoWidthProcessor< SampleType >::getWidth(), and WECore::StereoWidth::StereoWidthProcessor< SampleType >::setWidth().
The documentation for this class was generated from the following file:
StereoWidthProcessor.h