WE Core: WECore::MONSTR::MONSTRCrossover< SampleType > Class Template Reference
WECore::MONSTR::MONSTRCrossover< SampleType > Class Template Reference
#include <MONSTRCrossover.h>
Classes
class BandWrapper
Public Member Functions
MONSTRCrossover ()
virtual ~MONSTRCrossover ()=default
void addBand ()
void removeBand ()
void Process2in2out (SampleType *leftSample, SampleType *rightSample, size_t numSamples)
void reset ()
Setter Methods
void setIsActive (size_t index, bool isActive)
void setIsMuted (size_t index, bool isMuted)
void setIsSoloed (size_t index, bool isSoloed)
void setCrossoverFrequency (size_t index, double val)
void setEffectsProcessor (size_t index, std::shared_ptr< EffectsProcessor2in2out< SampleType > > processor)
void setSampleRate (double newSampleRate)
void setNumBands (int val)
Getter Methods
bool getIsActive (size_t index) const
bool getIsMuted (size_t index) const
bool getIsSoloed (size_t index) const
double getCrossoverFrequency (size_t index) const
size_t getNumBands ()
Private Attributes
size_t _numBands
size_t _numBandsSoloed
std::array< BandWrapper, Parameters::_MAX_NUM_BANDS > _bands
Static Private Attributes
static constexpr unsigned int INTERNAL_BUFFER_SIZE = 512
Detailed Description
template<typename SampleType>
class WECore::MONSTR::MONSTRCrossover< SampleType >
Class which provides three band stereo width control.
This class contains three MONSTRBand objects, and may later be expanded to support a variable number of bands.
To use this class, use the setter and getter methods to manipulate crossover parameters which are shared by several bands (crossover frequencies), and call the setter and getter methods of each band to manipulate parameters which are particular to each band. Call the reset, setSampleRate and process methods as required.
See also
MONSTRBand
The below example shows how to prepare a MONSTRCrossover object to process audio:
MONSTRCrossover crossover;
crossover.setSampleRate(44100);
Then when you have a buffer ready:
crossover.Process2in2out(leftSample, rightSample, numSamples);
Definition at line 55 of file MONSTRCrossover.h.
Constructor & Destructor Documentation
MONSTRCrossover()
template<typename SampleType > WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover
Definition at line 233 of file MONSTRCrossover.h.
References WECore::MONSTR::MONSTRCrossover< SampleType >::_bands, WECore::MONSTR::Parameters::_DEFAULT_NUM_BANDS, WECore::MONSTR::Parameters::CROSSOVER_LOWER_DEFAULT, WECore::MONSTR::Parameters::CROSSOVER_UPPER_DEFAULT, WECore::MONSTR::MIDDLE, WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency(), and WECore::MONSTR::UPPER.
~MONSTRCrossover()
template<typename SampleType > virtual WECore::MONSTR::MONSTRCrossover< SampleType >::~MONSTRCrossover () virtual default
Member Function Documentation
addBand()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::addBand inline
Increments the number of bands (if currently below the maximum number)
Definition at line 389 of file MONSTRCrossover.h.
References WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY(), WECore::MONSTR::MIDDLE, WECore::MONSTR::Parameters::NUM_BANDS(), and WECore::MONSTR::UPPER.
Referenced by SCENARIO().
getCrossoverFrequency()
template<typename SampleType > double WECore::MONSTR::MONSTRCrossover< SampleType >::getCrossoverFrequency (size_t index) const inline
Gets the crossover frequency of the band at the provided index.
Parameters
index The crossover to get.
Returns
The frequency in Hz of the lower crossover point
See also
CROSSOVER_FREQUENCY for valid values
Definition at line 378 of file MONSTRCrossover.h.
Referenced by SCENARIO().
getIsActive()
template<typename SampleType > bool WECore::MONSTR::MONSTRCrossover< SampleType >::getIsActive (size_t index) const inline
Gets whether the given band is applying processing.
Parameters
index The band to get
Returns
True if the band is applying processing, false if bypassed
Definition at line 345 of file MONSTRCrossover.h.
Referenced by SCENARIO().
getIsMuted()
template<typename SampleType > bool WECore::MONSTR::MONSTRCrossover< SampleType >::getIsMuted (size_t index) const inline
Gets whether the given band is muted.
Parameters
index The band to get
Returns
True if the band is muted, false if unmuted
Definition at line 356 of file MONSTRCrossover.h.
Referenced by SCENARIO().
getIsSoloed()
template<typename SampleType > bool WECore::MONSTR::MONSTRCrossover< SampleType >::getIsSoloed (size_t index) const inline
Gets whether the given band is soloed.
Parameters
index The band to get
Returns
True if the band is soloed, false if unsoloed
Definition at line 367 of file MONSTRCrossover.h.
Referenced by SCENARIO().
getNumBands()
template<typename SampleType > size_t WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands () inline
Returns the number of bands available. Increased or decreased using addBand() and removeBand().
Returns
Number of bands
See also
NUM_BANDS for valid values
Definition at line 178 of file MONSTRCrossover.h.
References WECore::MONSTR::MONSTRCrossover< SampleType >::_numBands.
Referenced by SCENARIO().
Process2in2out()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::Process2in2out (SampleType * leftSample, SampleType * rightSample, size_t numSamples) inline
Applies the filtering to a stereo buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
[out] leftSample Pointer to the first sample of the left channel's buffer
[out] rightSample Pointer to the first sample of the right channel's buffer
[in] numSamples Number of samples in the buffer. The left and right buffers must be the same size
Definition at line 440 of file MONSTRCrossover.h.
Referenced by SCENARIO().
removeBand()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::removeBand inline
Decrements the number of bands (if currently above the minimum)
Definition at line 423 of file MONSTRCrossover.h.
References WECore::MONSTR::Parameters::NUM_BANDS(), and WECore::MONSTR::UPPER.
Referenced by SCENARIO().
reset()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::reset inline
Resets all filters. Call this whenever the audio stream is interrupted (ie. the playhead is moved)
Definition at line 500 of file MONSTRCrossover.h.
setCrossoverFrequency()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency (size_t index, double val) inline
Sets the crossover frequency of the band at the provided index.
Parameters
index The crossover to set
val The frequency in Hz to set the crossover point to
See also
CROSSOVER_FREQUENCY for valid values
Definition at line 279 of file MONSTRCrossover.h.
References WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY().
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover(), and SCENARIO().
setEffectsProcessor()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setEffectsProcessor (size_t index, std::shared_ptr< EffectsProcessor2in2out< SampleType > > processor) inline
Sets the effects processor which will be used by the given band.
Parameters
index The band to set
processor EffectsProcessor to use
Definition at line 314 of file MONSTRCrossover.h.
Referenced by SCENARIO().
setIsActive()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setIsActive (size_t index, bool isActive) inline
Activates or bypasses the processing of the given band.
Parameters
index The band to set
isActive Set to true if the band's processing should be active
Definition at line 247 of file MONSTRCrossover.h.
Referenced by SCENARIO().
setIsMuted()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setIsMuted (size_t index, bool isMuted) inline
Mutes the given band.
Parameters
index The band to set
isMuted Set to true if the band should be muted
Definition at line 254 of file MONSTRCrossover.h.
Referenced by SCENARIO().
setIsSoloed()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setIsSoloed (size_t index, bool isSoloed) inline
Solos the given band.
Parameters
index The band to set
isSoloed Set to true if the band should be soloed
Definition at line 261 of file MONSTRCrossover.h.
Referenced by SCENARIO().
setNumBands()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setNumBands (int val) inline
Sets the number of bands without performing any logic to configure the crossover frequencies of the new bands.
Only use this if you're going to manually set the frequencies of the new bands (ie. when restoring a saved state by setting the number of bands, then the crossover frequencies).
Definition at line 329 of file MONSTRCrossover.h.
References WECore::MONSTR::LOWER, WECore::MONSTR::MIDDLE, WECore::MONSTR::Parameters::NUM_BANDS(), and WECore::MONSTR::UPPER.
setSampleRate()
template<typename SampleType > void WECore::MONSTR::MONSTRCrossover< SampleType >::setSampleRate (double newSampleRate) inline
Configures the filters for the correct sample rate. Ensure this is called before attempting to process audio.
Parameters
newSampleRate The sample rate the filter should be configured for
Definition at line 322 of file MONSTRCrossover.h.
Member Data Documentation
_bands
template<typename SampleType > std::array<BandWrapper, Parameters::_MAX_NUM_BANDS> WECore::MONSTR::MONSTRCrossover< SampleType >::_bands private
Definition at line 229 of file MONSTRCrossover.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover().
_numBands
template<typename SampleType > size_t WECore::MONSTR::MONSTRCrossover< SampleType >::_numBands private
Definition at line 227 of file MONSTRCrossover.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::getNumBands().
_numBandsSoloed
template<typename SampleType > size_t WECore::MONSTR::MONSTRCrossover< SampleType >::_numBandsSoloed private
Definition at line 228 of file MONSTRCrossover.h.
INTERNAL_BUFFER_SIZE
template<typename SampleType > constexpr unsigned int WECore::MONSTR::MONSTRCrossover< SampleType >::INTERNAL_BUFFER_SIZE = 512 static constexpr private
Definition at line 212 of file MONSTRCrossover.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::BandWrapper::BandWrapper().
The documentation for this class was generated from the following files:
MONSTRBand.h
MONSTRCrossover.h