WE Core: WECore::Richter::RichterLFOBase Class Reference
WECore::Richter::RichterLFOBase Class Reference
#include <RichterLFOBase.h>
Public Member Functions
RichterLFOBase ()
virtual ~RichterLFOBase () override=default
void prepareForNextBuffer (double bpm, double timeInSeconds, double sampleRate)
Getter Methods
bool getBypassSwitch () const
bool getPhaseSyncSwitch () const
bool getTempoSyncSwitch () const
bool getInvertSwitch () const
int getWave () const
double getDepth () const
double getFreq () const
int getManualPhase () const
double getTempoNumer () const
double getTempoDenom () const
int getIndexOffset ()
Setter Methods
void setBypassSwitch (bool val)
void setPhaseSyncSwitch (bool val)
void setTempoSyncSwitch (bool val)
void setInvertSwitch (bool val)
void setTempoNumer (int val)
void setTempoDenom (int val)
void setFreq (double val)
void setDepth (double val)
void setManualPhase (int val)
void setWave (int val)
void setWaveTablePointers ()
void setIndexOffset (int val)
Public Member Functions inherited from WECore::ModulationSource< double >
ModulationSource ()
virtual ~ModulationSource ()=default
double getNextOutput (double inSample)
double getLastOutput () const
void reset ()
Protected Member Functions
virtual void _resetImpl () override
void _calcPhaseOffset (double timeInSeconds)
void _calcFreq (double bpm)
void _calcSamplesPerTremoloCycle (double sampleRate)
void _calcNextScale ()
void calcIndexAndScaleInLoop ()
Protected Attributes
int _manualPhase
int _wave
int _index
int _indexOffset
long _samplesProcessed
bool _bypassSwitch
bool _tempoSyncSwitch
bool _phaseSyncSwitch
bool _invertSwitch
bool _needsPhaseCalc
double _tempoNumer
double _tempoDenom
double _tempoFreq
double _freq
double _depth
double _samplesPerTremoloCycle
double _gain
double _offset
double _currentScale
double _nextScale
const double * _waveArrayPointer
Friends
class RichterLFOPair
Detailed Description
A bass class for providing most of the functionality needed for an LFO. This cannot be used used directly "as-is" in your project. For an LFO which can be dropped straight into your project, see RichterLFO or RichterMOD, which complete the implementation of this class.
Supports multiple wave shapes, tempo sync, and phase sync for consistent playback no matter where the host playhead started playback from.
Definition at line 43 of file RichterLFOBase.h.
Constructor & Destructor Documentation
RichterLFOBase()
WECore::Richter::RichterLFOBase::RichterLFOBase () inline
Initialises parameters to default values.
Definition at line 49 of file RichterLFOBase.h.
~RichterLFOBase()
virtual WECore::Richter::RichterLFOBase::~RichterLFOBase () override virtual default
Member Function Documentation
_calcFreq()
void WECore::Richter::RichterLFOBase::_calcFreq (double bpm) inline protected
Calculates the frequency of the oscillator. Will use either the frequency or tempoNumer/tempoDenom depending on whether tempo sync is enabled.
Parameters
bpm Current bpm of the host DAW
Definition at line 273 of file RichterLFOBase.h.
References _freq, _tempoDenom, _tempoFreq, _tempoNumer, _tempoSyncSwitch, and WECore::Richter::Parameters::FREQ().
Referenced by prepareForNextBuffer(), and WECore::Richter::RichterLFOPair::prepareForNextBuffer().
_calcNextScale()
void WECore::Richter::RichterLFOBase::_calcNextScale () inline protected
Calculates the scale factor to be applied when calculating the index.
Definition at line 205 of file RichterLFOBase.h.
References _nextScale, _samplesPerTremoloCycle, and WECore::Richter::Wavetables::SIZE.
Referenced by prepareForNextBuffer(), and WECore::Richter::RichterLFOPair::prepareForNextBuffer().
_calcPhaseOffset()
void WECore::Richter::RichterLFOBase::_calcPhaseOffset (double timeInSeconds) inline protected
Calculates the phase offset to be applied to the oscillator, including any offset required by the phase sync and any offset applied by the user.
Parameters
timeInSeconds Position of the host DAW's playhead at the start of playback.
Definition at line 252 of file RichterLFOBase.h.
References _freq, _indexOffset, _manualPhase, _needsPhaseCalc, _phaseSyncSwitch, and WECore::Richter::Wavetables::SIZE.
Referenced by prepareForNextBuffer(), and WECore::Richter::RichterLFOPair::prepareForNextBuffer().
_calcSamplesPerTremoloCycle()
void WECore::Richter::RichterLFOBase::_calcSamplesPerTremoloCycle (double sampleRate) inline protected
Calculates the number of samples which pass in the same time as one cycle of the LFO. Dependant on the LFO frequency and the sample rate.
Parameters
sampleRate Sample rate of the host DAW
Definition at line 198 of file RichterLFOBase.h.
References _freq, and _samplesPerTremoloCycle.
Referenced by prepareForNextBuffer(), and WECore::Richter::RichterLFOPair::prepareForNextBuffer().
_resetImpl()
void WECore::Richter::RichterLFOBase::_resetImpl () inline override protected virtual
Resets internal counters including indexOffset and currentScale.
Implements WECore::ModulationSource< double >.
Definition at line 244 of file RichterLFOBase.h.
References _currentScale, _indexOffset, _needsPhaseCalc, and _samplesProcessed.
calcIndexAndScaleInLoop()
void WECore::Richter::RichterLFOBase::calcIndexAndScaleInLoop () inline protected
Calculates the current index of the oscillator in its wavetable. Includes protection against indexes out of range (caused by phase offset) and updates currentScale. Call from within the processing loop. Increments the number of samples processed
Definition at line 284 of file RichterLFOBase.h.
References _currentScale, _gain, _index, _indexOffset, _nextScale, _samplesProcessed, _waveArrayPointer, CoreMath::compareFloatsEqual(), and WECore::Richter::Wavetables::SIZE.
Referenced by WECore::Richter::RichterLFO::_getNextOutputImpl(), and WECore::Richter::RichterMOD::_getNextOutputImpl().
getBypassSwitch()
bool WECore::Richter::RichterLFOBase::getBypassSwitch () const inline
Definition at line 79 of file RichterLFOBase.h.
References _bypassSwitch.
Referenced by WECore::Richter::RichterLFOPair::_getNextOutputImpl(), and SCENARIO().
getDepth()
double WECore::Richter::RichterLFOBase::getDepth () const inline
Definition at line 89 of file RichterLFOBase.h.
References _depth.
Referenced by WECore::Richter::RichterLFOPair::_getNextOutputImpl(), and SCENARIO().
getFreq()
double WECore::Richter::RichterLFOBase::getFreq () const inline
Definition at line 91 of file RichterLFOBase.h.
References _freq.
Referenced by SCENARIO().
getIndexOffset()
int WECore::Richter::RichterLFOBase::getIndexOffset () inline
Definition at line 99 of file RichterLFOBase.h.
References _indexOffset.
getInvertSwitch()
bool WECore::Richter::RichterLFOBase::getInvertSwitch () const inline
Definition at line 85 of file RichterLFOBase.h.
References _invertSwitch.
Referenced by SCENARIO().
getManualPhase()
int WECore::Richter::RichterLFOBase::getManualPhase () const inline
Definition at line 93 of file RichterLFOBase.h.
References _manualPhase.
Referenced by SCENARIO().
getPhaseSyncSwitch()
bool WECore::Richter::RichterLFOBase::getPhaseSyncSwitch () const inline
Definition at line 81 of file RichterLFOBase.h.
References _phaseSyncSwitch.
Referenced by SCENARIO().
getTempoDenom()
double WECore::Richter::RichterLFOBase::getTempoDenom () const inline
Definition at line 97 of file RichterLFOBase.h.
References _tempoDenom.
Referenced by SCENARIO().
getTempoNumer()
double WECore::Richter::RichterLFOBase::getTempoNumer () const inline
Definition at line 95 of file RichterLFOBase.h.
References _tempoNumer.
Referenced by SCENARIO().
getTempoSyncSwitch()
bool WECore::Richter::RichterLFOBase::getTempoSyncSwitch () const inline
Definition at line 83 of file RichterLFOBase.h.
References _tempoSyncSwitch.
Referenced by SCENARIO().
getWave()
int WECore::Richter::RichterLFOBase::getWave () const inline
Definition at line 87 of file RichterLFOBase.h.
References _wave.
Referenced by SCENARIO().
prepareForNextBuffer()
void WECore::Richter::RichterLFOBase::prepareForNextBuffer (double bpm, double timeInSeconds, double sampleRate) inline
Prepares for processing the next buffer of samples. For example if using JUCE, you would call this in your processBlock() method before doing any processing.
Parameters
bpm Current bpm of the host
timeInSeconds Position of the host DAW's playhead at the start of playback.
sampleRate Current sample rate of the host
Definition at line 233 of file RichterLFOBase.h.
References _calcFreq(), _calcNextScale(), _calcPhaseOffset(), _calcSamplesPerTremoloCycle(), and setWaveTablePointers().
setBypassSwitch()
void WECore::Richter::RichterLFOBase::setBypassSwitch (bool val) inline
Definition at line 106 of file RichterLFOBase.h.
References _bypassSwitch.
Referenced by SCENARIO().
setDepth()
void WECore::Richter::RichterLFOBase::setDepth (double val) inline
Definition at line 120 of file RichterLFOBase.h.
References _depth, and WECore::Richter::Parameters::DEPTH().
Referenced by SCENARIO().
setFreq()
void WECore::Richter::RichterLFOBase::setFreq (double val) inline
Definition at line 118 of file RichterLFOBase.h.
References _freq, and WECore::Richter::Parameters::FREQ().
Referenced by SCENARIO().
setIndexOffset()
void WECore::Richter::RichterLFOBase::setIndexOffset (int val) inline
Definition at line 128 of file RichterLFOBase.h.
References _indexOffset.
setInvertSwitch()
void WECore::Richter::RichterLFOBase::setInvertSwitch (bool val) inline
Definition at line 112 of file RichterLFOBase.h.
References _invertSwitch.
Referenced by SCENARIO().
setManualPhase()
void WECore::Richter::RichterLFOBase::setManualPhase (int val) inline
Definition at line 122 of file RichterLFOBase.h.
References _manualPhase, and WECore::Richter::Parameters::PHASE().
Referenced by SCENARIO().
setPhaseSyncSwitch()
void WECore::Richter::RichterLFOBase::setPhaseSyncSwitch (bool val) inline
Definition at line 108 of file RichterLFOBase.h.
References _phaseSyncSwitch.
Referenced by SCENARIO().
setTempoDenom()
void WECore::Richter::RichterLFOBase::setTempoDenom (int val) inline
Definition at line 116 of file RichterLFOBase.h.
References _tempoDenom, and WECore::Richter::Parameters::TEMPODENOM().
Referenced by SCENARIO().
setTempoNumer()
void WECore::Richter::RichterLFOBase::setTempoNumer (int val) inline
Definition at line 114 of file RichterLFOBase.h.
References _tempoNumer, and WECore::Richter::Parameters::TEMPONUMER().
Referenced by SCENARIO().
setTempoSyncSwitch()
void WECore::Richter::RichterLFOBase::setTempoSyncSwitch (bool val) inline
Definition at line 110 of file RichterLFOBase.h.
References _tempoSyncSwitch.
Referenced by SCENARIO().
setWave()
void WECore::Richter::RichterLFOBase::setWave (int val) inline
Definition at line 124 of file RichterLFOBase.h.
References _wave, ParameterDefinition::BaseParameter< T >::BoundsCheck(), and WECore::Richter::Parameters::WAVE.
Referenced by SCENARIO().
setWaveTablePointers()
void WECore::Richter::RichterLFOBase::setWaveTablePointers () inline
Definition at line 219 of file RichterLFOBase.h.
References _wave, _waveArrayPointer, WECore::Richter::Wavetables::getInstance(), WECore::Richter::Wavetables::getSaw(), WECore::Richter::Wavetables::getSidechain(), WECore::Richter::Wavetables::getSine(), WECore::Richter::Wavetables::getSquare(), and WECore::Richter::Parameters::WAVE.
Referenced by prepareForNextBuffer(), and WECore::Richter::RichterLFOPair::prepareForNextBuffer().
Friends And Related Function Documentation
RichterLFOPair
friend class RichterLFOPair friend
Definition at line 74 of file RichterLFOBase.h.
Member Data Documentation
_bypassSwitch
bool WECore::Richter::RichterLFOBase::_bypassSwitch protected
Definition at line 151 of file RichterLFOBase.h.
Referenced by WECore::Richter::RichterMOD::_calcGain(), WECore::Richter::RichterLFO::_getNextOutputImpl(), getBypassSwitch(), and setBypassSwitch().
_currentScale
double WECore::Richter::RichterLFOBase::_currentScale protected
Definition at line 165 of file RichterLFOBase.h.
Referenced by _resetImpl(), and calcIndexAndScaleInLoop().
_depth
double WECore::Richter::RichterLFOBase::_depth protected
Definition at line 161 of file RichterLFOBase.h.
Referenced by WECore::Richter::RichterLFO::_calcDepthInLoop(), WECore::Richter::RichterMOD::_calcGain(), WECore::Richter::RichterLFO::_getNextOutputImpl(), getDepth(), and setDepth().
_freq
double WECore::Richter::RichterLFOBase::_freq protected
Definition at line 160 of file RichterLFOBase.h.
Referenced by _calcFreq(), WECore::Richter::RichterLFO::_calcFreqInLoop(), _calcPhaseOffset(), _calcSamplesPerTremoloCycle(), getFreq(), and setFreq().
_gain
double WECore::Richter::RichterLFOBase::_gain protected
Definition at line 163 of file RichterLFOBase.h.
Referenced by WECore::Richter::RichterMOD::_calcGain(), WECore::Richter::RichterLFO::_getNextOutputImpl(), and calcIndexAndScaleInLoop().
_index
int WECore::Richter::RichterLFOBase::_index protected
Definition at line 146 of file RichterLFOBase.h.
Referenced by calcIndexAndScaleInLoop().
_indexOffset
int WECore::Richter::RichterLFOBase::_indexOffset protected
Definition at line 147 of file RichterLFOBase.h.
Referenced by _calcPhaseOffset(), _resetImpl(), calcIndexAndScaleInLoop(), getIndexOffset(), and setIndexOffset().
_invertSwitch
bool WECore::Richter::RichterLFOBase::_invertSwitch protected
Definition at line 154 of file RichterLFOBase.h.
Referenced by WECore::Richter::RichterMOD::_calcGain(), WECore::Richter::RichterLFO::_getNextOutputImpl(), getInvertSwitch(), and setInvertSwitch().
_manualPhase
int WECore::Richter::RichterLFOBase::_manualPhase protected
Definition at line 144 of file RichterLFOBase.h.
Referenced by _calcPhaseOffset(), getManualPhase(), and setManualPhase().
_needsPhaseCalc
bool WECore::Richter::RichterLFOBase::_needsPhaseCalc protected
Definition at line 155 of file RichterLFOBase.h.
Referenced by _calcPhaseOffset(), and _resetImpl().
_nextScale
double WECore::Richter::RichterLFOBase::_nextScale protected
Definition at line 166 of file RichterLFOBase.h.
Referenced by _calcNextScale(), and calcIndexAndScaleInLoop().
_offset
double WECore::Richter::RichterLFOBase::_offset protected
Definition at line 164 of file RichterLFOBase.h.
_phaseSyncSwitch
bool WECore::Richter::RichterLFOBase::_phaseSyncSwitch protected
Definition at line 153 of file RichterLFOBase.h.
Referenced by _calcPhaseOffset(), getPhaseSyncSwitch(), and setPhaseSyncSwitch().
_samplesPerTremoloCycle
double WECore::Richter::RichterLFOBase::_samplesPerTremoloCycle protected
Definition at line 162 of file RichterLFOBase.h.
Referenced by _calcNextScale(), and _calcSamplesPerTremoloCycle().
_samplesProcessed
long WECore::Richter::RichterLFOBase::_samplesProcessed protected
Definition at line 149 of file RichterLFOBase.h.
Referenced by _resetImpl(), and calcIndexAndScaleInLoop().
_tempoDenom
double WECore::Richter::RichterLFOBase::_tempoDenom protected
Definition at line 158 of file RichterLFOBase.h.
Referenced by _calcFreq(), getTempoDenom(), and setTempoDenom().
_tempoFreq
double WECore::Richter::RichterLFOBase::_tempoFreq protected
Definition at line 159 of file RichterLFOBase.h.
Referenced by _calcFreq().
_tempoNumer
double WECore::Richter::RichterLFOBase::_tempoNumer protected
Definition at line 157 of file RichterLFOBase.h.
Referenced by _calcFreq(), getTempoNumer(), and setTempoNumer().
_tempoSyncSwitch
bool WECore::Richter::RichterLFOBase::_tempoSyncSwitch protected
Definition at line 152 of file RichterLFOBase.h.
Referenced by _calcFreq(), WECore::Richter::RichterLFO::_calcFreqInLoop(), getTempoSyncSwitch(), and setTempoSyncSwitch().
_wave
int WECore::Richter::RichterLFOBase::_wave protected
Definition at line 145 of file RichterLFOBase.h.
Referenced by getWave(), setWave(), and setWaveTablePointers().
_waveArrayPointer
const double* WECore::Richter::RichterLFOBase::_waveArrayPointer protected
Definition at line 168 of file RichterLFOBase.h.
Referenced by calcIndexAndScaleInLoop(), and setWaveTablePointers().
The documentation for this class was generated from the following file:
RichterLFOBase.h