WE Core: WECore::AREnv::AREnvelopeFollowerBase Class Reference
WECore::AREnv::AREnvelopeFollowerBase Class Reference abstract
#include <AREnvelopeFollowerBase.h>
Public Member Functions
AREnvelopeFollowerBase ()
virtual ~AREnvelopeFollowerBase () override=default
Setter Methods
void setSampleRate (double sampleRate)
void setAttackTimeMs (double time)
void setReleaseTimeMs (double time)
void setFilterEnabled (bool isEnabled)
void setLowCutHz (double freq)
void setHighCutHz (double freq)
Getter Methods
double getAttackTimeMs () const
double getReleaseTimeMs () const
bool getFilterEnabled () const
double getLowCutHz () const
double getHighCutHz () const
Public Member Functions inherited from WECore::ModulationSource< double >
ModulationSource ()
virtual ~ModulationSource ()=default
double getNextOutput (double inSample)
virtual double getLastOutput () const
void reset ()
Protected Member Functions
double _getNextOutputImpl (double inSample) override
virtual double _envGetNextOutputImpl (double inSample)=0
void _resetImpl () override
double _calcCoef (double timeMs)
Protected Member Functions inherited from WECore::ModulationSource< double >
Protected Attributes
double _envVal
double _attackTimeMs
double _releaseTimeMs
double _attackCoef
double _releaseCoef
bool _filterEnabled
TPTSVF::TPTSVFilter< double > _lowCutFilter
TPTSVF::TPTSVFilter< double > _highCutFilter
double _sampleRate
Protected Attributes inherited from WECore::ModulationSource< double >
double _cachedOutput
Detailed Description
Base class for an envelope follower with controls for attack and release times, with optional low/high cut filters before the envelope stage.
Definition at line 33 of file AREnvelopeFollowerBase.h.
Constructor & Destructor Documentation
AREnvelopeFollowerBase()
WECore::AREnv::AREnvelopeFollowerBase::AREnvelopeFollowerBase () inline
Definition at line 35 of file AREnvelopeFollowerBase.h.
References _highCutFilter, _lowCutFilter, WECore::TPTSVF::Parameters::FILTER_MODE, WECore::AREnv::Parameters::HIGH_CUT(), WECore::AREnv::Parameters::LOW_CUT(), WECore::ModulationSource< double >::reset(), WECore::TPTSVF::TPTSVFilter< T >::setCutoff(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), and setSampleRate().
~AREnvelopeFollowerBase()
virtual WECore::AREnv::AREnvelopeFollowerBase::~AREnvelopeFollowerBase () override virtual default
Member Function Documentation
_calcCoef()
double WECore::AREnv::AREnvelopeFollowerBase::_calcCoef (double timeMs) inline protected
Definition at line 161 of file AREnvelopeFollowerBase.h.
References _sampleRate.
Referenced by setAttackTimeMs(), setReleaseTimeMs(), and setSampleRate().
_envGetNextOutputImpl()
virtual double WECore::AREnv::AREnvelopeFollowerBase::_envGetNextOutputImpl (double inSample) inline protected pure virtual
Implemented in WECore::AREnv::AREnvelopeFollowerFullWave, and WECore::AREnv::AREnvelopeFollowerSquareLaw.
Referenced by _getNextOutputImpl().
_getNextOutputImpl()
double WECore::AREnv::AREnvelopeFollowerBase::_getNextOutputImpl (double inSample) inline override protected virtual
Applies the filters if needed, then calls _envGetNextOutputImpl.
Implements WECore::ModulationSource< double >.
Definition at line 185 of file AREnvelopeFollowerBase.h.
References _envGetNextOutputImpl(), _filterEnabled, _highCutFilter, _lowCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::processBlock().
_resetImpl()
void WECore::AREnv::AREnvelopeFollowerBase::_resetImpl () inline override protected virtual
Must be overriden by the inheriting class to reset the internat state as required.
Implements WECore::ModulationSource< double >.
Definition at line 194 of file AREnvelopeFollowerBase.h.
References _envVal, _highCutFilter, _lowCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::reset().
getAttackTimeMs()
double WECore::AREnv::AREnvelopeFollowerBase::getAttackTimeMs () const inline
See also
setAttackTimeMs
Definition at line 114 of file AREnvelopeFollowerBase.h.
References _attackTimeMs.
Referenced by SCENARIO(), and SCENARIO().
getFilterEnabled()
bool WECore::AREnv::AREnvelopeFollowerBase::getFilterEnabled () const inline
See also
setFilterEnabled
Definition at line 124 of file AREnvelopeFollowerBase.h.
References _filterEnabled.
Referenced by SCENARIO().
getHighCutHz()
double WECore::AREnv::AREnvelopeFollowerBase::getHighCutHz () const inline
See also
setHighCutHz
Definition at line 134 of file AREnvelopeFollowerBase.h.
References _highCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::getCutoff().
Referenced by SCENARIO(), and SCENARIO().
getLowCutHz()
double WECore::AREnv::AREnvelopeFollowerBase::getLowCutHz () const inline
See also
setLowCutHz
Definition at line 129 of file AREnvelopeFollowerBase.h.
References _lowCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::getCutoff().
Referenced by SCENARIO(), and SCENARIO().
getReleaseTimeMs()
double WECore::AREnv::AREnvelopeFollowerBase::getReleaseTimeMs () const inline
See also
setReleaseTimeMs
Definition at line 119 of file AREnvelopeFollowerBase.h.
References _releaseTimeMs.
Referenced by SCENARIO(), and SCENARIO().
setAttackTimeMs()
void WECore::AREnv::AREnvelopeFollowerBase::setAttackTimeMs (double time) inline
Sets the attack time of the envelope.
See also
ATTACK_MS for valid values
Parameters
[in] time Attack time in milliseconds
Definition at line 175 of file AREnvelopeFollowerBase.h.
References _attackCoef, _attackTimeMs, _calcCoef(), and WECore::AREnv::Parameters::ATTACK_MS().
Referenced by SCENARIO(), and SCENARIO().
setFilterEnabled()
void WECore::AREnv::AREnvelopeFollowerBase::setFilterEnabled (bool isEnabled) inline
Sets enables or disables the filter in front of the envelope.
See also
FILTER_ENABLED for valid values
Parameters
[in] isEnabled Set to true to enabled the filter.
Definition at line 87 of file AREnvelopeFollowerBase.h.
References _filterEnabled.
Referenced by SCENARIO().
setHighCutHz()
void WECore::AREnv::AREnvelopeFollowerBase::setHighCutHz (double freq) inline
Sets the high cut applied before the envelope.
See also
HIGH_CUT for valid values
Parameters
[in] freq Cutoff frequency in Hz
Definition at line 105 of file AREnvelopeFollowerBase.h.
References _highCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::setCutoff().
Referenced by SCENARIO(), and SCENARIO().
setLowCutHz()
void WECore::AREnv::AREnvelopeFollowerBase::setLowCutHz (double freq) inline
Sets the low cut applied before the envelope.
See also
LOW_CUT for valid values
Parameters
[in] freq Cutoff frequency in Hz
Definition at line 96 of file AREnvelopeFollowerBase.h.
References _lowCutFilter, and WECore::TPTSVF::TPTSVFilter< T >::setCutoff().
Referenced by SCENARIO(), and SCENARIO().
setReleaseTimeMs()
void WECore::AREnv::AREnvelopeFollowerBase::setReleaseTimeMs (double time) inline
Sets the release time of the envelope.
See also
RELEASE_MS for valid values
Parameters
[in] time Release time in milliseconds
Definition at line 180 of file AREnvelopeFollowerBase.h.
References _calcCoef(), _releaseCoef, _releaseTimeMs, and WECore::AREnv::Parameters::RELEASE_MS().
Referenced by SCENARIO(), and SCENARIO().
setSampleRate()
void WECore::AREnv::AREnvelopeFollowerBase::setSampleRate (double sampleRate) inline
Sets the sample rate the envelope will operate at. It is recommended that you call this at some point before calling clockUpdateEnvelope.
Parameters
[in] sampleRate The sample rate in Hz
Definition at line 166 of file AREnvelopeFollowerBase.h.
References _attackCoef, _attackTimeMs, _calcCoef(), _highCutFilter, _lowCutFilter, _releaseCoef, _releaseTimeMs, _sampleRate, and WECore::TPTSVF::TPTSVFilter< T >::setSampleRate().
Referenced by AREnvelopeFollowerBase().
Member Data Documentation
_attackCoef
double WECore::AREnv::AREnvelopeFollowerBase::_attackCoef protected
Definition at line 143 of file AREnvelopeFollowerBase.h.
Referenced by WECore::AREnv::AREnvelopeFollowerFullWave::_envGetNextOutputImpl(), WECore::AREnv::AREnvelopeFollowerSquareLaw::_envGetNextOutputImpl(), setAttackTimeMs(), and setSampleRate().
_attackTimeMs
double WECore::AREnv::AREnvelopeFollowerBase::_attackTimeMs protected
Definition at line 140 of file AREnvelopeFollowerBase.h.
Referenced by getAttackTimeMs(), setAttackTimeMs(), and setSampleRate().
_envVal
double WECore::AREnv::AREnvelopeFollowerBase::_envVal protected
Definition at line 138 of file AREnvelopeFollowerBase.h.
Referenced by WECore::AREnv::AREnvelopeFollowerFullWave::_envGetNextOutputImpl(), WECore::AREnv::AREnvelopeFollowerSquareLaw::_envGetNextOutputImpl(), and _resetImpl().
_filterEnabled
bool WECore::AREnv::AREnvelopeFollowerBase::_filterEnabled protected
Definition at line 146 of file AREnvelopeFollowerBase.h.
Referenced by _getNextOutputImpl(), getFilterEnabled(), and setFilterEnabled().
_highCutFilter
TPTSVF::TPTSVFilter<double> WECore::AREnv::AREnvelopeFollowerBase::_highCutFilter protected
Definition at line 148 of file AREnvelopeFollowerBase.h.
Referenced by _getNextOutputImpl(), _resetImpl(), AREnvelopeFollowerBase(), getHighCutHz(), setHighCutHz(), and setSampleRate().
_lowCutFilter
TPTSVF::TPTSVFilter<double> WECore::AREnv::AREnvelopeFollowerBase::_lowCutFilter protected
Definition at line 147 of file AREnvelopeFollowerBase.h.
Referenced by _getNextOutputImpl(), _resetImpl(), AREnvelopeFollowerBase(), getLowCutHz(), setLowCutHz(), and setSampleRate().
_releaseCoef
double WECore::AREnv::AREnvelopeFollowerBase::_releaseCoef protected
Definition at line 144 of file AREnvelopeFollowerBase.h.
Referenced by WECore::AREnv::AREnvelopeFollowerFullWave::_envGetNextOutputImpl(), WECore::AREnv::AREnvelopeFollowerSquareLaw::_envGetNextOutputImpl(), setReleaseTimeMs(), and setSampleRate().
_releaseTimeMs
double WECore::AREnv::AREnvelopeFollowerBase::_releaseTimeMs protected
Definition at line 141 of file AREnvelopeFollowerBase.h.
Referenced by getReleaseTimeMs(), setReleaseTimeMs(), and setSampleRate().
_sampleRate
double WECore::AREnv::AREnvelopeFollowerBase::_sampleRate protected
Definition at line 150 of file AREnvelopeFollowerBase.h.
Referenced by _calcCoef(), and setSampleRate().
The documentation for this class was generated from the following file:
AREnvelopeFollowerBase.h