WE Core: WECore::Carve::CarveDSPUnit< T > Class Template Reference
WECore::Carve::CarveDSPUnit< T > Class Template Reference
#include <CarveDSPUnit.h>
Public Member Functions
CarveDSPUnit ()
virtual ~CarveDSPUnit ()
T process (T inSample) const
Setter Methods
void setMode (int val)
void setPreGain (double val)
void setPostGain (double val)
void setTweak (double val)
Getter Methods
int getMode ()
double getPreGain ()
double getPostGain ()
double getTweak ()
Private Member Functions
T _processSine (T inSample) const
T _processParabolicSoft (T inSample) const
T _processParabolicHard (T inSample) const
T _processAsymmetricSine (T inSample) const
T _processExponent (T inSample) const
T _processClipper (T inSample) const
Private Attributes
double _preGain
double _postGain
double _tweak
int _mode
Detailed Description
template<typename T>
class WECore::Carve::CarveDSPUnit< T >
Definition at line 58 of file CarveDSPUnit.h.
Constructor & Destructor Documentation
CarveDSPUnit()
template<typename T > WECore::Carve::CarveDSPUnit< T >::CarveDSPUnit () inline
Sets all parameters to their default values.
Definition at line 66 of file CarveDSPUnit.h.
~CarveDSPUnit()
template<typename T > virtual WECore::Carve::CarveDSPUnit< T >::~CarveDSPUnit () inline virtual
Definition at line 71 of file CarveDSPUnit.h.
Member Function Documentation
_processAsymmetricSine()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processAsymmetricSine (T inSample) const private
Definition at line 230 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_PI.
_processClipper()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processClipper (T inSample) const private
Definition at line 247 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_PI.
_processExponent()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processExponent (T inSample) const private
Definition at line 239 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_E.
_processParabolicHard()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processParabolicHard (T inSample) const private
Definition at line 221 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_PI.
_processParabolicSoft()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processParabolicSoft (T inSample) const private
Definition at line 212 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_PI.
_processSine()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::_processSine (T inSample) const private
Definition at line 203 of file CarveDSPUnit.h.
References WECore::CoreMath::DOUBLE_PI.
getMode()
template<typename T > int WECore::Carve::CarveDSPUnit< T >::getMode () inline
See also
setMode
Definition at line 124 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_mode.
Referenced by SCENARIO().
getPostGain()
template<typename T > double WECore::Carve::CarveDSPUnit< T >::getPostGain () inline
See also
setPostGain
Definition at line 134 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_postGain.
Referenced by SCENARIO().
getPreGain()
template<typename T > double WECore::Carve::CarveDSPUnit< T >::getPreGain () inline
See also
setPreGain
Definition at line 129 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_preGain.
Referenced by SCENARIO().
getTweak()
template<typename T > double WECore::Carve::CarveDSPUnit< T >::getTweak () inline
See also
setTweak
Definition at line 139 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_tweak.
Referenced by SCENARIO().
process()
template<typename T > T WECore::Carve::CarveDSPUnit< T >::process (T inSample) const
Performs the processing on the sample, by calling the appropriate private processing methods.
Parameters
[in] inSample The sample to be processed
Returns
The value of inSample after processing
Definition at line 174 of file CarveDSPUnit.h.
References WECore::Carve::Parameters::ModeParameter::ASYMMETRIC_SINE, WECore::Carve::Parameters::ModeParameter::CLIPPER, WECore::Carve::Parameters::ModeParameter::EXPONENT, WECore::Carve::Parameters::ModeParameter::OFF, WECore::Carve::Parameters::ModeParameter::PARABOLIC_HARD, WECore::Carve::Parameters::ModeParameter::PARABOLIC_SOFT, and WECore::Carve::Parameters::ModeParameter::SINE.
Referenced by SCENARIO().
setMode()
template<typename T > void WECore::Carve::CarveDSPUnit< T >::setMode (int val) inline
Sets the wave shape which will be applied to the signal.
Parameters
[in] val Value the mode should be set to
See also
ModeParameter for valid values
Definition at line 83 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_mode, ParameterDefinition::BaseParameter< T >::BoundsCheck(), and WECore::Carve::Parameters::MODE.
Referenced by SCENARIO().
setPostGain()
template<typename T > void WECore::Carve::CarveDSPUnit< T >::setPostGain (double val) inline
Sets the gain to be applied to the signal after processing. More post-gain = more volume.
Parameters
[in] val Post-gain value that should be used
See also
POSTGAIN for valid values
Definition at line 103 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_postGain, and WECore::Carve::Parameters::POSTGAIN().
Referenced by SCENARIO().
setPreGain()
template<typename T > void WECore::Carve::CarveDSPUnit< T >::setPreGain (double val) inline
Sets the gain to be applied to the signal before processing. More pre-gain = more distortion.
Parameters
[in] val Pre-gain value that should be used
See also
PREGAIN for valid values
Definition at line 93 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_preGain, and WECore::Carve::Parameters::PREGAIN().
Referenced by SCENARIO().
setTweak()
template<typename T > void WECore::Carve::CarveDSPUnit< T >::setTweak (double val) inline
Sets the tweak value to be applied to the signal during processing. This behaves differently for each mode, and modifies the shape of the wave applied to the signal
Parameters
[in] val Tweak value that should be used
See also
TWEAK for valid values
Definition at line 114 of file CarveDSPUnit.h.
References WECore::Carve::CarveDSPUnit< T >::_tweak, and WECore::Carve::Parameters::TWEAK().
Referenced by SCENARIO().
Member Data Documentation
_mode
template<typename T > int WECore::Carve::CarveDSPUnit< T >::_mode private
Definition at line 158 of file CarveDSPUnit.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::getMode(), and WECore::Carve::CarveDSPUnit< T >::setMode().
_postGain
template<typename T > double WECore::Carve::CarveDSPUnit< T >::_postGain private
Definition at line 155 of file CarveDSPUnit.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::getPostGain(), and WECore::Carve::CarveDSPUnit< T >::setPostGain().
_preGain
template<typename T > double WECore::Carve::CarveDSPUnit< T >::_preGain private
Definition at line 154 of file CarveDSPUnit.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::getPreGain(), and WECore::Carve::CarveDSPUnit< T >::setPreGain().
_tweak
template<typename T > double WECore::Carve::CarveDSPUnit< T >::_tweak private
Definition at line 156 of file CarveDSPUnit.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::getTweak(), and WECore::Carve::CarveDSPUnit< T >::setTweak().
The documentation for this class was generated from the following file:
CarveDSPUnit.h