WE Core: WECore::Richter::RichterLFOPair Class Reference
WECore::Richter::RichterLFOPair Class Reference
#include <RichterLFOPair.h>
Public Member Functions
RichterLFOPair ()
virtual ~RichterLFOPair ()=default
RichterLFOPair operator= (RichterLFOPair &other)=delete
RichterLFOPair (RichterLFOPair &other)=delete
void reset ()
void prepareForNextBuffer (double bpm, double timeInSeconds, double sampleRate)
double calcGainInLoop ()
double getGain ()
double getMod ()
Public Attributes
RichterLFO LFO
RichterMOD MOD
Private Attributes
double _lfoGain
double _modGain
Detailed Description
A convenience class that allows a simple implementation of an LFO that has been paired with a MOD oscillator to modulate its depth and frequency. If you use this class, you will never need to interact directly with either of the contained LFOs for anything other than getting or setting parameter values.
This class has been created as the LFO relies on the MOD being ready before it can perform certain operations, which means there are method calls to each oscillator which must be interleaved carefully.
The following example shows how to set up this object for audio at 120bpm and 44.1kHz:
RichterLFOPair lfoPair;
lfoPair.prepareForNextBuffer(120, 0, 44100);
Then the class can be used to process a buffer as follows: (where numSamples is the size of the buffer)
for (size_t iii {0}; iii < numSamples; iii++) {
    buffer[iii] = buffer[iii] * lfoPair.calcGainInLoop();
}
calcGainInLoop must be called once for each sample. Even if there is a sample in the buffer which you do not wish to apply processing to,calcGainInLoop must still be called otherwise subsequent samples will have the wrong gain calculation applied.
Definition at line 60 of file RichterLFOPair.h.
Constructor & Destructor Documentation
RichterLFOPair() [1/2]
WECore::Richter::RichterLFOPair::RichterLFOPair () inline
Definition at line 62 of file RichterLFOPair.h.
~RichterLFOPair()
virtual WECore::Richter::RichterLFOPair::~RichterLFOPair () virtual default
RichterLFOPair() [2/2]
WECore::Richter::RichterLFOPair::RichterLFOPair (RichterLFOPair & other) delete
Member Function Documentation
calcGainInLoop()
double WECore::Richter::RichterLFOPair::calcGainInLoop () inline
Use this in your processing loop. Returns a gain value which is intended to be multiplied with a single sample to apply the tremolo effect.
Note: Calling this method will advance the oscillators internal counters by one sample. Calling this method will return a different value each time.
Returns
The value of the RichterLFO's output at this moment, a value between 0 and 1.
Definition at line 140 of file RichterLFOPair.h.
References WECore::Richter::RichterMOD::_calcGain(), WECore::Richter::RichterLFO::_calcGain(), _lfoGain, _modGain, WECore::Richter::RichterLFOBase::calcIndexAndScaleInLoop(), WECore::Richter::RichterLFOBase::getBypassSwitch(), LFO, and MOD.
getGain()
double WECore::Richter::RichterLFOPair::getGain () inline
Returns the most recent gain value without advancing the LFOs.
Definition at line 100 of file RichterLFOPair.h.
References _lfoGain.
getMod()
double WECore::Richter::RichterLFOPair::getMod () inline
Returns the most recent mod value without advancing the LFOs.
Definition at line 105 of file RichterLFOPair.h.
References _modGain.
operator=()
RichterLFOPair WECore::Richter::RichterLFOPair::operator= (RichterLFOPair & other) delete
prepareForNextBuffer()
void WECore::Richter::RichterLFOPair::prepareForNextBuffer (double bpm, double timeInSeconds, double sampleRate) inline
Prepares for processing the next buffer of samples. For example if using JUCE, you would call this in your processBlock() method before doing any processing.
This calls various protected methods of each of the oscillators in a specific order to ensure calculations are done correctly.
Parameters
bpm Current bpm of the host.
timeInSeconds Position of the host DAW's playhead at the start of playback.
sampleRate Current sample rate of the host
Definition at line 120 of file RichterLFOPair.h.
References WECore::Richter::RichterLFOBase::_calcFreq(), WECore::Richter::RichterLFOBase::_calcNextScale(), WECore::Richter::RichterLFOBase::_calcPhaseOffset(), WECore::Richter::RichterLFOBase::_calcSamplesPerTremoloCycle(), LFO, MOD, and WECore::Richter::RichterLFOBase::setWaveTablePointers().
reset()
void WECore::Richter::RichterLFOPair::reset () inline
Call each oscillator's reset method.
Definition at line 115 of file RichterLFOPair.h.
References LFO, MOD, and WECore::Richter::RichterLFOBase::reset().
Member Data Documentation
_lfoGain
double WECore::Richter::RichterLFOPair::_lfoGain private
Definition at line 111 of file RichterLFOPair.h.
Referenced by calcGainInLoop(), and getGain().
_modGain
double WECore::Richter::RichterLFOPair::_modGain private
Definition at line 112 of file RichterLFOPair.h.
Referenced by calcGainInLoop(), and getMod().
LFO
RichterLFO WECore::Richter::RichterLFOPair::LFO
Definition at line 107 of file RichterLFOPair.h.
Referenced by calcGainInLoop(), prepareForNextBuffer(), reset(), and SCENARIO().
MOD
RichterMOD WECore::Richter::RichterLFOPair::MOD
Definition at line 108 of file RichterLFOPair.h.
Referenced by calcGainInLoop(), prepareForNextBuffer(), reset(), and SCENARIO().
The documentation for this class was generated from the following file:
RichterLFOPair.h