WE Core: WECore::JUCEPlugin::CoreLookAndFeel Class Reference
WECore::JUCEPlugin::CoreLookAndFeel Class Reference
#include <CoreLookAndFeel.h>
Public Member Functions
CoreLookAndFeel ()
virtual ~CoreLookAndFeel ()=default
CoreLookAndFeel operator= (CoreLookAndFeel &)=delete
CoreLookAndFeel (CoreLookAndFeel &)=delete
virtual void drawLinearSliderThumb (juce::Graphics &g, int x, int y, int width, int height, float sliderPos, float, float, const juce::Slider::SliderStyle style, juce::Slider &slider) override
virtual void drawButtonBackground (juce::Graphics &g, juce::Button &button, const juce::Colour &, bool, bool) override
virtual void drawButtonText (juce::Graphics &g, juce::TextButton &textButton, bool, bool) override
virtual void drawComboBox (juce::Graphics &g, int, int, const bool, int buttonX, int buttonY, int buttonW, int buttonH, juce::ComboBox &box) override
virtual void drawLinearSlider (juce::Graphics &g, int x, int y, int width, int height, float sliderPos, float minSliderPos, float maxSliderPos, const juce::Slider::SliderStyle style, juce::Slider &slider) override
virtual void drawLinearSliderBackground (juce::Graphics &g, int x, int y, int width, int height, float, float, float, const juce::Slider::SliderStyle, juce::Slider &slider) override
virtual void drawTooltip (juce::Graphics &g, const juce::String &text, int width, int height) override
virtual void setHighlightColour (juce::Colour newColour)
virtual void setLightColour (juce::Colour newColour)
virtual void setDarkColour (juce::Colour newColour)
Protected Attributes
juce::Colour lightColour
juce::Colour darkColour
juce::Colour highlightColour
Detailed Description
A class which contains most of the basic design elements which the white elephant audio plugins have in common.
Not all drawing methods are defined, and so methods inherited from LookAndFeel_V2 may be used.
By default the three colours which are used are dark grey, light grey, and neon blue. These can be changed using the provided setter methods.
The colour members (highlightColour, etc) are being phased out as it doesn't fit well with how colours are managed in JUCE.
Definition at line 44 of file CoreLookAndFeel.h.
Constructor & Destructor Documentation
CoreLookAndFeel() [1/2]
WECore::JUCEPlugin::CoreLookAndFeel::CoreLookAndFeel () inline
Definition at line 46 of file CoreLookAndFeel.h.
References setDarkColour(), setHighlightColour(), and setLightColour().
~CoreLookAndFeel()
virtual WECore::JUCEPlugin::CoreLookAndFeel::~CoreLookAndFeel () virtual default
CoreLookAndFeel() [2/2]
WECore::JUCEPlugin::CoreLookAndFeel::CoreLookAndFeel (CoreLookAndFeel &) delete
Member Function Documentation
drawButtonBackground()
void WECore::JUCEPlugin::CoreLookAndFeel::drawButtonBackground (juce::Graphics & g, juce::Button & button, const juce::Colour & , bool , bool) inline override virtual
Definition at line 200 of file CoreLookAndFeel.h.
References darkColour, highlightColour, and lightColour.
drawButtonText()
void WECore::JUCEPlugin::CoreLookAndFeel::drawButtonText (juce::Graphics & g, juce::TextButton & textButton, bool , bool) inline override virtual
Definition at line 236 of file CoreLookAndFeel.h.
References darkColour, highlightColour, and lightColour.
drawComboBox()
void WECore::JUCEPlugin::CoreLookAndFeel::drawComboBox (juce::Graphics & g, int , int , const bool , int buttonX, int buttonY, int buttonW, int buttonH, juce::ComboBox & box) inline override virtual
Definition at line 264 of file CoreLookAndFeel.h.
References darkColour, highlightColour, and lightColour.
drawLinearSlider()
void WECore::JUCEPlugin::CoreLookAndFeel::drawLinearSlider (juce::Graphics & g, int x, int y, int width, int height, float sliderPos, float minSliderPos, float maxSliderPos, const juce::Slider::SliderStyle style, juce::Slider & slider) inline override virtual
Definition at line 297 of file CoreLookAndFeel.h.
References drawLinearSliderBackground(), and drawLinearSliderThumb().
drawLinearSliderBackground()
void WECore::JUCEPlugin::CoreLookAndFeel::drawLinearSliderBackground (juce::Graphics & g, int x, int y, int width, int height, float , float , float , const juce::Slider::SliderStyle , juce::Slider & slider) inline override virtual
Definition at line 312 of file CoreLookAndFeel.h.
References lightColour.
Referenced by drawLinearSlider().
drawLinearSliderThumb()
void WECore::JUCEPlugin::CoreLookAndFeel::drawLinearSliderThumb (juce::Graphics & g, int x, int y, int width, int height, float sliderPos, float , float , const juce::Slider::SliderStyle style, juce::Slider & slider) inline override virtual
Definition at line 152 of file CoreLookAndFeel.h.
References darkColour, highlightColour, and lightColour.
Referenced by drawLinearSlider().
drawTooltip()
void WECore::JUCEPlugin::CoreLookAndFeel::drawTooltip (juce::Graphics & g, const juce::String & text, int width, int height) inline override virtual
Definition at line 329 of file CoreLookAndFeel.h.
References darkColour, and lightColour.
operator=()
CoreLookAndFeel WECore::JUCEPlugin::CoreLookAndFeel::operator= (CoreLookAndFeel &) delete
setDarkColour()
virtual void WECore::JUCEPlugin::CoreLookAndFeel::setDarkColour (juce::Colour newColour) inline virtual
Definition at line 138 of file CoreLookAndFeel.h.
References darkColour.
Referenced by CoreLookAndFeel().
setHighlightColour()
virtual void WECore::JUCEPlugin::CoreLookAndFeel::setHighlightColour (juce::Colour newColour) inline virtual
Definition at line 116 of file CoreLookAndFeel.h.
References highlightColour.
Referenced by CoreLookAndFeel().
setLightColour()
virtual void WECore::JUCEPlugin::CoreLookAndFeel::setLightColour (juce::Colour newColour) inline virtual
Definition at line 128 of file CoreLookAndFeel.h.
References lightColour.
Referenced by CoreLookAndFeel().
Member Data Documentation
darkColour
juce::Colour WECore::JUCEPlugin::CoreLookAndFeel::darkColour protected
Definition at line 148 of file CoreLookAndFeel.h.
Referenced by drawButtonBackground(), drawButtonText(), drawComboBox(), drawLinearSliderThumb(), drawTooltip(), and setDarkColour().
highlightColour
juce::Colour WECore::JUCEPlugin::CoreLookAndFeel::highlightColour protected
Definition at line 149 of file CoreLookAndFeel.h.
Referenced by drawButtonBackground(), drawButtonText(), drawComboBox(), drawLinearSliderThumb(), and setHighlightColour().
lightColour
juce::Colour WECore::JUCEPlugin::CoreLookAndFeel::lightColour protected
Definition at line 147 of file CoreLookAndFeel.h.
Referenced by drawButtonBackground(), drawButtonText(), drawComboBox(), drawLinearSliderBackground(), drawLinearSliderThumb(), drawTooltip(), and setLightColour().
The documentation for this class was generated from the following file:
CoreLookAndFeel.h