WE Core: WECore::JUCEPlugin::SliderLabelUpdater Class Reference
WECore::JUCEPlugin::SliderLabelUpdater Class Reference abstract
#include <LabelReadoutSlider.h>
Public Member Functions
SliderLabelUpdater (const juce::String &componentName)
virtual ~SliderLabelUpdater ()=default
Mouse event handlers
virtual void mouseEnter (const juce::MouseEvent &event) override
virtual void mouseMove (const juce::MouseEvent &event) override
virtual void mouseExit (const juce::MouseEvent &event) override
virtual void mouseDoubleClick (const juce::MouseEvent &event) override
virtual void mouseDrag (const juce::MouseEvent &event) override
virtual void mouseWheelMove (const juce::MouseEvent &event, const juce::MouseWheelDetails &wheel) override
Private Member Functions
virtual void _updateLabel (const juce::MouseEvent &event)=0
virtual void _resetLabel ()=0
Detailed Description
Handles mouse events that may indicate that the Slider value has changed.
Definition at line 35 of file LabelReadoutSlider.h.
Constructor & Destructor Documentation
SliderLabelUpdater()
WECore::JUCEPlugin::SliderLabelUpdater::SliderLabelUpdater (const juce::String & componentName) inline explicit
Definition at line 37 of file LabelReadoutSlider.h.
~SliderLabelUpdater()
virtual WECore::JUCEPlugin::SliderLabelUpdater::~SliderLabelUpdater () virtual default
Member Function Documentation
_resetLabel()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::_resetLabel () private pure virtual
Called when the mouse is no longer over the Slider, so the Label(s) can be reset.
Implemented in WECore::JUCEPlugin::LabelReadoutSlider< T >.
Referenced by mouseExit().
_updateLabel()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::_updateLabel (const juce::MouseEvent & event) private pure virtual
Called when the Slider value may have changed and the Label(s) should be updated.
Implemented in WECore::JUCEPlugin::LabelReadoutSlider< T >.
Referenced by mouseDoubleClick(), mouseDrag(), mouseEnter(), mouseMove(), and mouseWheelMove().
mouseDoubleClick()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseDoubleClick (const juce::MouseEvent & event) inline override virtual
Definition at line 57 of file LabelReadoutSlider.h.
References _updateLabel().
mouseDrag()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseDrag (const juce::MouseEvent & event) inline override virtual
Definition at line 62 of file LabelReadoutSlider.h.
References _updateLabel().
mouseEnter()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseEnter (const juce::MouseEvent & event) inline override virtual
Definition at line 42 of file LabelReadoutSlider.h.
References _updateLabel().
mouseExit()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseExit (const juce::MouseEvent & event) inline override virtual
Definition at line 52 of file LabelReadoutSlider.h.
References _resetLabel().
mouseMove()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseMove (const juce::MouseEvent & event) inline override virtual
Definition at line 47 of file LabelReadoutSlider.h.
References _updateLabel().
mouseWheelMove()
virtual void WECore::JUCEPlugin::SliderLabelUpdater::mouseWheelMove (const juce::MouseEvent & event, const juce::MouseWheelDetails & wheel) inline override virtual
Definition at line 67 of file LabelReadoutSlider.h.
References _updateLabel().
The documentation for this class was generated from the following file:
LabelReadoutSlider.h