WE Core: WECore::Richter::RichterLFO Class Reference
WECore::Richter::RichterLFO Class Reference
#include <RichterLFO.h>
Public Member Functions
RichterLFO ()
virtual ~RichterLFO () override=default
bool addFreqModulationSource (std::shared_ptr< ModulationSource > source)
bool removeFreqModulationSource (std::shared_ptr< ModulationSource > source)
bool setFreqModulationAmount (size_t index, double amount)
std::vector< ModulationSourceWrapper< double > > getFreqModulationSources () const
bool addDepthModulationSource (std::shared_ptr< ModulationSource > source)
bool removeDepthModulationSource (std::shared_ptr< ModulationSource > source)
bool setDepthModulationAmount (size_t index, double amount)
std::vector< ModulationSourceWrapper< double > > getDepthModulationSources () const
bool addPhaseModulationSource (std::shared_ptr< ModulationSource > source)
bool removePhaseModulationSource (std::shared_ptr< ModulationSource > source)
bool setPhaseModulationAmount (size_t index, double amount)
std::vector< ModulationSourceWrapper< double > > getPhaseModulationSources () const
void prepareForNextBuffer (double bpm, double timeInSeconds)
RichterLFO operator= (RichterLFO &other)=delete
RichterLFO (RichterLFO &)=delete
Getter Methods
bool getBypassSwitch () const
bool getPhaseSyncSwitch () const
bool getTempoSyncSwitch () const
bool getInvertSwitch () const
int getWave () const
double getTempoNumer () const
double getTempoDenom () const
double getFreq ()
double getModulatedFreqValue () const
double getDepth ()
double getModulatedDepthValue () const
double getManualPhase () const
double getModulatedPhaseValue () const
Setter Methods
void setBypassSwitch (bool val)
void setPhaseSyncSwitch (bool val)
void setTempoSyncSwitch (bool val)
void setInvertSwitch (bool val)
void setWave (int val)
void setTempoNumer (int val)
void setTempoDenom (int val)
void setFreq (double val)
void setDepth (double val)
void setManualPhase (double val)
void setSampleRate (double val)
Public Member Functions inherited from WECore::ModulationSource< double >
ModulationSource ()
virtual ~ModulationSource ()=default
double getNextOutput (double inSample)
virtual double getLastOutput () const
void reset ()
Protected Member Functions
void _calcPhaseOffset (double timeInSeconds)
double _calcFreq (double modAmount)
double _calcLFOValue (double freq, double phaseModValue)
double _getNextOutputImpl (double inSample) override
virtual void _resetImpl () override
double _calcModValue (const std::vector< ModulationSourceWrapper< double > > &sources) const
Protected Attributes
int _wave
int _indexOffset
bool _bypassSwitch
bool _tempoSyncSwitch
bool _phaseSyncSwitch
bool _invertSwitch
bool _needsSeekOffsetCalc
double _tempoNumer
double _tempoDenom
double _rawFreq
double _modulatedFreqValue
double _rawDepth
double _modulatedDepthValue
double _manualPhase
double _modulatedPhaseValue
double _sampleRate
double _bpm
double _wavetablePosition
const double * _waveArrayPointer
std::vector< ModulationSourceWrapper< double > > _freqModulationSources
std::vector< ModulationSourceWrapper< double > > _depthModulationSources
std::vector< ModulationSourceWrapper< double > > _phaseModulationSources
Protected Attributes inherited from WECore::ModulationSource< double >
double _cachedOutput
Friends
class RichterLFOPair
Detailed Description
Provides and LFO with: depth, rate, tempo sync, phase, wave shape, and phase sync controls, plus additional functionality to allow the depth and rate controls to be modulated by an external source, with internal controls of the for the depth of this modulation.
This LFO oscillates between -1 and 1.
To use, you simply need to call reset, prepareForNextBuffer, and getNextOutput as necessary (see their descriptions for details), and use the provided getter and setter methods to manipulate parameters.
Definition at line 44 of file RichterLFO.h.
Constructor & Destructor Documentation
RichterLFO() [1/2]
WECore::Richter::RichterLFO::RichterLFO () inline
Generates the wave tables on initialsation, while running gain values are simply looked up from these wave tables.
Also initialises parameters (that are not part of RichterLFOBase) to default values.
Definition at line 202 of file RichterLFO.h.
~RichterLFO()
virtual WECore::Richter::RichterLFO::~RichterLFO () override virtual default
RichterLFO() [2/2]
WECore::Richter::RichterLFO::RichterLFO (RichterLFO &) delete
Member Function Documentation
_calcFreq()
double WECore::Richter::RichterLFO::_calcFreq (double modAmount) inline protected
Calculates the frequency of the oscillator. Will use either the frequency or tempoNumer/tempoDenom depending on whether tempo sync is enabled.
Parameters
modAmount The gain output from the modulation oscillator.
Definition at line 366 of file RichterLFO.h.
References _bpm, _modulatedFreqValue, _rawFreq, _tempoDenom, _tempoNumer, _tempoSyncSwitch, and WECore::Richter::Parameters::FREQ().
Referenced by _calcPhaseOffset(), and _getNextOutputImpl().
_calcLFOValue()
double WECore::Richter::RichterLFO::_calcLFOValue (double freq, double phaseModValue) inline protected
Calculates the current index of the oscillator in its wavetable and increments the number of samples processed.
Parameters
freq The absolute frequency of the LFO, including tempo sync or modulation.
Returns
The value in the wavetable at the current index.
Definition at line 382 of file RichterLFO.h.
References _indexOffset, _manualPhase, _modulatedPhaseValue, _sampleRate, _waveArrayPointer, _wavetablePosition, WECore::Richter::Parameters::PHASE(), and WECore::Richter::Wavetables::SIZE.
Referenced by _getNextOutputImpl().
_calcModValue()
double WECore::Richter::RichterLFO::_calcModValue (const std::vector< ModulationSourceWrapper< double > > & sources) const inline protected
Definition at line 191 of file RichterLFO.h.
Referenced by _getNextOutputImpl().
_calcPhaseOffset()
void WECore::Richter::RichterLFO::_calcPhaseOffset (double timeInSeconds) inline protected
Calculates the phase offset to be applied to the oscillator, including any offset required by the phase sync and any offset applied by the user.
Parameters
timeInSeconds Position of the host DAW's playhead at the start of playback.
Definition at line 345 of file RichterLFO.h.
References _calcFreq(), _indexOffset, _needsSeekOffsetCalc, _phaseSyncSwitch, and WECore::Richter::Wavetables::SIZE.
Referenced by prepareForNextBuffer().
_getNextOutputImpl()
double WECore::Richter::RichterLFO::_getNextOutputImpl (double inSample) inline override protected virtual
Returns the next output of the LFO.
Note: Calling this method will advance the oscillators internal counters by one sample. Calling this method will return a different value each time.
Returns
The value of the LFO's output at this moment, a value between -1 and 1.
Implements WECore::ModulationSource< double >.
Definition at line 400 of file RichterLFO.h.
References _bypassSwitch, _calcFreq(), _calcLFOValue(), _calcModValue(), _depthModulationSources, _freqModulationSources, _invertSwitch, _modulatedDepthValue, _phaseModulationSources, _rawDepth, and WECore::Richter::Parameters::DEPTH().
_resetImpl()
void WECore::Richter::RichterLFO::_resetImpl () inline override protected virtual
Resets internal counters including indexOffset and currentScale.
Implements WECore::ModulationSource< double >.
Definition at line 339 of file RichterLFO.h.
References _indexOffset, _needsSeekOffsetCalc, and _wavetablePosition.
addDepthModulationSource()
bool WECore::Richter::RichterLFO::addDepthModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 269 of file RichterLFO.h.
References _depthModulationSources.
Referenced by WECore::Richter::RichterLFOPair::RichterLFOPair().
addFreqModulationSource()
bool WECore::Richter::RichterLFO::addFreqModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 237 of file RichterLFO.h.
References _freqModulationSources.
Referenced by WECore::Richter::RichterLFOPair::RichterLFOPair().
addPhaseModulationSource()
bool WECore::Richter::RichterLFO::addPhaseModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 301 of file RichterLFO.h.
References _phaseModulationSources.
getBypassSwitch()
bool WECore::Richter::RichterLFO::getBypassSwitch () const inline
Definition at line 62 of file RichterLFO.h.
References _bypassSwitch.
Referenced by WECore::Richter::RichterLFOPair::_getNextOutputImpl(), and SCENARIO().
getDepth()
double WECore::Richter::RichterLFO::getDepth () inline
Definition at line 71 of file RichterLFO.h.
References _rawDepth.
Referenced by WECore::Richter::RichterLFOPair::_getNextOutputImpl(), SCENARIO(), and SCENARIO().
getDepthModulationSources()
std::vector< ModulationSourceWrapper< double > > WECore::Richter::RichterLFO::getDepthModulationSources () const inline
Definition at line 100 of file RichterLFO.h.
References _depthModulationSources.
getFreq()
double WECore::Richter::RichterLFO::getFreq () inline
Definition at line 69 of file RichterLFO.h.
References _rawFreq.
Referenced by SCENARIO(), and SCENARIO().
getFreqModulationSources()
std::vector< ModulationSourceWrapper< double > > WECore::Richter::RichterLFO::getFreqModulationSources () const inline
Definition at line 95 of file RichterLFO.h.
References _freqModulationSources.
getInvertSwitch()
bool WECore::Richter::RichterLFO::getInvertSwitch () const inline
Definition at line 65 of file RichterLFO.h.
References _invertSwitch.
Referenced by SCENARIO().
getManualPhase()
double WECore::Richter::RichterLFO::getManualPhase () const inline
Definition at line 73 of file RichterLFO.h.
References _manualPhase.
Referenced by SCENARIO(), and SCENARIO().
getModulatedDepthValue()
double WECore::Richter::RichterLFO::getModulatedDepthValue () const inline
Definition at line 72 of file RichterLFO.h.
References _modulatedDepthValue.
getModulatedFreqValue()
double WECore::Richter::RichterLFO::getModulatedFreqValue () const inline
Definition at line 70 of file RichterLFO.h.
References _modulatedFreqValue.
getModulatedPhaseValue()
double WECore::Richter::RichterLFO::getModulatedPhaseValue () const inline
Definition at line 74 of file RichterLFO.h.
References _modulatedPhaseValue.
getPhaseModulationSources()
std::vector< ModulationSourceWrapper< double > > WECore::Richter::RichterLFO::getPhaseModulationSources () const inline
Definition at line 105 of file RichterLFO.h.
References _phaseModulationSources.
getPhaseSyncSwitch()
bool WECore::Richter::RichterLFO::getPhaseSyncSwitch () const inline
Definition at line 63 of file RichterLFO.h.
References _phaseSyncSwitch.
Referenced by SCENARIO().
getTempoDenom()
double WECore::Richter::RichterLFO::getTempoDenom () const inline
Definition at line 68 of file RichterLFO.h.
References _tempoDenom.
Referenced by SCENARIO(), and SCENARIO().
getTempoNumer()
double WECore::Richter::RichterLFO::getTempoNumer () const inline
Definition at line 67 of file RichterLFO.h.
References _tempoNumer.
Referenced by SCENARIO(), and SCENARIO().
getTempoSyncSwitch()
bool WECore::Richter::RichterLFO::getTempoSyncSwitch () const inline
Definition at line 64 of file RichterLFO.h.
References _tempoSyncSwitch.
Referenced by SCENARIO().
getWave()
int WECore::Richter::RichterLFO::getWave () const inline
Definition at line 66 of file RichterLFO.h.
References _wave.
Referenced by SCENARIO(), and SCENARIO().
operator=()
RichterLFO WECore::Richter::RichterLFO::operator= (RichterLFO & other) delete
prepareForNextBuffer()
void WECore::Richter::RichterLFO::prepareForNextBuffer (double bpm, double timeInSeconds) inline
Prepares for processing the next buffer of samples. For example if using JUCE, you would call this in your processBlock() method before doing any processing.
Parameters
bpm Current bpm of the host
timeInSeconds Position of the host DAW's playhead at the start of playback.
Definition at line 333 of file RichterLFO.h.
References _bpm, and _calcPhaseOffset().
Referenced by WECore::Richter::RichterLFOPair::prepareForNextBuffer().
removeDepthModulationSource()
bool WECore::Richter::RichterLFO::removeDepthModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 281 of file RichterLFO.h.
References _depthModulationSources.
removeFreqModulationSource()
bool WECore::Richter::RichterLFO::removeFreqModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 249 of file RichterLFO.h.
References _freqModulationSources.
removePhaseModulationSource()
bool WECore::Richter::RichterLFO::removePhaseModulationSource (std::shared_ptr< ModulationSource > source) inline
Definition at line 313 of file RichterLFO.h.
References _phaseModulationSources.
setBypassSwitch()
void WECore::Richter::RichterLFO::setBypassSwitch (bool val) inline
Definition at line 79 of file RichterLFO.h.
References _bypassSwitch.
Referenced by SCENARIO().
setDepth()
void WECore::Richter::RichterLFO::setDepth (double val) inline
Definition at line 87 of file RichterLFO.h.
References _rawDepth, and WECore::Richter::Parameters::DEPTH().
Referenced by SCENARIO(), and SCENARIO().
setDepthModulationAmount()
bool WECore::Richter::RichterLFO::setDepthModulationAmount (size_t index, double amount) inline
Definition at line 292 of file RichterLFO.h.
References _depthModulationSources.
setFreq()
void WECore::Richter::RichterLFO::setFreq (double val) inline
Definition at line 86 of file RichterLFO.h.
References _rawFreq, and WECore::Richter::Parameters::FREQ().
Referenced by SCENARIO(), and SCENARIO().
setFreqModulationAmount()
bool WECore::Richter::RichterLFO::setFreqModulationAmount (size_t index, double amount) inline
Definition at line 260 of file RichterLFO.h.
References _freqModulationSources.
setInvertSwitch()
void WECore::Richter::RichterLFO::setInvertSwitch (bool val) inline
Definition at line 82 of file RichterLFO.h.
References _invertSwitch.
Referenced by SCENARIO().
setManualPhase()
void WECore::Richter::RichterLFO::setManualPhase (double val) inline
Definition at line 88 of file RichterLFO.h.
References _manualPhase, and WECore::Richter::Parameters::PHASE().
Referenced by SCENARIO(), and SCENARIO().
setPhaseModulationAmount()
bool WECore::Richter::RichterLFO::setPhaseModulationAmount (size_t index, double amount) inline
Definition at line 324 of file RichterLFO.h.
References _phaseModulationSources.
setPhaseSyncSwitch()
void WECore::Richter::RichterLFO::setPhaseSyncSwitch (bool val) inline
Definition at line 80 of file RichterLFO.h.
References _phaseSyncSwitch.
Referenced by SCENARIO().
setSampleRate()
void WECore::Richter::RichterLFO::setSampleRate (double val) inline
Definition at line 89 of file RichterLFO.h.
References _sampleRate.
Referenced by WECore::Richter::RichterLFOPair::setSampleRate().
setTempoDenom()
void WECore::Richter::RichterLFO::setTempoDenom (int val) inline
Definition at line 85 of file RichterLFO.h.
References _tempoDenom, and WECore::Richter::Parameters::TEMPODENOM().
Referenced by SCENARIO(), and SCENARIO().
setTempoNumer()
void WECore::Richter::RichterLFO::setTempoNumer (int val) inline
Definition at line 84 of file RichterLFO.h.
References _tempoNumer, and WECore::Richter::Parameters::TEMPONUMER().
Referenced by SCENARIO(), and SCENARIO().
setTempoSyncSwitch()
void WECore::Richter::RichterLFO::setTempoSyncSwitch (bool val) inline
Definition at line 81 of file RichterLFO.h.
References _tempoSyncSwitch.
Referenced by SCENARIO().
setWave()
void WECore::Richter::RichterLFO::setWave (int val) inline
Definition at line 223 of file RichterLFO.h.
References _wave, _waveArrayPointer, ParameterDefinition::BaseParameter< T >::BoundsCheck(), WECore::Richter::Wavetables::getInstance(), WECore::Richter::Wavetables::getSaw(), WECore::Richter::Wavetables::getSidechain(), WECore::Richter::Wavetables::getSine(), WECore::Richter::Wavetables::getSquare(), and WECore::Richter::Parameters::WAVE.
Referenced by SCENARIO(), and SCENARIO().
Friends And Related Symbol Documentation
RichterLFOPair
friend class RichterLFOPair friend
Definition at line 58 of file RichterLFO.h.
Member Data Documentation
_bpm
double WECore::Richter::RichterLFO::_bpm protected
Definition at line 139 of file RichterLFO.h.
Referenced by _calcFreq(), and prepareForNextBuffer().
_bypassSwitch
bool WECore::Richter::RichterLFO::_bypassSwitch protected
Definition at line 124 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), getBypassSwitch(), and setBypassSwitch().
_depthModulationSources
std::vector<ModulationSourceWrapper<double> > WECore::Richter::RichterLFO::_depthModulationSources protected
Definition at line 145 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), addDepthModulationSource(), getDepthModulationSources(), removeDepthModulationSource(), and setDepthModulationAmount().
_freqModulationSources
std::vector<ModulationSourceWrapper<double> > WECore::Richter::RichterLFO::_freqModulationSources protected
Definition at line 144 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), addFreqModulationSource(), getFreqModulationSources(), removeFreqModulationSource(), and setFreqModulationAmount().
_indexOffset
int WECore::Richter::RichterLFO::_indexOffset protected
Definition at line 122 of file RichterLFO.h.
Referenced by _calcLFOValue(), _calcPhaseOffset(), and _resetImpl().
_invertSwitch
bool WECore::Richter::RichterLFO::_invertSwitch protected
Definition at line 127 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), getInvertSwitch(), and setInvertSwitch().
_manualPhase
double WECore::Richter::RichterLFO::_manualPhase protected
Definition at line 136 of file RichterLFO.h.
Referenced by _calcLFOValue(), getManualPhase(), and setManualPhase().
_modulatedDepthValue
double WECore::Richter::RichterLFO::_modulatedDepthValue protected
Definition at line 135 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), and getModulatedDepthValue().
_modulatedFreqValue
double WECore::Richter::RichterLFO::_modulatedFreqValue protected
Definition at line 133 of file RichterLFO.h.
Referenced by _calcFreq(), and getModulatedFreqValue().
_modulatedPhaseValue
double WECore::Richter::RichterLFO::_modulatedPhaseValue protected
Definition at line 137 of file RichterLFO.h.
Referenced by _calcLFOValue(), and getModulatedPhaseValue().
_needsSeekOffsetCalc
bool WECore::Richter::RichterLFO::_needsSeekOffsetCalc protected
Definition at line 128 of file RichterLFO.h.
Referenced by _calcPhaseOffset(), and _resetImpl().
_phaseModulationSources
std::vector<ModulationSourceWrapper<double> > WECore::Richter::RichterLFO::_phaseModulationSources protected
Definition at line 146 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), addPhaseModulationSource(), getPhaseModulationSources(), removePhaseModulationSource(), and setPhaseModulationAmount().
_phaseSyncSwitch
bool WECore::Richter::RichterLFO::_phaseSyncSwitch protected
Definition at line 126 of file RichterLFO.h.
Referenced by _calcPhaseOffset(), getPhaseSyncSwitch(), and setPhaseSyncSwitch().
_rawDepth
double WECore::Richter::RichterLFO::_rawDepth protected
Definition at line 134 of file RichterLFO.h.
Referenced by _getNextOutputImpl(), getDepth(), and setDepth().
_rawFreq
double WECore::Richter::RichterLFO::_rawFreq protected
Definition at line 132 of file RichterLFO.h.
Referenced by _calcFreq(), getFreq(), and setFreq().
_sampleRate
double WECore::Richter::RichterLFO::_sampleRate protected
Definition at line 138 of file RichterLFO.h.
Referenced by _calcLFOValue(), and setSampleRate().
_tempoDenom
double WECore::Richter::RichterLFO::_tempoDenom protected
Definition at line 131 of file RichterLFO.h.
Referenced by _calcFreq(), getTempoDenom(), and setTempoDenom().
_tempoNumer
double WECore::Richter::RichterLFO::_tempoNumer protected
Definition at line 130 of file RichterLFO.h.
Referenced by _calcFreq(), getTempoNumer(), and setTempoNumer().
_tempoSyncSwitch
bool WECore::Richter::RichterLFO::_tempoSyncSwitch protected
Definition at line 125 of file RichterLFO.h.
Referenced by _calcFreq(), getTempoSyncSwitch(), and setTempoSyncSwitch().
_wave
int WECore::Richter::RichterLFO::_wave protected
Definition at line 121 of file RichterLFO.h.
Referenced by getWave(), and setWave().
_waveArrayPointer
const double* WECore::Richter::RichterLFO::_waveArrayPointer protected
Definition at line 142 of file RichterLFO.h.
Referenced by _calcLFOValue(), and setWave().
_wavetablePosition
double WECore::Richter::RichterLFO::_wavetablePosition protected
Definition at line 140 of file RichterLFO.h.
Referenced by _calcLFOValue(), and _resetImpl().
The documentation for this class was generated from the following file:
RichterLFO.h