WE Core: WECore::JUCEPlugin::CoreAudioProcessor Class Reference
WECore::JUCEPlugin::CoreAudioProcessor Class Reference abstract
#include <CoreAudioProcessor.h>
Classes
struct CustomParameterInterface
class ParameterBroadcaster
struct ParameterInterface
Public Member Functions
CoreAudioProcessor ()
CoreAudioProcessor (const BusesProperties &ioLayouts)
virtual ~CoreAudioProcessor ()
void addParameterChangeListener (juce::ChangeListener *listener)
void removeParameterChangeListener (juce::ChangeListener *listener)
virtual void getStateInformation (juce::MemoryBlock &destData) override
std::unique_ptr< juce::XmlElement > writeToXml ()
virtual void setStateInformation (const void *data, int sizeInBytes) override
void restoreFromXml (std::unique_ptr< juce::XmlElement > element)
void setParameterValueInternal (juce::AudioParameterFloat *param, float value)
void setParameterValueInternal (juce::AudioParameterInt *param, int value)
void setParameterValueInternal (juce::AudioParameterBool *param, bool value)
Public Member Functions inherited from WECore::JUCEPlugin::ParameterUpdateHandler
ParameterUpdateHandler ()
virtual ~ParameterUpdateHandler ()=default
Protected Member Functions
virtual std::vector< juce::String > _provideParamNamesForMigration ()=0
virtual void _migrateParamValues (std::vector< float > &paramValues)=0
void registerParameter (juce::AudioParameterFloat *&param, const juce::String &name, const ParameterDefinition::RangedParameter< double > *range, float defaultValue, float precision)
void registerParameter (juce::AudioParameterFloat *&param, const juce::String &name, const ParameterDefinition::RangedParameter< float > *range, float defaultValue, float precision)
void registerParameter (juce::AudioParameterInt *&param, const juce::String &name, const ParameterDefinition::BaseParameter< int > *range, int defaultValue)
void registerParameter (juce::AudioParameterBool *&param, const juce::String &name, bool defaultValue)
void registerPrivateParameter (juce::AudioParameterFloat *&param, const juce::String &name, const ParameterDefinition::RangedParameter< double > *range, float defaultValue, float precision, std::function< void(float)> setter)
void registerPrivateParameter (juce::AudioParameterInt *&param, const juce::String &name, const ParameterDefinition::BaseParameter< int > *range, int defaultValue, std::function< void(int)> setter)
template<typename PARAM_TYPE >
void registerPrivateParameter (PARAM_TYPE *&param, const juce::String &name)
Protected Member Functions inherited from WECore::JUCEPlugin::ParameterUpdateHandler
virtual void _onParameterUpdate ()=0
Private Member Functions
std::vector< float > _stringToFloatVector (const juce::String sFloatCSV) const
std::unique_ptr< juce::XmlElement > _migrateParameters (std::unique_ptr< juce::XmlElement > rootElement)
Private Attributes
std::vector< juce::AudioProcessorParameter * > _privateParameters
std::vector< CustomParameter * > _customParameters
ParameterBroadcaster _parameterBroadcaster
std::vector< ParameterInterface > _paramsList
std::vector< CustomParameterInterface > _customParamsList
Static Private Attributes
static constexpr int PARAMS_SCHEMA_VERSION {1}
Additional Inherited Members
Protected Attributes inherited from WECore::JUCEPlugin::ParameterUpdateHandler
ParameterUpdateListener _parameterListener
Detailed Description
This class provides basic functionality that is commonly used by an AudioProcessor in a White Elephant plugin.
Classes inheriting from this should:
Call registerParameter to declare parameters
Definition at line 41 of file CoreAudioProcessor.h.
Constructor & Destructor Documentation
CoreAudioProcessor() [1/2]
WECore::JUCEPlugin::CoreAudioProcessor::CoreAudioProcessor () inline
Definition at line 244 of file CoreAudioProcessor.h.
References WECore::JUCEPlugin::ParameterUpdateHandler::_parameterListener, and addParameterChangeListener().
CoreAudioProcessor() [2/2]
WECore::JUCEPlugin::CoreAudioProcessor::CoreAudioProcessor (const BusesProperties & ioLayouts) inline
Definition at line 248 of file CoreAudioProcessor.h.
References WECore::JUCEPlugin::ParameterUpdateHandler::_parameterListener, and addParameterChangeListener().
~CoreAudioProcessor()
WECore::JUCEPlugin::CoreAudioProcessor::~CoreAudioProcessor () inline virtual
Definition at line 252 of file CoreAudioProcessor.h.
References _customParameters, and _privateParameters.
Member Function Documentation
_migrateParameters()
std::unique_ptr< juce::XmlElement > WECore::JUCEPlugin::CoreAudioProcessor::_migrateParameters (std::unique_ptr< juce::XmlElement > rootElement) inline private
Definition at line 453 of file CoreAudioProcessor.h.
References _migrateParamValues(), _provideParamNamesForMigration(), and _stringToFloatVector().
Referenced by restoreFromXml().
_migrateParamValues()
virtual void WECore::JUCEPlugin::CoreAudioProcessor::_migrateParamValues (std::vector< float > & paramValues) protected pure virtual
Override this to migrate saved parameter values from normalised to internal.
Referenced by _migrateParameters().
_provideParamNamesForMigration()
virtual std::vector< juce::String > WECore::JUCEPlugin::CoreAudioProcessor::_provideParamNamesForMigration () protected pure virtual
Override this and return a vector of parameter names corresponding to the order that parameters were stored in using the legacy schema.
Referenced by _migrateParameters().
_stringToFloatVector()
std::vector< float > WECore::JUCEPlugin::CoreAudioProcessor::_stringToFloatVector (const juce::String sFloatCSV) const inline private
Definition at line 440 of file CoreAudioProcessor.h.
Referenced by _migrateParameters().
addParameterChangeListener()
void WECore::JUCEPlugin::CoreAudioProcessor::addParameterChangeListener (juce::ChangeListener * listener) inline
Adds a listener that will be notified whenever a parameter is changed.
Definition at line 60 of file CoreAudioProcessor.h.
References _parameterBroadcaster.
Referenced by CoreAudioProcessor(), and CoreAudioProcessor().
getStateInformation()
void WECore::JUCEPlugin::CoreAudioProcessor::getStateInformation (juce::MemoryBlock & destData) inline override virtual
Calls writeToXml and stores the XML in the given memory block.
Definition at line 274 of file CoreAudioProcessor.h.
References writeToXml().
registerParameter() [1/4]
void WECore::JUCEPlugin::CoreAudioProcessor::registerParameter (juce::AudioParameterBool *& param, const juce::String & name, bool defaultValue) inline protected
Used to register public parameters that are visible to the host.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
(Bool parameters don't have a meaningful range.)
Definition at line 380 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, and setParameterValueInternal().
registerParameter() [2/4]
void WECore::JUCEPlugin::CoreAudioProcessor::registerParameter (juce::AudioParameterFloat *& param, const juce::String & name, const ParameterDefinition::RangedParameter< double > * range, float defaultValue, float precision) inline protected
Used to register public parameters that are visible to the host.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
(Bool parameters don't have a meaningful range.)
Definition at line 333 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, ParameterDefinition::BaseParameter< T >::maxValue, ParameterDefinition::BaseParameter< T >::minValue, and setParameterValueInternal().
registerParameter() [3/4]
void WECore::JUCEPlugin::CoreAudioProcessor::registerParameter (juce::AudioParameterFloat *& param, const juce::String & name, const ParameterDefinition::RangedParameter< float > * range, float defaultValue, float precision) inline protected
Used to register public parameters that are visible to the host.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
(Bool parameters don't have a meaningful range.)
Definition at line 349 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, ParameterDefinition::BaseParameter< T >::maxValue, ParameterDefinition::BaseParameter< T >::minValue, and setParameterValueInternal().
registerParameter() [4/4]
void WECore::JUCEPlugin::CoreAudioProcessor::registerParameter (juce::AudioParameterInt *& param, const juce::String & name, const ParameterDefinition::BaseParameter< int > * range, int defaultValue) inline protected
Used to register public parameters that are visible to the host.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
(Bool parameters don't have a meaningful range.)
Definition at line 365 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, ParameterDefinition::BaseParameter< T >::maxValue, ParameterDefinition::BaseParameter< T >::minValue, and setParameterValueInternal().
registerPrivateParameter() [1/3]
void WECore::JUCEPlugin::CoreAudioProcessor::registerPrivateParameter (juce::AudioParameterFloat *& param, const juce::String & name, const ParameterDefinition::RangedParameter< double > * range, float defaultValue, float precision, std::function< void(float)> setter) inline protected
Used to register private parameters that are not visible to the host. Used for parameters that cause other parameter or state changes so make automation impractical, but should still be saved/restored and trigger updates through the ParameterBroadcaster as usual.
These parameters typically need a custom setter when being restored to trigger the extra parameter/state changes.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
Custom parameters don't have a range and can only ever be private.
(Bool parameters don't have a meaningful range.)
Definition at line 394 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, _privateParameters, ParameterDefinition::BaseParameter< T >::maxValue, and ParameterDefinition::BaseParameter< T >::minValue.
registerPrivateParameter() [2/3]
void WECore::JUCEPlugin::CoreAudioProcessor::registerPrivateParameter (juce::AudioParameterInt *& param, const juce::String & name, const ParameterDefinition::BaseParameter< int > * range, int defaultValue, std::function< void(int)> setter) inline protected
Used to register private parameters that are not visible to the host. Used for parameters that cause other parameter or state changes so make automation impractical, but should still be saved/restored and trigger updates through the ParameterBroadcaster as usual.
These parameters typically need a custom setter when being restored to trigger the extra parameter/state changes.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
Custom parameters don't have a range and can only ever be private.
(Bool parameters don't have a meaningful range.)
Definition at line 411 of file CoreAudioProcessor.h.
References _parameterBroadcaster, _paramsList, _privateParameters, ParameterDefinition::BaseParameter< T >::maxValue, and ParameterDefinition::BaseParameter< T >::minValue.
registerPrivateParameter() [3/3]
template<typename PARAM_TYPE > void WECore::JUCEPlugin::CoreAudioProcessor::registerPrivateParameter (PARAM_TYPE *& param, const juce::String & name) inline protected
Used to register private parameters that are not visible to the host. Used for parameters that cause other parameter or state changes so make automation impractical, but should still be saved/restored and trigger updates through the ParameterBroadcaster as usual.
These parameters typically need a custom setter when being restored to trigger the extra parameter/state changes.
The parameter will be deleted when the processor class is deallocated.
Float parameters are created with their real (not normalised) ranges.
Int parameters are created with their real (not normalised) ranges.
Custom parameters don't have a range and can only ever be private.
(Bool parameters don't have a meaningful range.)
Definition at line 428 of file CoreAudioProcessor.h.
References _customParameters, _customParamsList, and _parameterBroadcaster.
removeParameterChangeListener()
void WECore::JUCEPlugin::CoreAudioProcessor::removeParameterChangeListener (juce::ChangeListener * listener) inline
Removes a previously added listener.
Definition at line 67 of file CoreAudioProcessor.h.
References _parameterBroadcaster.
restoreFromXml()
void WECore::JUCEPlugin::CoreAudioProcessor::restoreFromXml (std::unique_ptr< juce::XmlElement > element) inline
Restores parameter values from previously written XML.
Definition at line 304 of file CoreAudioProcessor.h.
References _customParamsList, _migrateParameters(), _paramsList, and PARAMS_SCHEMA_VERSION.
Referenced by setStateInformation().
setParameterValueInternal() [1/3]
void WECore::JUCEPlugin::CoreAudioProcessor::setParameterValueInternal (juce::AudioParameterBool * param, bool value) inline
Sets a given parameter using a value in the internal (non-normalised) range.
Definition at line 270 of file CoreAudioProcessor.h.
setParameterValueInternal() [2/3]
void WECore::JUCEPlugin::CoreAudioProcessor::setParameterValueInternal (juce::AudioParameterFloat * param, float value) inline
Sets a given parameter using a value in the internal (non-normalised) range.
Definition at line 262 of file CoreAudioProcessor.h.
Referenced by registerParameter(), registerParameter(), registerParameter(), and registerParameter().
setParameterValueInternal() [3/3]
void WECore::JUCEPlugin::CoreAudioProcessor::setParameterValueInternal (juce::AudioParameterInt * param, int value) inline
Sets a given parameter using a value in the internal (non-normalised) range.
Definition at line 266 of file CoreAudioProcessor.h.
setStateInformation()
void WECore::JUCEPlugin::CoreAudioProcessor::setStateInformation (const void * data, int sizeInBytes) inline override virtual
Reads the given memory into an XmlElement and calls restoreFromXml.
Definition at line 299 of file CoreAudioProcessor.h.
References restoreFromXml().
writeToXml()
std::unique_ptr< juce::XmlElement > WECore::JUCEPlugin::CoreAudioProcessor::writeToXml () inline
Collects the registered parameter values and writes them to XML.
Float parameters are written in their normalised 0 to 1 range.
Int parameters are written as a float representation of their real (not normalised) value.
Bool parameters are written as a float representation of true or false.
Definition at line 279 of file CoreAudioProcessor.h.
References _customParamsList, _paramsList, and PARAMS_SCHEMA_VERSION.
Referenced by getStateInformation().
Member Data Documentation
_customParameters
std::vector<CustomParameter*> WECore::JUCEPlugin::CoreAudioProcessor::_customParameters private
Definition at line 188 of file CoreAudioProcessor.h.
Referenced by registerPrivateParameter(), and ~CoreAudioProcessor().
_customParamsList
std::vector<CustomParameterInterface> WECore::JUCEPlugin::CoreAudioProcessor::_customParamsList private
Definition at line 234 of file CoreAudioProcessor.h.
Referenced by registerPrivateParameter(), restoreFromXml(), and writeToXml().
_parameterBroadcaster
ParameterBroadcaster WECore::JUCEPlugin::CoreAudioProcessor::_parameterBroadcaster private
Definition at line 228 of file CoreAudioProcessor.h.
Referenced by addParameterChangeListener(), registerParameter(), registerParameter(), registerParameter(), registerParameter(), registerPrivateParameter(), registerPrivateParameter(), registerPrivateParameter(), and removeParameterChangeListener().
_paramsList
std::vector<ParameterInterface> WECore::JUCEPlugin::CoreAudioProcessor::_paramsList private
List of parameters which will trigger updates and are stored in XML.
Definition at line 233 of file CoreAudioProcessor.h.
Referenced by registerParameter(), registerParameter(), registerParameter(), registerParameter(), registerPrivateParameter(), registerPrivateParameter(), restoreFromXml(), and writeToXml().
_privateParameters
std::vector<juce::AudioProcessorParameter*> WECore::JUCEPlugin::CoreAudioProcessor::_privateParameters private
Definition at line 187 of file CoreAudioProcessor.h.
Referenced by registerPrivateParameter(), registerPrivateParameter(), and ~CoreAudioProcessor().
PARAMS_SCHEMA_VERSION
int WECore::JUCEPlugin::CoreAudioProcessor::PARAMS_SCHEMA_VERSION {1} static constexpr private
Definition at line 183 of file CoreAudioProcessor.h.
Referenced by restoreFromXml(), and writeToXml().
The documentation for this class was generated from the following file:
CoreAudioProcessor.h