WE Core: WECore::Songbird::SongbirdFilterModule< T > Class Template Reference
WECore::Songbird::SongbirdFilterModule< T > Class Template Reference
#include <SongbirdFilterModule.h>
Public Member Functions
SongbirdFilterModule ()
virtual ~SongbirdFilterModule ()
void reset ()
void Process1in1out (T *inSamples, size_t numSamples)
void Process2in2out (T *leftSamples, T *rightSamples, size_t numSamples)
SongbirdFilterModule operator= (SongbirdFilterModule &other)=delete
SongbirdFilterModule (SongbirdFilterModule &other)=delete
Setter Methods
void setVowel1 (int val)
void setVowel2 (int val)
void setFilterPosition (double val)
void setSampleRate (double val)
void setMix (double val)
void setOutputGain (double val)
void setModMode (bool val)
void setAirGain (double val)
void setModulationSource (std::shared_ptr< ModulationSource< double > > val)
Getter Methods
int getVowel1 () const
int getVowel2 () const
Vowel getVowelDescription (int val) const
double getFilterPosition () const
double getMix () const
bool getModMode () const
double getAirGain () const
double getOutputGain () const
Private Member Functions
void _setVowel1 (const Vowel &val)
Vowel _calcVowelForFreqMode (double modAmount)
Private Attributes
int _vowel1
int _vowel2
double _filterPosition
double _sampleRate
double _mix
double _airGain
double _outputGain
bool _modMode
std::shared_ptr< ModulationSource< double > > _modulationSource
SongbirdFormantFilter< T, NUM_FORMANTS_PER_VOWEL > _filter1Left
SongbirdFormantFilter< T, NUM_FORMANTS_PER_VOWEL > _filter1Right
SongbirdFormantFilter< T, NUM_FORMANTS_PER_VOWEL > _filter2Left
SongbirdFormantFilter< T, NUM_FORMANTS_PER_VOWEL > _filter2Right
SongbirdFormantFilter< T, NUM_AIR_FORMANTS > _filterAirLeft
SongbirdFormantFilter< T, NUM_AIR_FORMANTS > _filterAirRight
const Vowel _allFormants [NUM_VOWELS]
Detailed Description
template<typename T>
class WECore::Songbird::SongbirdFilterModule< T >
A filter module providing five different vowel sounds, any two of which can be selected simulaneously and blended between.
Also provides an "air" function which is a pair of fixed frequency formant filters at higher frequency that can be blended into the output.
To use this class, simply call reset, and the process methods as necessary, using the provided getter and setter methods to manipulate parameters.
You must call setSampleRate before beginning any processing as the default sample rate might not be the one you want.
Internally relies on the parameters provided in SongbirdFiltersParameters.h
See also
SongbirdFormantFilter - SongbirdFilterModule is composed of two pairs of SongbirdFormantFilters (pairs to allow stereo processing), each pair is assigned one of the five supported vowels at any time
A SongbirdFilterModule can be created and used to process a buffer as follows:
SongbirdFilterModule filter;
filter.setSampleRate(44100);
filter.setVowel1(VOWEL.VOWEL_O);
filter.setVowel2(VOWEL.VOWEL_I);
...
set any other parameters you need
...
filter.Process2in2out(leftSamples, rightSamples, numSamples);
Definition at line 85 of file SongbirdFilterModule.h.
Constructor & Destructor Documentation
SongbirdFilterModule() [1/2]
template<typename T > WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule () inline
Does some basic setup and defaulting of parameters, though do not rely on this to sensibly default all parameters.
Definition at line 94 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_filterAirLeft, WECore::Songbird::SongbirdFilterModule< T >::_filterAirRight, WECore::Songbird::SongbirdFilterModule< T >::_vowel1, WECore::Songbird::SongbirdFilterModule< T >::_vowel2, WECore::Songbird::SongbirdFormantFilter< T, NUM_FORMANTS >::setFormants(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().
~SongbirdFilterModule()
template<typename T > virtual WECore::Songbird::SongbirdFilterModule< T >::~SongbirdFilterModule () inline virtual
Definition at line 116 of file SongbirdFilterModule.h.
SongbirdFilterModule() [2/2]
template<typename T > WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule (SongbirdFilterModule< T > & other) delete
Member Function Documentation
_calcVowelForFreqMode()
template<typename T > Vowel WECore::Songbird::SongbirdFilterModule< T >::_calcVowelForFreqMode (double modAmount) inline private
Uses the filterPosition parameter and the modulation source to calculate the vowel that should be used when in MODMODE_FREQ, as this vowel will sit somewhere between the two vowels that have been selected by the user.
Parameters
modAmount Modulation amount to be applied
Definition at line 485 of file SongbirdFilterModule.h.
References WECore::Songbird::NUM_FORMANTS_PER_VOWEL.
_setVowel1()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::_setVowel1 (const Vowel & val) inline private
Sets the vowel sound that should be created by filter 1 using a Vowel object provided by the caller rather than one of the built in Vowel objects stored in this class.
Parameters
val Value that should be used for Vowel 1
Definition at line 479 of file SongbirdFilterModule.h.
getAirGain()
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::getAirGain () const inline
See also
setAirGain
Definition at line 247 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_airGain.
Referenced by SCENARIO(), and SCENARIO().
getFilterPosition()
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::getFilterPosition () const inline
See also
setFilterPosition
Definition at line 232 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_filterPosition.
Referenced by SCENARIO(), and SCENARIO().
getMix()
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::getMix () const inline
See also
setMix
Definition at line 237 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_mix.
Referenced by SCENARIO(), and SCENARIO().
getModMode()
template<typename T > bool WECore::Songbird::SongbirdFilterModule< T >::getModMode () const inline
See also
modMode
Definition at line 242 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_modMode.
Referenced by SCENARIO().
getOutputGain()
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::getOutputGain () const inline
See also
setOutputGain
Definition at line 252 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_outputGain.
getVowel1()
template<typename T > int WECore::Songbird::SongbirdFilterModule< T >::getVowel1 () const inline
See also
setVowel1
Definition at line 215 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_vowel1.
Referenced by SCENARIO(), and SCENARIO().
getVowel2()
template<typename T > int WECore::Songbird::SongbirdFilterModule< T >::getVowel2 () const inline
See also
setVowel2
Definition at line 220 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_vowel2.
Referenced by SCENARIO(), and SCENARIO().
getVowelDescription()
template<typename T > Vowel WECore::Songbird::SongbirdFilterModule< T >::getVowelDescription (int val) const inline
Return a vowel object describing one of the built in vowels.
See also
VowelParameter for valid values
Definition at line 375 of file SongbirdFilterModule.h.
References WECore::Songbird::NUM_FORMANTS_PER_VOWEL.
operator=()
template<typename T > SongbirdFilterModule WECore::Songbird::SongbirdFilterModule< T >::operator= (SongbirdFilterModule< T > & other) delete
Process1in1out()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::Process1in1out (T * inSamples, size_t numSamples) inline
Applies the filtering to a mono buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
inSamples Pointer to the first sample of the buffer
numSamples Number of samples in the buffer. The left and right buffers must be the same size.
Definition at line 386 of file SongbirdFilterModule.h.
References WECore::Songbird::Parameters::MODMODE_BLEND.
Process2in2out()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::Process2in2out (T * leftSamples, T * rightSamples, size_t numSamples) inline
Applies the filtering to a stereo buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
leftSamples Pointer to the first sample of the left channel's buffer
rightSamples Pointer to the first sample of the right channel's buffer
numSamples Number of samples in the buffer. The left and right buffers must be the same size.
Definition at line 422 of file SongbirdFilterModule.h.
References WECore::Songbird::Parameters::MODMODE_BLEND.
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), and SCENARIO().
reset()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::reset () inline
Resets all filters. Call this whenever the audio stream is interrupted (ie. the playhead is moved)
Definition at line 365 of file SongbirdFilterModule.h.
setAirGain()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setAirGain (double val) inline
Sets the level of the upper formant filter peaks.
Parameters
[in] val Gain value that should be used
See also
AIR_GAIN for valid values
Definition at line 192 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_airGain, and WECore::Songbird::Parameters::AIR_GAIN().
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), and SCENARIO().
setFilterPosition()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setFilterPosition (double val) inline
Sets the position between the two filters that have been selected.
Parameters
[in] val Filter position to use.
See also
FILTER_POSITION for valid values
modMode which the effect of this parameter is dependent on
Definition at line 149 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_filterPosition, and WECore::Songbird::Parameters::FILTER_POSITION().
Referenced by SCENARIO(), and SCENARIO().
setMix()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setMix (double val) inline
Sets the dry/wet mix level. Lowest value = completely dry, unprocessed signal, no filtering applied. Highest value = completely wet signal, no unprocessed audio survives.
Parameters
[in] val Mix value that should be used
See also
MIX for valid values
Definition at line 167 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_mix, and WECore::Songbird::Parameters::MIX().
Referenced by SCENARIO(), and SCENARIO().
setModMode()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setModMode (bool val) inline
Sets the modulation mode to apply to the filters.
Parameters
[in] val Chooses the modulation mode
Definition at line 183 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_modMode.
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), and SCENARIO().
setModulationSource()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setModulationSource (std::shared_ptr< ModulationSource< double > > val) inline
Sets the modulation source that will be used to modulate the filter position.
Parameters
[in] val The modulation source to use
Definition at line 199 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_modulationSource.
setOutputGain()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setOutputGain (double val) inline
Sets the output gain.
Parameters
[in] val The output gain that should be used
See also
OUTPUTGAIN for valid values
Definition at line 176 of file SongbirdFilterModule.h.
References WECore::Songbird::SongbirdFilterModule< T >::_outputGain, and WECore::Songbird::Parameters::OUTPUTGAIN().
setSampleRate()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setSampleRate (double val) inline
Set the sample rate that the filters expect of the audio which will be processed.
Parameters
[in] val The sample rate to set the filters to
Definition at line 353 of file SongbirdFilterModule.h.
setVowel1()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setVowel1 (int val) inline
Sets the vowel sound that should be created by filter 1 using one of the built in Vowel objects stored in this class.
Parameters
[in] val Value that should be used for Vowel 1
See also
VowelParameter for valid values
Definition at line 335 of file SongbirdFilterModule.h.
References ParameterDefinition::BaseParameter< T >::BoundsCheck(), and WECore::Songbird::Parameters::VOWEL.
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), and WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
setVowel2()
template<typename T > void WECore::Songbird::SongbirdFilterModule< T >::setVowel2 (int val) inline
Sets the vowel sound that should be created by filter 2.
Parameters
[in] val Value that should be used for Vowel 2
See also
VowelParameter for valid values
Definition at line 344 of file SongbirdFilterModule.h.
References ParameterDefinition::BaseParameter< T >::BoundsCheck(), and WECore::Songbird::Parameters::VOWEL.
Referenced by SCENARIO(), SCENARIO(), SCENARIO(), SCENARIO(), and WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
Member Data Documentation
_airGain
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::_airGain private
Definition at line 288 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getAirGain(), and WECore::Songbird::SongbirdFilterModule< T >::setAirGain().
_allFormants
template<typename T > const Vowel WECore::Songbird::SongbirdFilterModule< T >::_allFormants[NUM_VOWELS] private
Initial value:
{
            {Formant(800, 0), Formant(1150, -4)},
            {Formant(400, 0), Formant(2100, -24)},
            {Formant(350, 0), Formant(2400, -20)},
            {Formant(450, 0), Formant(800, -9)},
            {Formant(325, 0), Formant(700, -12)},
        }
An array which defines all the formants that will be needed.
Definition at line 325 of file SongbirdFilterModule.h.
_filter1Left
template<typename T > SongbirdFormantFilter<T, NUM_FORMANTS_PER_VOWEL> WECore::Songbird::SongbirdFilterModule< T >::_filter1Left private
Definition at line 295 of file SongbirdFilterModule.h.
_filter1Right
template<typename T > SongbirdFormantFilter<T, NUM_FORMANTS_PER_VOWEL> WECore::Songbird::SongbirdFilterModule< T >::_filter1Right private
Definition at line 296 of file SongbirdFilterModule.h.
_filter2Left
template<typename T > SongbirdFormantFilter<T, NUM_FORMANTS_PER_VOWEL> WECore::Songbird::SongbirdFilterModule< T >::_filter2Left private
Definition at line 298 of file SongbirdFilterModule.h.
_filter2Right
template<typename T > SongbirdFormantFilter<T, NUM_FORMANTS_PER_VOWEL> WECore::Songbird::SongbirdFilterModule< T >::_filter2Right private
Definition at line 299 of file SongbirdFilterModule.h.
_filterAirLeft
template<typename T > SongbirdFormantFilter<T, NUM_AIR_FORMANTS> WECore::Songbird::SongbirdFilterModule< T >::_filterAirLeft private
Definition at line 301 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
_filterAirRight
template<typename T > SongbirdFormantFilter<T, NUM_AIR_FORMANTS> WECore::Songbird::SongbirdFilterModule< T >::_filterAirRight private
Definition at line 302 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
_filterPosition
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::_filterPosition private
Definition at line 285 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getFilterPosition(), and WECore::Songbird::SongbirdFilterModule< T >::setFilterPosition().
_mix
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::_mix private
Definition at line 287 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getMix(), and WECore::Songbird::SongbirdFilterModule< T >::setMix().
_modMode
template<typename T > bool WECore::Songbird::SongbirdFilterModule< T >::_modMode private
Definition at line 291 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getModMode(), and WECore::Songbird::SongbirdFilterModule< T >::setModMode().
_modulationSource
template<typename T > std::shared_ptr<ModulationSource<double> > WECore::Songbird::SongbirdFilterModule< T >::_modulationSource private
Definition at line 293 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::setModulationSource().
_outputGain
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::_outputGain private
Definition at line 289 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getOutputGain(), and WECore::Songbird::SongbirdFilterModule< T >::setOutputGain().
_sampleRate
template<typename T > double WECore::Songbird::SongbirdFilterModule< T >::_sampleRate private
Definition at line 286 of file SongbirdFilterModule.h.
_vowel1
template<typename T > int WECore::Songbird::SongbirdFilterModule< T >::_vowel1 private
Definition at line 282 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
_vowel2
template<typename T > int WECore::Songbird::SongbirdFilterModule< T >::_vowel2 private
Definition at line 283 of file SongbirdFilterModule.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::getVowel2(), and WECore::Songbird::SongbirdFilterModule< T >::SongbirdFilterModule().
The documentation for this class was generated from the following file:
SongbirdFilterModule.h