WE Core: ParameterDefinition::BaseParameter< T > Class Template Reference
ParameterDefinition::BaseParameter< T > Class Template Reference
#include <ParameterDefinition.h>
Public Member Functions
BaseParameter ()=delete
virtual ~BaseParameter ()=default
BaseParameter (T newMinValue, T newMaxValue, T newDefaultValue)
T BoundsCheck (T val) const
Public Attributes
const T minValue
const T maxValue
const T defaultValue
Detailed Description
template<class T>
class ParameterDefinition::BaseParameter< T >
Provides basic functionality that may be useful for building other parameters from.
Definition at line 64 of file ParameterDefinition.h.
Constructor & Destructor Documentation
BaseParameter() [1/2]
template<class T > ParameterDefinition::BaseParameter< T >::BaseParameter () delete
~BaseParameter()
template<class T > virtual ParameterDefinition::BaseParameter< T >::~BaseParameter () virtual default
BaseParameter() [2/2]
template<class T > ParameterDefinition::BaseParameter< T >::BaseParameter (T newMinValue, T newMaxValue, T newDefaultValue) inline
Definition at line 74 of file ParameterDefinition.h.
Member Function Documentation
BoundsCheck()
template<class T > T ParameterDefinition::BaseParameter< T >::BoundsCheck (T val) const inline
If the given value is between the minimum and maximum values for this parameter, then the value is returned unchanged. If the given value is outside the minimum and maximum values for this parameter, the given value is clipped to this range and then returned.
Parameters
val Value to clip to minumum and maximum values
Returns
Clipped value
Definition at line 90 of file ParameterDefinition.h.
References ParameterDefinition::BoundsCheck(), ParameterDefinition::BaseParameter< T >::maxValue, and ParameterDefinition::BaseParameter< T >::minValue.
Referenced by WECore::Carve::CarveDSPUnit< T >::setMode(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), WECore::Songbird::SongbirdFilterModule< T >::setVowel2(), and WECore::Richter::RichterLFO::setWave().
Member Data Documentation
defaultValue
template<class T > const T ParameterDefinition::BaseParameter< T >::defaultValue
Definition at line 69 of file ParameterDefinition.h.
maxValue
template<class T > const T ParameterDefinition::BaseParameter< T >::maxValue
Definition at line 68 of file ParameterDefinition.h.
Referenced by ParameterDefinition::BaseParameter< T >::BoundsCheck(), ParameterDefinition::RangedParameter< T >::InternalToNormalised(), ParameterDefinition::RangedParameter< T >::NormalisedToInternal(), WECore::JUCEPlugin::CoreAudioProcessor::registerParameter(), and WECore::JUCEPlugin::CoreAudioProcessor::registerPrivateParameter().
minValue
template<class T > const T ParameterDefinition::BaseParameter< T >::minValue
Definition at line 67 of file ParameterDefinition.h.
Referenced by ParameterDefinition::BaseParameter< T >::BoundsCheck(), ParameterDefinition::RangedParameter< T >::InternalToNormalised(), ParameterDefinition::RangedParameter< T >::NormalisedToInternal(), WECore::JUCEPlugin::CoreAudioProcessor::registerParameter(), and WECore::JUCEPlugin::CoreAudioProcessor::registerPrivateParameter().
The documentation for this class was generated from the following file:
ParameterDefinition.h