WE Core: WECore::Carve::NoiseFilter< T > Class Template Reference
WECore::Carve::NoiseFilter< T > Class Template Reference
#include <CarveNoiseFilter.h>
Public Member Functions
NoiseFilter (double lowCutHz, double highCutHz)
virtual ~NoiseFilter ()
void setSampleRate (double sampleRate)
void reset ()
void Process1in1out (T *inSample, size_t numSamples)
void Process2in2out (T *inLeftSample, T *inRightSample, size_t numSamples)
Private Attributes
WECore::TPTSVF::TPTSVFilter< T > _monoLowCutFilter
WECore::TPTSVF::TPTSVFilter< T > _leftLowCutFilter
WECore::TPTSVF::TPTSVFilter< T > _rightLowCutFilter
WECore::TPTSVF::TPTSVFilter< T > _monoHighCutFilter
WECore::TPTSVF::TPTSVFilter< T > _leftHighCutFilter
WECore::TPTSVF::TPTSVFilter< T > _rightHighCutFilter
double _lowCutHz
double _highCutHz
Detailed Description
template<typename T>
class WECore::Carve::NoiseFilter< T >
Definition at line 44 of file CarveNoiseFilter.h.
Constructor & Destructor Documentation
NoiseFilter()
template<typename T > WECore::Carve::NoiseFilter< T >::NoiseFilter (double lowCutHz, double highCutHz)
Defaults the sample rate. It is recommended to call setSampleRate manually before attempting any processing.
Parameters
lowCutHz Everything below this frequency will be cut
highCutHz Everything above this frequency will be cut
Definition at line 106 of file CarveNoiseFilter.h.
References WECore::Carve::NoiseFilter< T >::_leftHighCutFilter, WECore::Carve::NoiseFilter< T >::_leftLowCutFilter, WECore::Carve::NoiseFilter< T >::_monoHighCutFilter, WECore::Carve::NoiseFilter< T >::_monoLowCutFilter, WECore::Carve::NoiseFilter< T >::_rightHighCutFilter, WECore::Carve::NoiseFilter< T >::_rightLowCutFilter, WECore::TPTSVF::Parameters::ModeParameter::HIGHPASS, WECore::TPTSVF::Parameters::ModeParameter::LOWPASS, and WECore::Carve::NoiseFilter< T >::setSampleRate().
~NoiseFilter()
template<typename T > virtual WECore::Carve::NoiseFilter< T >::~NoiseFilter () inline virtual
Definition at line 56 of file CarveNoiseFilter.h.
Member Function Documentation
Process1in1out()
template<typename T > void WECore::Carve::NoiseFilter< T >::Process1in1out (T * inSample, size_t numSamples) inline
Applies the filtering to a mono buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
inSample Pointer to the first sample of the buffer
numSamples Number of samples in the buffer
Definition at line 156 of file CarveNoiseFilter.h.
Referenced by SCENARIO().
Process2in2out()
template<typename T > void WECore::Carve::NoiseFilter< T >::Process2in2out (T * inLeftSample, T * inRightSample, size_t numSamples) inline
Applies the filtering to a stereo buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
inLeftSample Pointer to the first sample of the left channel's buffer
inRightSample Pointer to the first sample of the right channel's buffer
numSamples Number of samples in the buffer. The left and right buffers must be the same size.
Definition at line 162 of file CarveNoiseFilter.h.
reset()
template<typename T > void WECore::Carve::NoiseFilter< T >::reset inline
Resets all filters. Call this whenever the audio stream is interrupted (ie. the playhead is moved)
Definition at line 145 of file CarveNoiseFilter.h.
setSampleRate()
template<typename T > void WECore::Carve::NoiseFilter< T >::setSampleRate (double sampleRate) inline
Configures the filters for the correct sample rate. Ensure this is called before attempting to process audio.
Parameters
sampleRate The sample rate the filter should be configured for
Definition at line 134 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter(), and SCENARIO().
Member Data Documentation
_highCutHz
template<typename T > double WECore::Carve::NoiseFilter< T >::_highCutHz private
Definition at line 102 of file CarveNoiseFilter.h.
_leftHighCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_leftHighCutFilter private
Definition at line 98 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
_leftLowCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_leftLowCutFilter private
Definition at line 94 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
_lowCutHz
template<typename T > double WECore::Carve::NoiseFilter< T >::_lowCutHz private
Definition at line 101 of file CarveNoiseFilter.h.
_monoHighCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_monoHighCutFilter private
Definition at line 97 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
_monoLowCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_monoLowCutFilter private
Definition at line 93 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
_rightHighCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_rightHighCutFilter private
Definition at line 99 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
_rightLowCutFilter
template<typename T > WECore::TPTSVF::TPTSVFilter<T> WECore::Carve::NoiseFilter< T >::_rightLowCutFilter private
Definition at line 95 of file CarveNoiseFilter.h.
Referenced by WECore::Carve::NoiseFilter< T >::NoiseFilter().
The documentation for this class was generated from the following file:
CarveNoiseFilter.h