WE Core: WECore::TPTSVF::TPTSVFilter< T > Class Template Reference
WECore::TPTSVF::TPTSVFilter< T > Class Template Reference
#include <TPTSVFilter.h>
Public Member Functions
TPTSVFilter ()
virtual ~TPTSVFilter ()=default
void processBlock (T *inSamples, size_t numSamples)
void reset ()
TPTSVFilter clone () const
Getter Methods
int getMode () const
double getCutoff () const
double getQ () const
double getGain () const
Setter Methods
void setMode (int val)
void setCutoff (double val)
void setQ (double val)
void setGain (double val)
void setSampleRate (double val)
Private Member Functions
void _calculateCoefficients ()
TPTSVFilter (const TPTSVFilter &other)
Private Attributes
double _sampleRate
double _cutoffHz
double _q
double _gain
T _s1
T _s2
T _g
T _h
int _mode
Detailed Description
template<typename T>
class WECore::TPTSVF::TPTSVFilter< T >
A state variable filter from a topology-preserving transform.
To use this class, simply call reset, and the process methods as necessary, using the provided getter and setter methods to manipulate parameters.
Internally relies on the parameters provided in TPTSVFilterParameters.h
Based on a talk given by Ivan Cohen: https://www.youtube.com/watch?v=esjHXGPyrhg
Definition at line 39 of file TPTSVFilter.h.
Constructor & Destructor Documentation
TPTSVFilter() [1/2]
template<typename T > WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter () inline
Definition at line 44 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_calculateCoefficients().
Referenced by WECore::TPTSVF::TPTSVFilter< T >::clone().
~TPTSVFilter()
template<typename T > virtual WECore::TPTSVF::TPTSVFilter< T >::~TPTSVFilter () virtual default
TPTSVFilter() [2/2]
template<typename T > WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter (const TPTSVFilter< T > & other) inline private
Definition at line 116 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_cutoffHz, WECore::TPTSVF::TPTSVFilter< T >::_g, WECore::TPTSVF::TPTSVFilter< T >::_gain, WECore::TPTSVF::TPTSVFilter< T >::_h, WECore::TPTSVF::TPTSVFilter< T >::_mode, WECore::TPTSVF::TPTSVFilter< T >::_q, WECore::TPTSVF::TPTSVFilter< T >::_s1, WECore::TPTSVF::TPTSVFilter< T >::_s2, and WECore::TPTSVF::TPTSVFilter< T >::_sampleRate.
Member Function Documentation
_calculateCoefficients()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::_calculateCoefficients () private
Definition at line 183 of file TPTSVFilter.h.
References WECore::CoreMath::DOUBLE_PI.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
clone()
template<typename T > TPTSVFilter WECore::TPTSVF::TPTSVFilter< T >::clone () const inline
Definition at line 97 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
Referenced by SCENARIO().
getCutoff()
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::getCutoff () const inline
Definition at line 80 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_cutoffHz.
Referenced by WECore::AREnv::AREnvelopeFollowerBase::getHighCutHz(), WECore::AREnv::AREnvelopeFollowerBase::getLowCutHz(), SCENARIO(), SCENARIO(), and SCENARIO().
getGain()
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::getGain () const inline
Definition at line 82 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_gain.
Referenced by SCENARIO(), SCENARIO(), and SCENARIO().
getMode()
template<typename T > int WECore::TPTSVF::TPTSVFilter< T >::getMode () const inline
Definition at line 79 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_mode.
Referenced by SCENARIO(), SCENARIO(), and SCENARIO().
getQ()
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::getQ () const inline
Definition at line 81 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_q.
Referenced by SCENARIO(), SCENARIO(), and SCENARIO().
processBlock()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::processBlock (T * inSamples, size_t numSamples)
Applies the filtering to a buffer of samples. Expect seg faults or other memory issues if arguements passed are incorrect.
Parameters
[out] inSamples Pointer to the first sample of the left channel's buffer
[in] numSamples Number of samples in the buffer
Definition at line 132 of file TPTSVFilter.h.
References WECore::TPTSVF::Parameters::FILTER_MODE, WECore::TPTSVF::Parameters::ModeParameter::HIGHPASS, and WECore::TPTSVF::Parameters::ModeParameter::PEAK.
Referenced by WECore::AREnv::AREnvelopeFollowerBase::_getNextOutputImpl(), SCENARIO(), and SCENARIO().
reset()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::reset () inline
Resets filter coefficients. Call this whenever the audio stream is interrupted (ie. the playhead is moved)
Definition at line 71 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_s1, and WECore::TPTSVF::TPTSVFilter< T >::_s2.
Referenced by WECore::AREnv::AREnvelopeFollowerBase::_resetImpl().
setCutoff()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::setCutoff (double val) inline
Definition at line 165 of file TPTSVFilter.h.
References WECore::TPTSVF::Parameters::CUTOFF().
Referenced by WECore::AREnv::AREnvelopeFollowerBase::AREnvelopeFollowerBase(), SCENARIO(), SCENARIO(), SCENARIO(), WECore::AREnv::AREnvelopeFollowerBase::setHighCutHz(), and WECore::AREnv::AREnvelopeFollowerBase::setLowCutHz().
setGain()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::setGain (double val) inline
Definition at line 92 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_gain, and WECore::TPTSVF::Parameters::GAIN().
Referenced by SCENARIO(), SCENARIO(), and SCENARIO().
setMode()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::setMode (int val) inline
Definition at line 89 of file TPTSVFilter.h.
References WECore::TPTSVF::TPTSVFilter< T >::_mode, ParameterDefinition::BaseParameter< T >::BoundsCheck(), and WECore::TPTSVF::Parameters::FILTER_MODE.
Referenced by WECore::AREnv::AREnvelopeFollowerBase::AREnvelopeFollowerBase(), SCENARIO(), SCENARIO(), and SCENARIO().
setQ()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::setQ (double val) inline
Definition at line 171 of file TPTSVFilter.h.
References WECore::TPTSVF::Parameters::Q().
Referenced by SCENARIO(), SCENARIO(), and SCENARIO().
setSampleRate()
template<typename T > void WECore::TPTSVF::TPTSVFilter< T >::setSampleRate (double val) inline
Definition at line 177 of file TPTSVFilter.h.
Referenced by SCENARIO(), and WECore::AREnv::AREnvelopeFollowerBase::setSampleRate().
Member Data Documentation
_cutoffHz
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::_cutoffHz private
Definition at line 103 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::getCutoff(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_g
template<typename T > T WECore::TPTSVF::TPTSVFilter< T >::_g private
Definition at line 109 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_gain
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::_gain private
Definition at line 105 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::getGain(), WECore::TPTSVF::TPTSVFilter< T >::setGain(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_h
template<typename T > T WECore::TPTSVF::TPTSVFilter< T >::_h private
Definition at line 110 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_mode
template<typename T > int WECore::TPTSVF::TPTSVFilter< T >::_mode private
Definition at line 112 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::getMode(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_q
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::_q private
Definition at line 104 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::getQ(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_s1
template<typename T > T WECore::TPTSVF::TPTSVFilter< T >::_s1 private
Definition at line 107 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::reset(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_s2
template<typename T > T WECore::TPTSVF::TPTSVFilter< T >::_s2 private
Definition at line 108 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::reset(), and WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
_sampleRate
template<typename T > double WECore::TPTSVF::TPTSVFilter< T >::_sampleRate private
Definition at line 102 of file TPTSVFilter.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::TPTSVFilter().
The documentation for this class was generated from the following file:
TPTSVFilter.h