WE Core: WECore::Richter::RichterMOD Class Reference
WECore::Richter::RichterMOD Class Reference
#include <RichterMOD.h>
Public Member Functions
RichterMOD ()
virtual ~RichterMOD ()=default
double calcGainInLoop ()
RichterMOD operator= (RichterMOD &other)=delete
RichterMOD (RichterMOD &other)=delete
Public Member Functions inherited from WECore::Richter::RichterLFOBase
RichterLFOBase ()
virtual ~RichterLFOBase ()
void prepareForNextBuffer (double bpm, double timeInSeconds, double sampleRate)
void reset ()
RichterLFOBase operator= (RichterLFOBase &other)=delete
RichterLFOBase (RichterLFOBase &other)=delete
bool getBypassSwitch () const
bool getPhaseSyncSwitch () const
bool getTempoSyncSwitch () const
int getWave () const
double getDepth () const
double getFreq () const
int getManualPhase () const
double getTempoNumer () const
double getTempoDenom () const
float getWaveArraySize () const
int getIndexOffset ()
void setBypassSwitch (bool val)
void setPhaseSyncSwitch (bool val)
void setTempoSyncSwitch (bool val)
void setTempoNumer (int val)
void setTempoDenom (int val)
void setFreq (double val)
void setDepth (double val)
void setManualPhase (int val)
void setWave (int val)
void setWaveTablePointers ()
void setIndexOffset (int val)
Private Member Functions
double _calcGain ()
Friends
class RichterLFOPair
Additional Inherited Members
Protected Member Functions inherited from WECore::Richter::RichterLFOBase
void _calcPhaseOffset (double timeInSeconds)
void _calcFreq (double bpm)
void _calcSamplesPerTremoloCycle (double sampleRate)
void _calcNextScale ()
void calcIndexAndScaleInLoop ()
Protected Attributes inherited from WECore::Richter::RichterLFOBase
int _manualPhase
int _wave
int _index
int _indexOffset
long _samplesProcessed
bool _bypassSwitch
bool _tempoSyncSwitch
bool _phaseSyncSwitch
bool _needsPhaseCalc
double _tempoNumer
double _tempoDenom
double _tempoFreq
double _freq
double _depth
double _samplesPerTremoloCycle
double _gain
double _offset
double _currentScale
double _nextScale
double * _waveArrayPointer
double _sineTable [Parameters::kWaveArraySize]
double _squareTable [Parameters::kWaveArraySize]
double _sawTable [Parameters::kWaveArraySize]
Detailed Description
Provides and LFO with: depth, rate, tempo sync, phase, wave shape, and phase sync controls. This LFO oscillates between -1 and 1, and so is useful as a modulation source for parameters.
To use, you simply need to call reset, prepareForNextBuffer, and calcGainInLoop as necessary (see their descriptions for details), and use the provided getter and setter methods to manipulate parameters.
Completes the implementation of RichterLFO.
Definition at line 43 of file RichterMOD.h.
Constructor & Destructor Documentation
WECore::Richter::RichterMOD::RichterMOD () inline
Generates the wave tables on initialsation, while running gain values are simply looked up from these wave tables.
Definition at line 78 of file RichterMOD.h.
References WECore::Richter::RichterLFOBase::_sawTable, WECore::Richter::RichterLFOBase::_sineTable, WECore::Richter::RichterLFOBase::_squareTable, CoreMath::DOUBLE_PI, and WECore::Richter::Parameters::kWaveArraySize.
virtual WECore::Richter::RichterMOD::~RichterMOD () virtual default
WECore::Richter::RichterMOD::RichterMOD (RichterMOD & other) delete
Member Function Documentation
double WECore::Richter::RichterMOD::_calcGain () inline private
Calculates the gain value to be applied to a signal (in this case a parameter of another oscillator) which the oscillator is operating on. Outputs a value between -0.5 and 0.5. Always outputs 0 if bypassed.
Definition at line 130 of file RichterMOD.h.
References WECore::Richter::RichterLFOBase::_bypassSwitch, WECore::Richter::RichterLFOBase::_depth, and WECore::Richter::RichterLFOBase::_gain.
Referenced by calcGainInLoop(), and WECore::Richter::RichterLFOPair::calcGainInLoop().
double WECore::Richter::RichterMOD::calcGainInLoop () inline
Use this in your processing loop.
Note: Calling this method will advance the oscillators internal counters by one sample. Calling this method will return a different value each time.
Returns
The value of the LFO's output at this moment, a value between -1 and 1.
Definition at line 125 of file RichterMOD.h.
References _calcGain(), and WECore::Richter::RichterLFOBase::calcIndexAndScaleInLoop().
RichterMOD WECore::Richter::RichterMOD::operator= (RichterMOD & other) delete
Friends And Related Function Documentation
friend class RichterLFOPair friend
Definition at line 54 of file RichterMOD.h.
The documentation for this class was generated from the following file:
RichterMOD.h