WE Core: WECore::MONSTR::MONSTRBand< SampleType > Class Template Reference
WECore::MONSTR::MONSTRBand< SampleType > Class Template Reference
#include <MONSTRBand.h>
Public Member Functions
MONSTRBand (BandType bandType)
virtual ~MONSTRBand ()=default
void process2in2out (SampleType *leftSample, SampleType *rightSample, size_t numSamples)
void reset ()
Setter Methods
void setIsActive (bool val)
void setIsMuted (bool val)
void setLowCutoff (double val)
void setHighCutoff (double val)
void setBandType (BandType bandType)
void setSampleRate (double newSampleRate)
void setEffectsProcessor (std::shared_ptr< EffectsProcessor2in2out< SampleType > > processor)
Getter Methods
bool getIsActive () const
bool getIsMuted () const
double getLowCutoff () const
double getHighCutoff () const
Private Member Functions
void _filterSamples (SampleType *inLeftSamples, SampleType *inRightSamples, int numSamples)
Private Attributes
BandType _bandType
bool _isActive
bool _isMuted
double _lowCutoffHz
double _highCutoffHz
double _sampleRate
std::shared_ptr< EffectsProcessor2in2out< SampleType > > _processor
Dsp::SimpleFilter< Dsp::Butterworth::HighPass< FILTER_ORDER >, 2 > _lowCut1
Dsp::SimpleFilter< Dsp::Butterworth::HighPass< FILTER_ORDER >, 2 > _lowCut2
Dsp::SimpleFilter< Dsp::Butterworth::LowPass< FILTER_ORDER >, 2 > _highCut1
Dsp::SimpleFilter< Dsp::Butterworth::LowPass< FILTER_ORDER >, 2 > _highCut2
Static Private Attributes
static constexpr int FILTER_ORDER {2}
Detailed Description
template<typename SampleType>
class WECore::MONSTR::MONSTRBand< SampleType >
Provides processing for single frequency range in a crossover.
It is recommended to use this class through the MONSTRCrossover class.
This class contains a highpass and a lowpass filter in series (this is a roundabout way of creating a bandpass but this appeared to perform better), the passband can then be processed by a provided EffectsProcessor
Internally relies on the parameters provided in MONSTRParameters.h
See also
MONSTRCrossover
Definition at line 81 of file MONSTRBand.h.
Constructor & Destructor Documentation
MONSTRBand()
template<typename SampleType > WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand (BandType bandType) inline
Performs setup of the filters using default settings. The arguments are used to tell the MONSTRBand object which part of the frequency spectrum it will be covering as crossover filter.
NOTE: The parameters cannot both be true. This will cause undefined behaviour.
Parameters
[in] bandType Tells the band whether it is at either end of the crossover or in the middle.
Definition at line 98 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_highCut1, WECore::MONSTR::MONSTRBand< SampleType >::_highCut2, WECore::MONSTR::MONSTRBand< SampleType >::_highCutoffHz, WECore::MONSTR::MONSTRBand< SampleType >::_lowCut1, WECore::MONSTR::MONSTRBand< SampleType >::_lowCut2, WECore::MONSTR::MONSTRBand< SampleType >::_lowCutoffHz, WECore::MONSTR::MONSTRBand< SampleType >::_sampleRate, and WECore::MONSTR::MONSTRBand< SampleType >::FILTER_ORDER.
~MONSTRBand()
template<typename SampleType > virtual WECore::MONSTR::MONSTRBand< SampleType >::~MONSTRBand () virtual default
Member Function Documentation
_filterSamples()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::_filterSamples (SampleType * inLeftSamples, SampleType * inRightSamples, int numSamples) inline private
Definition at line 271 of file MONSTRBand.h.
References WECore::MONSTR::LOWER, and WECore::MONSTR::UPPER.
getHighCutoff()
template<typename SampleType > double WECore::MONSTR::MONSTRBand< SampleType >::getHighCutoff () const inline
See also
setIsActive
Definition at line 157 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_highCutoffHz.
Referenced by SCENARIO().
getIsActive()
template<typename SampleType > bool WECore::MONSTR::MONSTRBand< SampleType >::getIsActive () const inline
See also
setIsActive
Definition at line 151 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_isActive.
Referenced by SCENARIO().
getIsMuted()
template<typename SampleType > bool WECore::MONSTR::MONSTRBand< SampleType >::getIsMuted () const inline
See also
setIsActive
Definition at line 153 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_isMuted.
Referenced by SCENARIO().
getLowCutoff()
template<typename SampleType > double WECore::MONSTR::MONSTRBand< SampleType >::getLowCutoff () const inline
See also
setIsActive
Definition at line 155 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_lowCutoffHz.
Referenced by SCENARIO().
process2in2out()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::process2in2out (SampleType * leftSample, SampleType * rightSample, size_t numSamples) inline
Performs the effect processing on leftSample and rightSample. Use for stereo in->stereo out signals.
Parameters
[out] leftSample Pointer to the first sample of the left channel's buffer
[out] rightSample Pointer to the first sample of the right channel's buffer
[in] numSamples Number of samples in the buffer. The left and right buffers must be the same size.
Definition at line 240 of file MONSTRBand.h.
Referenced by SCENARIO().
reset()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::reset inline
Resets filter states. Call before beginning a new buffer of samples.
Definition at line 263 of file MONSTRBand.h.
setBandType()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setBandType (BandType bandType) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 225 of file MONSTRBand.h.
setEffectsProcessor()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setEffectsProcessor (std::shared_ptr< EffectsProcessor2in2out< SampleType > > processor) inline
Specifies the processor that this band should pass audio through.
Definition at line 141 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_processor.
setHighCutoff()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setHighCutoff (double val) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 213 of file MONSTRBand.h.
References WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY().
Referenced by SCENARIO().
setIsActive()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setIsActive (bool val) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 126 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_isActive.
Referenced by SCENARIO().
setIsMuted()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setIsMuted (bool val) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 128 of file MONSTRBand.h.
References WECore::MONSTR::MONSTRBand< SampleType >::_isMuted.
Referenced by SCENARIO().
setLowCutoff()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setLowCutoff (double val) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 201 of file MONSTRBand.h.
References WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY().
Referenced by SCENARIO().
setSampleRate()
template<typename SampleType > void WECore::MONSTR::MONSTRBand< SampleType >::setSampleRate (double newSampleRate) inline
Sets whether this band will route audio through the EffectsProcessor.
If the band is deactivated filtering will still be performed. This is so that a crossover containing multiple MONSTRBands will always be able easily to sum the output of the bands to unity gain, whether some of the MONSTRBands are bypassed or not.
Parameters
val If true, stereo width processing will be applied
Definition at line 230 of file MONSTRBand.h.
References WECore::CoreMath::compareFloatsEqual().
Member Data Documentation
_bandType
template<typename SampleType > BandType WECore::MONSTR::MONSTRBand< SampleType >::_bandType private
Definition at line 178 of file MONSTRBand.h.
_highCut1
template<typename SampleType > Dsp::SimpleFilter<Dsp::Butterworth::LowPass<FILTER_ORDER>, 2> WECore::MONSTR::MONSTRBand< SampleType >::_highCut1 private
Definition at line 194 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_highCut2
template<typename SampleType > Dsp::SimpleFilter<Dsp::Butterworth::LowPass<FILTER_ORDER>, 2> WECore::MONSTR::MONSTRBand< SampleType >::_highCut2 private
Definition at line 195 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_highCutoffHz
template<typename SampleType > double WECore::MONSTR::MONSTRBand< SampleType >::_highCutoffHz private
Definition at line 184 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::getHighCutoff(), and WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_isActive
template<typename SampleType > bool WECore::MONSTR::MONSTRBand< SampleType >::_isActive private
Definition at line 180 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::getIsActive(), and WECore::MONSTR::MONSTRBand< SampleType >::setIsActive().
_isMuted
template<typename SampleType > bool WECore::MONSTR::MONSTRBand< SampleType >::_isMuted private
Definition at line 181 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::getIsMuted(), and WECore::MONSTR::MONSTRBand< SampleType >::setIsMuted().
_lowCut1
template<typename SampleType > Dsp::SimpleFilter<Dsp::Butterworth::HighPass<FILTER_ORDER>, 2> WECore::MONSTR::MONSTRBand< SampleType >::_lowCut1 private
Definition at line 192 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_lowCut2
template<typename SampleType > Dsp::SimpleFilter<Dsp::Butterworth::HighPass<FILTER_ORDER>, 2> WECore::MONSTR::MONSTRBand< SampleType >::_lowCut2 private
Definition at line 193 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_lowCutoffHz
template<typename SampleType > double WECore::MONSTR::MONSTRBand< SampleType >::_lowCutoffHz private
Definition at line 183 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::getLowCutoff(), and WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
_processor
template<typename SampleType > std::shared_ptr<EffectsProcessor2in2out<SampleType> > WECore::MONSTR::MONSTRBand< SampleType >::_processor private
Definition at line 188 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::setEffectsProcessor().
_sampleRate
template<typename SampleType > double WECore::MONSTR::MONSTRBand< SampleType >::_sampleRate private
Definition at line 186 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
FILTER_ORDER
template<typename SampleType > constexpr int WECore::MONSTR::MONSTRBand< SampleType >::FILTER_ORDER {2} static constexpr private
Definition at line 190 of file MONSTRBand.h.
Referenced by WECore::MONSTR::MONSTRBand< SampleType >::MONSTRBand().
The documentation for this class was generated from the following file:
MONSTRBand.h