WE Core: WECore::SimpleCompressor::SimpleCompressor< SampleType > Class Template Reference
WECore::SimpleCompressor::SimpleCompressor< SampleType > Class Template Reference
#include <SimpleCompressor.h>
Public Member Functions
SimpleCompressor ()
virtual ~SimpleCompressor () override=default
virtual void process1in1out (SampleType *inSamples, size_t numSamples) override
virtual void reset () override
Setter Methods
void setSampleRate (double val)
void setDirection (Direction val)
void setAttack (double val)
void setRelease (double val)
void setThreshold (double val)
void setRatio (double val)
void setKneeWidth (double val)
Getter Methods
Direction getDirection () const
double getAttack () const
double getRelease () const
double getThreshold () const
double getRatio () const
double getKneeWidth () const
SampleType getGainApplied () const
Public Member Functions inherited from WECore::EffectsProcessor1in1out< SampleType >
EffectsProcessor1in1out ()=default
virtual ~EffectsProcessor1in1out ()=default
Public Member Functions inherited from WECore::EffectsProcessorBase< SampleType >
EffectsProcessorBase ()=default
virtual ~EffectsProcessorBase ()=default
Private Member Functions
double _calcCoef (double timeMs)
SampleType _computeLevel (SampleType inSample)
SampleType _computeGain (SampleType inSample)
Private Attributes
Direction _direction
double _sampleRate
double _attackMs
double _attackCoef
double _releaseMs
double _releaseCoef
double _threshold
double _ratio
double _kneeWidth
SampleType _levelDetectorState
SampleType _gainApplied
Detailed Description
template<typename SampleType>
class WECore::SimpleCompressor::SimpleCompressor< SampleType >
Simple implementation of a feedforward log domain compressor supporting both upward and downward compression types.
Definition at line 40 of file SimpleCompressor.h.
Constructor & Destructor Documentation
SimpleCompressor()
template<typename SampleType > WECore::SimpleCompressor::SimpleCompressor< SampleType >::SimpleCompressor
Definition at line 178 of file SimpleCompressor.h.
References WECore::SimpleCompressor::DOWNWARD, and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setSampleRate().
~SimpleCompressor()
template<typename SampleType > virtual WECore::SimpleCompressor::SimpleCompressor< SampleType >::~SimpleCompressor () override virtual default
Member Function Documentation
_calcCoef()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_calcCoef (double timeMs) inline private
Definition at line 170 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_sampleRate.
_computeGain()
template<typename SampleType > SampleType WECore::SimpleCompressor::SimpleCompressor< SampleType >::_computeGain (SampleType inSample) inline private
Definition at line 266 of file SimpleCompressor.h.
References WECore::SimpleCompressor::DOWNWARD.
_computeLevel()
template<typename SampleType > SampleType WECore::SimpleCompressor::SimpleCompressor< SampleType >::_computeLevel (SampleType inSample) inline private
Definition at line 254 of file SimpleCompressor.h.
getAttack()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::getAttack () const inline
See also
setAttack
Definition at line 120 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_attackMs.
Referenced by SCENARIO().
getDirection()
template<typename SampleType > Direction WECore::SimpleCompressor::SimpleCompressor< SampleType >::getDirection () const inline
See also
setDirection
Definition at line 115 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_direction.
Referenced by SCENARIO().
getGainApplied()
template<typename SampleType > SampleType WECore::SimpleCompressor::SimpleCompressor< SampleType >::getGainApplied () const inline
Returns the last gain value applied to an input signal.
Definition at line 145 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_gainApplied.
getKneeWidth()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::getKneeWidth () const inline
See also
setKneeWidth
Definition at line 140 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_kneeWidth.
Referenced by SCENARIO().
getRatio()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRatio () const inline
See also
setRatio
Definition at line 135 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_ratio.
Referenced by SCENARIO().
getRelease()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRelease () const inline
See also
setRelease
Definition at line 125 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_releaseMs.
Referenced by SCENARIO().
getThreshold()
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::getThreshold () const inline
See also
setThreshold
Definition at line 130 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_threshold.
Referenced by SCENARIO().
process1in1out()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::process1in1out (SampleType * inSamples, size_t numSamples) inline override virtual
Implements WECore::EffectsProcessor1in1out< SampleType >.
Definition at line 224 of file SimpleCompressor.h.
References WECore::CoreMath::dBToLinear(), and WECore::CoreMath::linearTodB().
Referenced by SCENARIO().
reset()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::reset inline override virtual
Resets the internal state of the processor.
Override this to reset everything as necessary.
Reimplemented from WECore::EffectsProcessorBase< SampleType >.
Definition at line 248 of file SimpleCompressor.h.
setAttack()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setAttack (double val) inline
Sets the attack time in milliseconds.
Parameters
val The attack to be applied.
See also
ATTACK for valid values
Definition at line 212 of file SimpleCompressor.h.
References WECore::SimpleCompressor::Parameters::ATTACK_MS().
Referenced by SCENARIO().
setDirection()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setDirection (Direction val) inline
Sets whether the compressor operates in upward or downward mode.
Parameters
val The mode to be applied
Definition at line 204 of file SimpleCompressor.h.
Referenced by SCENARIO().
setKneeWidth()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setKneeWidth (double val) inline
Sets the knee width.
Parameters
val The knee width to be applied.
See also
KNEE_WIDTH for valid values
Definition at line 105 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_kneeWidth, and WECore::SimpleCompressor::Parameters::KNEE_WIDTH().
Referenced by SCENARIO().
setRatio()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRatio (double val) inline
Sets the compression ratio.
Parameters
val The ratio to be applied.
See also
RATIO for valid values
Definition at line 96 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_ratio, and WECore::SimpleCompressor::Parameters::RATIO().
Referenced by SCENARIO().
setRelease()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRelease (double val) inline
Sets the release time in milliseconds.
Parameters
val The release to be applied.
See also
RELEASE for valid values
Definition at line 218 of file SimpleCompressor.h.
References WECore::SimpleCompressor::Parameters::RELEASE_MS().
Referenced by SCENARIO().
setSampleRate()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setSampleRate (double val) inline
Sets the sample rate being used.
Parameters
val The sample rate
Definition at line 192 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::SimpleCompressor().
setThreshold()
template<typename SampleType > void WECore::SimpleCompressor::SimpleCompressor< SampleType >::setThreshold (double val) inline
Sets the threshold in dB.
Parameters
val The threshold to be applied.
See also
THRESHOLD for valid values
Definition at line 87 of file SimpleCompressor.h.
References WECore::SimpleCompressor::SimpleCompressor< SampleType >::_threshold, and WECore::SimpleCompressor::Parameters::THRESHOLD().
Referenced by SCENARIO().
Member Data Documentation
_attackCoef
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_attackCoef private
Definition at line 160 of file SimpleCompressor.h.
_attackMs
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_attackMs private
Definition at line 159 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getAttack().
_direction
template<typename SampleType > Direction WECore::SimpleCompressor::SimpleCompressor< SampleType >::_direction private
Definition at line 155 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getDirection().
_gainApplied
template<typename SampleType > SampleType WECore::SimpleCompressor::SimpleCompressor< SampleType >::_gainApplied private
Definition at line 168 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getGainApplied().
_kneeWidth
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_kneeWidth private
Definition at line 165 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getKneeWidth(), and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setKneeWidth().
_levelDetectorState
template<typename SampleType > SampleType WECore::SimpleCompressor::SimpleCompressor< SampleType >::_levelDetectorState private
Definition at line 167 of file SimpleCompressor.h.
_ratio
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_ratio private
Definition at line 164 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRatio(), and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRatio().
_releaseCoef
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_releaseCoef private
Definition at line 162 of file SimpleCompressor.h.
_releaseMs
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_releaseMs private
Definition at line 161 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getRelease().
_sampleRate
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_sampleRate private
Definition at line 157 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::_calcCoef().
_threshold
template<typename SampleType > double WECore::SimpleCompressor::SimpleCompressor< SampleType >::_threshold private
Definition at line 163 of file SimpleCompressor.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::getThreshold(), and WECore::SimpleCompressor::SimpleCompressor< SampleType >::setThreshold().
The documentation for this class was generated from the following file:
SimpleCompressor.h