WE Core: WECore::MONSTR::Parameters Namespace Reference
WECore::MONSTR::Parameters Namespace Reference
Functions
const ParameterDefinition::RangedParameter< double > CROSSOVER_FREQUENCY (40, 19500, 500)
const ParameterDefinition::RangedParameter< int > NUM_BANDS (2, _MAX_NUM_BANDS, _DEFAULT_NUM_BANDS)
Variables
constexpr bool BANDSWITCH_OFF {false}
constexpr bool BANDSWITCH_ON {true}
constexpr bool BANDSWITCH_DEFAULT {BANDSWITCH_ON}
constexpr bool BANDMUTED_OFF {false}
constexpr bool BANDMUTED_ON {true}
constexpr bool BANDMUTED_DEFAULT {BANDMUTED_OFF}
constexpr bool BANDSOLO_OFF {false}
constexpr bool BANDSOLO_ON {true}
constexpr bool BANDSOLO_DEFAULT {BANDSOLO_OFF}
constexpr int _MAX_NUM_BANDS {6}
constexpr int _DEFAULT_NUM_BANDS {3}
constexpr double CROSSOVER_LOWER_DEFAULT {100}
constexpr double CROSSOVER_UPPER_DEFAULT {5000}
Function Documentation
CROSSOVER_FREQUENCY()
const ParameterDefinition::RangedParameter< double > WECore::MONSTR::Parameters::CROSSOVER_FREQUENCY (40 , 19500 , 500)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), SCENARIO(), WECore::MONSTR::MONSTRCrossover< SampleType >::setCrossoverFrequency(), WECore::MONSTR::MONSTRBand< SampleType >::setHighCutoff(), and WECore::MONSTR::MONSTRBand< SampleType >::setLowCutoff().
NUM_BANDS()
const ParameterDefinition::RangedParameter< int > WECore::MONSTR::Parameters::NUM_BANDS (2 , _MAX_NUM_BANDS , _DEFAULT_NUM_BANDS)
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::addBand(), WECore::MONSTR::MONSTRCrossover< SampleType >::removeBand(), and WECore::MONSTR::MONSTRCrossover< SampleType >::setNumBands().
Variable Documentation
_DEFAULT_NUM_BANDS
constexpr int WECore::MONSTR::Parameters::_DEFAULT_NUM_BANDS {3} constexpr
Definition at line 41 of file MONSTRParameters.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover().
_MAX_NUM_BANDS
constexpr int WECore::MONSTR::Parameters::_MAX_NUM_BANDS {6} constexpr
Definition at line 40 of file MONSTRParameters.h.
BANDMUTED_DEFAULT
constexpr bool WECore::MONSTR::Parameters::BANDMUTED_DEFAULT {BANDMUTED_OFF}
Definition at line 33 of file MONSTRParameters.h.
BANDMUTED_OFF
constexpr bool WECore::MONSTR::Parameters::BANDMUTED_OFF {false}
Definition at line 31 of file MONSTRParameters.h.
BANDMUTED_ON
constexpr bool WECore::MONSTR::Parameters::BANDMUTED_ON {true}
Definition at line 32 of file MONSTRParameters.h.
BANDSOLO_DEFAULT
constexpr bool WECore::MONSTR::Parameters::BANDSOLO_DEFAULT {BANDSOLO_OFF}
Definition at line 37 of file MONSTRParameters.h.
BANDSOLO_OFF
constexpr bool WECore::MONSTR::Parameters::BANDSOLO_OFF {false}
Definition at line 35 of file MONSTRParameters.h.
BANDSOLO_ON
constexpr bool WECore::MONSTR::Parameters::BANDSOLO_ON {true}
Definition at line 36 of file MONSTRParameters.h.
BANDSWITCH_DEFAULT
constexpr bool WECore::MONSTR::Parameters::BANDSWITCH_DEFAULT {BANDSWITCH_ON}
Definition at line 29 of file MONSTRParameters.h.
BANDSWITCH_OFF
constexpr bool WECore::MONSTR::Parameters::BANDSWITCH_OFF {false} constexpr
Definition at line 27 of file MONSTRParameters.h.
BANDSWITCH_ON
constexpr bool WECore::MONSTR::Parameters::BANDSWITCH_ON {true}
Definition at line 28 of file MONSTRParameters.h.
CROSSOVER_LOWER_DEFAULT
constexpr double WECore::MONSTR::Parameters::CROSSOVER_LOWER_DEFAULT {100} constexpr
Definition at line 43 of file MONSTRParameters.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover().
CROSSOVER_UPPER_DEFAULT
constexpr double WECore::MONSTR::Parameters::CROSSOVER_UPPER_DEFAULT {5000} constexpr
Definition at line 44 of file MONSTRParameters.h.
Referenced by WECore::MONSTR::MONSTRCrossover< SampleType >::MONSTRCrossover().