WE Core: WECore::Perlin Namespace Reference
WECore::Perlin Namespace Reference
Namespaces
namespace Parameters
Classes
class PerlinSource
Functions
float fade (float t)
float lerp (float a, float b, float t)
float grad (int hash, float x)
float perlin1D (float x, const std::vector< int > &permutation)
Function Documentation
fade()
float WECore::Perlin::fade (float t) inline
Definition at line 31 of file PerlinSource.hpp.
Referenced by perlin1D().
grad()
float WECore::Perlin::grad (int hash, float x) inline
Definition at line 39 of file PerlinSource.hpp.
Referenced by perlin1D().
lerp()
float WECore::Perlin::lerp (float a, float b, float t) inline
Definition at line 35 of file PerlinSource.hpp.
Referenced by perlin1D().
perlin1D()
float WECore::Perlin::perlin1D (float x, const std::vector< int > & permutation) inline
Definition at line 51 of file PerlinSource.hpp.
References fade(), grad(), and lerp().
Referenced by WECore::Perlin::PerlinSource::_getNextOutputImpl().