WE Core: WECore::Carve::Parameters Namespace Reference
WECore::Carve::Parameters Namespace Reference
Classes
class ModeParameter
Functions
const
ParameterDefinition::RangedParameter
< double > PREGAIN (0, 2, 1)
const
ParameterDefinition::RangedParameter
< double > POSTGAIN (0, 2, 0.5)
const
ParameterDefinition::RangedParameter
< double > TWEAK (0, 1, 0)
Variables
const ModeParameter MODE
Function Documentation
const ParameterDefinition::RangedParameter<double> WECore::Carve::Parameters::POSTGAIN (0 , 2 , 0. 5)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Carve::CarveDSPUnit< T >::setPostGain().
const ParameterDefinition::RangedParameter<double> WECore::Carve::Parameters::PREGAIN (0 , 2 , 1)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Carve::CarveDSPUnit< T >::setPreGain().
const ParameterDefinition::RangedParameter<double> WECore::Carve::Parameters::TWEAK (0 , 1 , 0)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Carve::CarveDSPUnit< T >::setTweak().
Variable Documentation
const ModeParameter WECore::Carve::Parameters::MODE
Definition at line 45 of file CarveParameters.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::setMode().