WE Core: WECore::TPTSVF::Parameters Namespace Reference
WECore::TPTSVF::Parameters Namespace Reference
Classes
class ModeParameter
Functions
const
ParameterDefinition::RangedParameter
< double > CUTOFF (20, 20000, 20)
const
ParameterDefinition::RangedParameter
< double > Q (0.1, 20, 0.5)
const
ParameterDefinition::RangedParameter
< double > GAIN (0, 2, 1)
Variables
const ModeParameter FILTER_MODE
Function Documentation
const ParameterDefinition::RangedParameter<double> WECore::TPTSVF::Parameters::CUTOFF (20 , 20000 , 20)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::TPTSVF::TPTSVFilter< T >::setCutoff().
const ParameterDefinition::RangedParameter<double> WECore::TPTSVF::Parameters::GAIN (0 , 2 , 1)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::TPTSVF::TPTSVFilter< T >::setGain().
const ParameterDefinition::RangedParameter<double> WECore::TPTSVF::Parameters::Q (0. 1, 20 , 0. 5)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::TPTSVF::TPTSVFilter< T >::setQ().
Variable Documentation
const ModeParameter WECore::TPTSVF::Parameters::FILTER_MODE
Definition at line 40 of file TPTSVFilterParameters.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::processBlock(), WECore::TPTSVF::TPTSVFilter< T >::setMode(), and WECore::Songbird::SongbirdFormantFilter< T, NUM_FORMANTS >::SongbirdFormantFilter().