WE Core: WECore::SimpleCompressor::Parameters Namespace Reference
WECore::SimpleCompressor::Parameters Namespace Reference
Functions
const ParameterDefinition::RangedParameter< double > ATTACK_MS (0.1, 500, 10)
const ParameterDefinition::RangedParameter< double > RELEASE_MS (1, 5000, 100)
const ParameterDefinition::RangedParameter< double > THRESHOLD (-60, 0, 0)
const ParameterDefinition::RangedParameter< double > RATIO (1, 30, 2)
const ParameterDefinition::RangedParameter< double > KNEE_WIDTH (1, 10, 2)
Function Documentation
ATTACK_MS()
const ParameterDefinition::RangedParameter< double > WECore::SimpleCompressor::Parameters::ATTACK_MS (0. 1, 500 , 10)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::setAttack().
KNEE_WIDTH()
const ParameterDefinition::RangedParameter< double > WECore::SimpleCompressor::Parameters::KNEE_WIDTH (1 , 10 , 2)
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::setKneeWidth().
RATIO()
const ParameterDefinition::RangedParameter< double > WECore::SimpleCompressor::Parameters::RATIO (1 , 30 , 2)
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRatio().
RELEASE_MS()
const ParameterDefinition::RangedParameter< double > WECore::SimpleCompressor::Parameters::RELEASE_MS (1 , 5000 , 100)
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::setRelease().
THRESHOLD()
const ParameterDefinition::RangedParameter< double > WECore::SimpleCompressor::Parameters::THRESHOLD (- 60, 0 , 0)
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::setThreshold().