WE Core: WECore::AREnv::Parameters Namespace Reference
WECore::AREnv::Parameters Namespace Reference
Functions
const ParameterDefinition::RangedParameter< double > ATTACK_MS (0.1, 10000, 20)
const ParameterDefinition::RangedParameter< double > RELEASE_MS (0.1, 10000, 200)
const ParameterDefinition::RangedParameter< double > LOW_CUT (TPTSVF::Parameters::CUTOFF.minValue, TPTSVF::Parameters::CUTOFF.maxValue, 0)
const ParameterDefinition::RangedParameter< double > HIGH_CUT (TPTSVF::Parameters::CUTOFF.minValue, TPTSVF::Parameters::CUTOFF.maxValue, 20000)
const ParameterDefinition::BooleanParameter FILTER_ENABLED (false)
Function Documentation
ATTACK_MS()
const ParameterDefinition::RangedParameter< double > WECore::AREnv::Parameters::ATTACK_MS (0. 1, 10000 , 20)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::AREnv::AREnvelopeFollowerBase::setAttackTimeMs().
FILTER_ENABLED()
const ParameterDefinition::BooleanParameter WECore::AREnv::Parameters::FILTER_ENABLED (false)
HIGH_CUT()
const ParameterDefinition::RangedParameter< double > WECore::AREnv::Parameters::HIGH_CUT (TPTSVF::Parameters::CUTOFF. minValue, TPTSVF::Parameters::CUTOFF. maxValue, 20000)
Referenced by WECore::AREnv::AREnvelopeFollowerBase::AREnvelopeFollowerBase().
LOW_CUT()
const ParameterDefinition::RangedParameter< double > WECore::AREnv::Parameters::LOW_CUT (TPTSVF::Parameters::CUTOFF. minValue, TPTSVF::Parameters::CUTOFF. maxValue, 0)
Referenced by WECore::AREnv::AREnvelopeFollowerBase::AREnvelopeFollowerBase().
RELEASE_MS()
const ParameterDefinition::RangedParameter< double > WECore::AREnv::Parameters::RELEASE_MS (0. 1, 10000 , 200)
Referenced by WECore::AREnv::AREnvelopeFollowerBase::setReleaseTimeMs().