WE Core: WECore::Perlin::Parameters Namespace Reference
WECore::Perlin::Parameters Namespace Reference
Classes
class OutputModeParameter
Variables
const ParameterDefinition::RangedParameter< double > FREQ (0, 20, 1)
const ParameterDefinition::RangedParameter< double > DEPTH (0, 1, 0.5)
const OutputModeParameter OUTPUTMODE
Variable Documentation
DEPTH
const ParameterDefinition::RangedParameter< double > WECore::Perlin::Parameters::DEPTH(0, 1, 0.5) (0 , 1 , 0. 5)
Referenced by WECore::Perlin::PerlinSource::_getNextOutputImpl(), and WECore::Perlin::PerlinSource::setDepth().
FREQ
const ParameterDefinition::RangedParameter< double > WECore::Perlin::Parameters::FREQ(0, 20, 1) (0 , 20 , 1)
Referenced by WECore::Perlin::PerlinSource::_getNextOutputImpl(), and WECore::Perlin::PerlinSource::setFreq().
OUTPUTMODE
const OutputModeParameter WECore::Perlin::Parameters::OUTPUTMODE
Definition at line 84 of file PerlinSource.hpp.
Referenced by WECore::Perlin::PerlinSource::_getNextOutputImpl(), and WECore::Perlin::PerlinSource::setOutputMode().