WE Core: WECore::Songbird::Parameters Namespace Reference
WECore::Songbird::Parameters Namespace Reference
Classes
class VowelParameter
Functions
const
ParameterDefinition::RangedParameter
< double > FILTER_POSITION (0, 1, 0.5)
const
ParameterDefinition::RangedParameter
< double > MIX (0, 1, 1)
const
ParameterDefinition::RangedParameter
< double > MODULATION (-1, 1, 0)
Variables
const VowelParameter VOWEL
constexpr bool MODMODE_BLEND = false
constexpr bool MODMODE_FREQ = true
constexpr bool MODMODE_DEFAULT = MODMODE_BLEND
constexpr int FILTER_ORDER {8}
Function Documentation
const ParameterDefinition::RangedParameter<double> WECore::Songbird::Parameters::FILTER_POSITION (0 , 1 , 0. 5)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Songbird::SongbirdFilterModule< T >::setFilterPosition().
const ParameterDefinition::RangedParameter<double> WECore::Songbird::Parameters::MIX (0 , 1 , 1)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Songbird::SongbirdFilterModule< T >::setMix().
const ParameterDefinition::RangedParameter<double> WECore::Songbird::Parameters::MODULATION (- 1, 1 , 0)
A parameter which can take any float value between the ranges defined. The values passed on construction are in the following order: minimum value, maximum value, default value
Referenced by WECore::Songbird::SongbirdFilterModule< T >::setModulation().
Variable Documentation
constexpr int WECore::Songbird::Parameters::FILTER_ORDER {8}
Definition at line 59 of file SongbirdFiltersParameters.h.
Referenced by WECore::MONSTR::MONSTRBand< T >::setHighCutoff(), and WECore::MONSTR::MONSTRBand< T >::setLowCutoff().
constexpr bool WECore::Songbird::Parameters::MODMODE_BLEND = false
Definition at line 55 of file SongbirdFiltersParameters.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::Process1in1out(), and WECore::Songbird::SongbirdFilterModule< T >::Process2in2out().
constexpr bool WECore::Songbird::Parameters::MODMODE_DEFAULT = MODMODE_BLEND
Definition at line 57 of file SongbirdFiltersParameters.h.
constexpr bool WECore::Songbird::Parameters::MODMODE_FREQ = true
Definition at line 56 of file SongbirdFiltersParameters.h.
const VowelParameter WECore::Songbird::Parameters::VOWEL
Definition at line 40 of file SongbirdFiltersParameters.h.
Referenced by WECore::Songbird::SongbirdFilterModule< T >::setVowel1(), and WECore::Songbird::SongbirdFilterModule< T >::setVowel2().