WE Core: CoreMath Namespace Reference
CoreMath Namespace Reference
Functions
template<typename T >
bool compareFloatsEqual (T x, T y, T tolerance=std::numeric_limits< T >::epsilon())
double linearTodB (double val)
double dBToLinear (double val)
Variables
constexpr long double LONG_PI {3.14159265358979323846264338327950288}
constexpr double DOUBLE_PI {static_cast<double>(LONG_PI)}
constexpr long double LONG_TAU {2 * LONG_PI}
constexpr double DOUBLE_TAU {static_cast<double>(LONG_TAU)}
constexpr long double LONG_E {2.71828182845904523536028747135266250}
constexpr double DOUBLE_E {static_cast<double>(LONG_E)}
constexpr double MINUS_INF_DB {-200}
Detailed Description
Contains generic math related consts and functions.
Function Documentation
compareFloatsEqual()
template<typename T > bool CoreMath::compareFloatsEqual (T x, T y, T tolerance = std::numeric_limits<T>::epsilon())
Definition at line 47 of file CoreMath.h.
Referenced by WECore::Richter::RichterLFO::calcIndexAndScaleInLoop(), and WECore::MONSTR::MONSTRBand< SampleType >::setSampleRate().
dBToLinear()
double CoreMath::dBToLinear (double val) inline
Definition at line 53 of file CoreMath.h.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::process1in1out(), and WECore::Songbird::SongbirdFormantFilter< T, NUM_FORMANTS >::setFormants().
linearTodB()
double CoreMath::linearTodB (double val) inline
Definition at line 52 of file CoreMath.h.
References MINUS_INF_DB.
Referenced by WECore::SimpleCompressor::SimpleCompressor< SampleType >::process1in1out().
Variable Documentation
DOUBLE_E
constexpr double CoreMath::DOUBLE_E {static_cast<double>(LONG_E)} constexpr
Definition at line 44 of file CoreMath.h.
Referenced by WECore::Carve::CarveDSPUnit< T >::_processExponent().
DOUBLE_PI
constexpr double CoreMath::DOUBLE_PI {static_cast<double>(LONG_PI)} constexpr
Definition at line 38 of file CoreMath.h.
Referenced by WECore::TPTSVF::TPTSVFilter< T >::_calculateCoefficients(), WECore::Carve::CarveDSPUnit< T >::_processAsymmetricSine(), WECore::Carve::CarveDSPUnit< T >::_processClipper(), WECore::Carve::CarveDSPUnit< T >::_processParabolicHard(), WECore::Carve::CarveDSPUnit< T >::_processParabolicSoft(), WECore::Carve::CarveDSPUnit< T >::_processSine(), WECore::LookAndFeelMixins::MidAnchoredRotarySlider< BASE >::drawRotarySlider(), WECore::LookAndFeelMixins::RotarySliderV2< BASE >::drawRotarySlider(), WECore::JUCEPlugin::CoreLookAndFeel::drawRotarySlider(), and WECore::Richter::Wavetables::Wavetables().
DOUBLE_TAU
constexpr double CoreMath::DOUBLE_TAU {static_cast<double>(LONG_TAU)} constexpr
Definition at line 41 of file CoreMath.h.
Referenced by WECore::LookAndFeelMixins::MidAnchoredRotarySlider< BASE >::drawRotarySlider(), WECore::LookAndFeelMixins::RotarySliderV2< BASE >::drawRotarySlider(), and WECore::Richter::Wavetables::Wavetables().
LONG_E
constexpr long double CoreMath::LONG_E {2.71828182845904523536028747135266250} constexpr
Definition at line 43 of file CoreMath.h.
LONG_PI
constexpr long double CoreMath::LONG_PI {3.14159265358979323846264338327950288} constexpr
Used for portability since Visual Studio has a different implementation of math.h
Definition at line 37 of file CoreMath.h.
LONG_TAU
constexpr long double CoreMath::LONG_TAU {2 * LONG_PI} constexpr
Definition at line 40 of file CoreMath.h.
MINUS_INF_DB
constexpr double CoreMath::MINUS_INF_DB {-200} constexpr
Definition at line 51 of file CoreMath.h.
Referenced by linearTodB().