WE Core: WECore::Richter::Parameters Namespace Reference
WECore::Richter::Parameters Namespace Reference
Classes
class WaveParameter
Functions
const ParameterDefinition::RangedParameter< int > TEMPONUMER (1, 16, 1)
const ParameterDefinition::RangedParameter< int > TEMPODENOM (1, 32, 1)
const ParameterDefinition::RangedParameter< double > DEPTH (0, 1, 0.5)
const ParameterDefinition::RangedParameter< double > DEPTHMOD (0, 1, 0)
const ParameterDefinition::RangedParameter< double > FREQ (0.5, 20, 2)
const ParameterDefinition::RangedParameter< double > FREQMOD (0, 1, 0)
const ParameterDefinition::RangedParameter< double > PHASE (0, 360, 0)
Variables
const WaveParameter WAVE
constexpr bool LFOSWITCH_OFF = false
constexpr bool LFOSWITCH_ON = true
constexpr bool LFOSWITCH_DEFAULT = LFOSWITCH_OFF
constexpr bool TEMPOSYNC_OFF = false
constexpr bool TEMPOSYNC_ON = true
constexpr bool TEMPOSYNC_DEFAULT = TEMPOSYNC_OFF
constexpr bool PHASESYNC_OFF = false
constexpr bool PHASESYNC_ON = true
constexpr bool PHASESYNC_DEFAULT = PHASESYNC_ON
constexpr bool INVERT_OFF = false
constexpr bool INVERT_ON = true
constexpr bool INVERT_DEFAULT = INVERT_OFF
Function Documentation
DEPTH()
const ParameterDefinition::RangedParameter< double > WECore::Richter::Parameters::DEPTH (0 , 1 , 0. 5)
Referenced by WECore::Richter::RichterLFO::_getNextOutputImpl(), and WECore::Richter::RichterLFO::setDepth().
DEPTHMOD()
const ParameterDefinition::RangedParameter< double > WECore::Richter::Parameters::DEPTHMOD (0 , 1 , 0)
Referenced by WECore::Richter::RichterLFO::setDepthMod().
FREQ()
const ParameterDefinition::RangedParameter< double > WECore::Richter::Parameters::FREQ (0. 5, 20 , 2)
Referenced by WECore::Richter::RichterLFO::_calcFreq(), and WECore::Richter::RichterLFO::setFreq().
FREQMOD()
const ParameterDefinition::RangedParameter< double > WECore::Richter::Parameters::FREQMOD (0 , 1 , 0)
Referenced by WECore::Richter::RichterLFO::setFreqMod().
PHASE()
const ParameterDefinition::RangedParameter< double > WECore::Richter::Parameters::PHASE (0 , 360 , 0)
Referenced by WECore::Richter::RichterLFO::_calcPhaseOffset(), WECore::Richter::WaveViewer::paint(), and WECore::Richter::RichterLFO::setManualPhase().
TEMPODENOM()
const ParameterDefinition::RangedParameter< int > WECore::Richter::Parameters::TEMPODENOM (1 , 32 , 1)
Referenced by WECore::Richter::RichterLFO::setTempoDenom().
TEMPONUMER()
const ParameterDefinition::RangedParameter< int > WECore::Richter::Parameters::TEMPONUMER (1 , 16 , 1)
Referenced by WECore::Richter::RichterLFO::setTempoNumer().
Variable Documentation
INVERT_DEFAULT
constexpr bool WECore::Richter::Parameters::INVERT_DEFAULT = INVERT_OFF
Definition at line 64 of file RichterParameters.h.
INVERT_OFF
constexpr bool WECore::Richter::Parameters::INVERT_OFF = false
Definition at line 62 of file RichterParameters.h.
INVERT_ON
constexpr bool WECore::Richter::Parameters::INVERT_ON = true
Definition at line 63 of file RichterParameters.h.
LFOSWITCH_DEFAULT
constexpr bool WECore::Richter::Parameters::LFOSWITCH_DEFAULT = LFOSWITCH_OFF
Definition at line 52 of file RichterParameters.h.
LFOSWITCH_OFF
constexpr bool WECore::Richter::Parameters::LFOSWITCH_OFF = false constexpr
Definition at line 50 of file RichterParameters.h.
LFOSWITCH_ON
constexpr bool WECore::Richter::Parameters::LFOSWITCH_ON = true
Definition at line 51 of file RichterParameters.h.
PHASESYNC_DEFAULT
constexpr bool WECore::Richter::Parameters::PHASESYNC_DEFAULT = PHASESYNC_ON
Definition at line 60 of file RichterParameters.h.
PHASESYNC_OFF
constexpr bool WECore::Richter::Parameters::PHASESYNC_OFF = false
Definition at line 58 of file RichterParameters.h.
PHASESYNC_ON
constexpr bool WECore::Richter::Parameters::PHASESYNC_ON = true
Definition at line 59 of file RichterParameters.h.
TEMPOSYNC_DEFAULT
constexpr bool WECore::Richter::Parameters::TEMPOSYNC_DEFAULT = TEMPOSYNC_OFF
Definition at line 56 of file RichterParameters.h.
TEMPOSYNC_OFF
constexpr bool WECore::Richter::Parameters::TEMPOSYNC_OFF = false
Definition at line 54 of file RichterParameters.h.
TEMPOSYNC_ON
constexpr bool WECore::Richter::Parameters::TEMPOSYNC_ON = true
Definition at line 55 of file RichterParameters.h.
WAVE
const WaveParameter WECore::Richter::Parameters::WAVE
Definition at line 39 of file RichterParameters.h.
Referenced by WECore::Richter::RichterLFO::setWave().