name: Build and Test

on: [push, pull_request]

jobs:
  BuildClang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/BuildAndTest.sh
      - uses: actions/upload-artifact@v4
        with:
          name: callgrind-clang
          path: build/callgrind.out.*

  BuildGCC:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/BuildAndTest.sh
      - uses: actions/upload-artifact@v4
        with:
          name: callgrind-gcc
          path: build/callgrind.out.*
