name: Static Analysis

on: [push, pull_request]

jobs:
  StaticAnalysis:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunStaticAnalysis
        run: Scripts/StaticAnalysis.sh
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: clang-tidy
          path: clang-tidy.txt
